### PR TITLE
Log when number of available FDs is insufficient (RIPD-1125)

### PR DESCRIPTION
**Pull request by nbougalis**
Reviews: @miguelportilla, @wilsonianb

### CODE REVIEW

**Comment by wilsonianb** [comment]
LGTM :+1: 
`2016-May-04 18:32:48 Application:FTL Insufficient number of file descriptors: 4928 are needed, but only 1024 are available.`

**Comment by miguelportilla** [comment]
:+1:

**Comment by HowardHinnant** [comment]
Needs rebase to b10.

**Comment by HowardHinnant** [comment]
merged.

**Pull request closed without merging**
