### PR TITLE
Remove outdated example configs.

### PR DESCRIPTION
**Pull request by mtrippled**

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
Maybe these could be updated instead of removed?

**Comment by mtrippled** [comment]
@MarkusTeufelberger SysVInit is essentially deprecated in the Linux world in favor of SystemD.

**Comment by MarkusTeufelberger** [comment]
Yes, but you also want to remove the Systemd unit file. I agree about the SysVInit one (though there are still a few rebels out there, e.g. Alpine Linux, which is relatively often used in Docker base containers, but then again these don't need a service file).

**Comment by nbougalis** [comment]
> SysVInit is essentially deprecated in the Linux world in favor of SystemD.

And how sad and unfortunate is that... :cry:

But more to the point: I'm not sure if we want these in the repo; they're borderline distribution-specific and I'm not sure they help very much as is. It'd be different if we had a "packages" folder with code to built distribution-specific packages and those files were in the appropriate folder, but as is they feel a bit random.

**Comment by mellery451** [comment]
merged as e98c76110

**Pull request closed without merging**
