### PR TITLE
Whitespace only: Remove trailing spaces in rippled code.

### PR DESCRIPTION
**Pull request by rec**
I realized I was getting rusty on Python so I wrote a tool to get rid of trailing spaces and split long lines (that one takes human interaction).

Here's the first part of it - trailing spaces.  It turns out that we also have a lot of control-Ms so I got rid of those too.

@nbougalis @ximinez

### CODE REVIEW

**Comment by nbougalis** [comment]
Obviously correct... :+1:

**Comment by ximinez** [comment]
Obviously correct. `git diff -w HEAD^` shows no differences.  :+1:

**Comment by rec** [comment]
The advantage of a script!

https://github.com/rec/cprep/blob/master/cprep.py

It also does a hack job on "restrict to 80 columns" - the one cleverness is
that it also opens up each edit in my editor so I can correct it (it does
an OK job on indentation but I decided it was better to go for "clear and
fast" over "always correct").

I'm probably going to clean the whole of rippled to 80 columns in fairly
small changelists once we get the current code checked in...

**Comment by MarkusTeufelberger** [comment]
Shouldn't this be split in seperate commits per submodule/-project? Otherwise you will be in merging hell once you upgrade SQLite, RocksDB etc.

**Comment by nbougalis** [comment]
@MarkusTeufelberger has a point - we probably shouldn't be changing the whitespace for things like Donna, RocksDB, SOCI, etc.

**Comment by vinniefalco** [comment]
The commit message is wrong. First of all we don't need to ever say "in rippled code" in a commit message since that's redundant. Second, beast sources are changed. Suggested commit message "Remove whitespace"

**Comment by rec** [comment]
URG, you're right.  Gimme a few moments to redo this, and I'll do beast and
ripple separately.

**Comment by vinniefalco** [comment]
@rec There's no need to produce two separate commits, as long as the commit message makes sense for both repositories. Suggested commit message: `Remove trailing whitespace`

**Comment by rec** [comment]
Fixed to just do ripple and beast - my original intent when fooling around with these scripts.

**Comment by vinniefalco** [comment]
@rec I don't see any change

**Comment by rec** [comment]
pushed...!

**Comment by rec** [comment]
Rebased to deal with the tiny conflict...

**Comment by ximinez** [comment]
:+1:

I'll note that now `git diff -w HEAD^` shows a line removed in apply.h. https://github.com/ripple/rippled/pull/1204/files#diff-700f4caa6a4dcacf65ddb438f87f91ecL63

**Comment by rec** [comment]
I removed the blank line during the merge.  We sometimes put a blank line after Throws and sometimes we don't.  I can easily put it back in...?

**Comment by ximinez** [comment]
I have absolutely no option. I was just pointing out the change.

**Pull request closed without merging**
