### PR TITLE
OpenLedger fixes and tidying

### PR DESCRIPTION
**Pull request by vinniefalco**
Fixes a bug with fees in `OpenLedger` and `Ledger` construction, plus various tidyings. This includes a rebased version of #1174, only the last 6 commits belong to this pull request.

### CODE REVIEW

**Comment by rec** [comment]
:-( We couldn't have done this as two pull requests?  I'd love to see just the total changes for the last six items.

**Comment by vinniefalco** [comment]
1. Even as two pull requests, the second one (The one that includes the last six items) will still have the earlier commits in the first pull request.
2. You can pull the branch and squash the last 6 commits

**Comment by vinniefalco** [comment]
@rec Here's a squashed version
https://github.com/vinniefalco/rippled/commits/openview2

**Comment by HowardHinnant** [comment]
Needs this to workaround a libc++ bug (my bad) https://github.com/HowardHinnant/rippled/commit/7c2e600147cdc5b9b03a94f2f90befd760922992
The libc++ bug has been fixed:
https://github.com/llvm-mirror/libcxx/commit/c41133728d1a4197b8d0a366854b73d161788d20
but Apple hasn't picked it up yet.

**Comment by HowardHinnant** [comment]
unittest failure on OS X / debug / nounity:
ripple.ledger.View
Assertion failed: (state_ != SHAMapState::Immutable), function delItem, file src/ripple/shamap/impl/SHAMap.cpp, line 765.

**Comment by HowardHinnant** [comment]
Suspected commit which causes unittest failure:
https://github.com/vinniefalco/rippled/commit/805e9b305becb46a18889867fdb3289cb8ad4d4a

**Comment by rec** [comment]
All right, this is looking good!

You're still getting those unit test failures on Travis - you need to patch in @HowardHinnant's change.

**Comment by HowardHinnant** [comment]
I didn't post a fix for the unittest failures.  Just a likely commit which is the cause.

**Comment by vinniefalco** [comment]
Howard's compile fix incorporated, and tests also fixed.

**Comment by HowardHinnant** [comment]
I'm still failing at compile time with the same error.

**Comment by vinniefalco** [comment]
@HowardHinnant Fixed the new call to make_shared that triggered the libc++ defect, should build now

**Comment by HowardHinnant** [comment]
Compiles without warnings and passes tests here.

**Comment by rec** [comment]
I think this is good, anything else I should re-review?

**Comment by vinniefalco** [comment]
Can't think of anything

**Comment by rec** [comment]
:+1:

**Comment by rec** [comment]
Come on, let's _do it!!_

**Comment by vinniefalco** [comment]
@rec I'd prefer if you and Nik sorted out the rebase issues so we didn't have to revert that one commit

**Comment by rec** [comment]
This is the only passed pull request - can't we just rebase it against develop and go?

**Comment by rec** [comment]
or, tell me what needs to be done...

**Pull request merged**
