### PR TITLE
Resolve non-virtual destructor warning

### PR DESCRIPTION
**Pull request by seelabs**
This is the new PR for https://github.com/ripple/rippled/pull/2510

* Turn on non-virtual-destructor warning
* Resolve beast warnings
* Resolve rippled warnings

### CODE REVIEW

**Comment by seelabs** [comment]
I see the warnings about ` warning: command line option ‘-Wnon-virtual-dtor’ is valid for C++/ObjC++ but not for C`. Will fix.

**Comment by HowardHinnant** [comment]
Because of the added user-declared destructors, it becomes desirable to also add user-declared copy members to ensure we aren't relying on deprecated behavior.  This further necessitates adding defaulted default constructors in a few places.

Patch to do this:  https://github.com/HowardHinnant/rippled/commit/e28e8317905f4fa73b9fe4ab047e9d309b0c8900

**Comment by JoeLoser** [comment]
@seelabs thanks for opening this PR and fixing up the Beast warnings. It wasn't clear to me whether we wanted to fix that problem for the upstream third party code and turn on the compiler flag. Seems like others are OK with that.

**Comment by seelabs** [comment]
Added @HowardHinnant patch. This looks good to me. :+1:

**Comment by seelabs** [comment]
In 1.1.0-b1

**Pull request closed without merging**
