### PR TITLE
Proposed 0.27.0-b3

### PR DESCRIPTION
**Pull request by ximinez**
Reviewers: @vinniefalco, @ximinez, @josh-ripple, @nbougalis .

### CODE REVIEW

**Comment by josh-ripple** [comment]
I cherry-picked the commit adding ed25519 wrappers and tests, and they passed.  Looks good from my end.

**Comment by nbougalis** [comment]
:+1:

**Comment by ximinez** [comment]
:+1:

**Comment by josh-ripple** [comment]
:+1:

**Comment by vinniefalco** [comment]
:+1:

**Pull request merged**
