### PR TITLE
Use standard C++ types instead of type aliases:

### PR DESCRIPTION
**Pull request by nbougalis**
* Remove `ripple::RippleMutex` and `ripple::RippleRecursiveMutex`
  and use `std::mutex` and `std::recursive_mutex` respectively.
* Use `std::lock_guard` instead of `std::unique_lock` when the
  additional features of `std::unique_lock` are not needed.

@seelabs, @HowardHinnant

### CODE REVIEW

**Comment by HowardHinnant** [comment]
:+1:  Tests out here.  Does the vc++ project need to be rebuilt?

**Comment by nbougalis** [comment]
yes, the project does need a rebuild - I'll fix that.

**Comment by seelabs** [comment]
:+1: (assuming the vcxproj & unneeded `ScopeLockType` issues are taken care of)

**Comment by nbougalis** [comment]
I have addressed concerns and squashed.

**Pull request closed without merging**
