### PR TITLE
Remove jss::account_index and jss::peer_index.

### PR DESCRIPTION
**Pull request by rec**
@miguelportilla @nbougalis

### CODE REVIEW

**Comment by nbougalis** [comment]
:+1: modulo Vinnie's comment about the `namespace`

**Comment by rec** [comment]
Why are we getting rid of the RPC namespace?  What's this sudden obsession with moving everything into one namespace?

**Comment by rec** [comment]
Regarding `bStrict` I have an upcoming change where handlers never even see those variables - they pass in params and get back a ledger.  So I'll leave it to that...

**Comment by nbougalis** [comment]
@rec I don't think that we need to move _everything_ to the `ripple` namespace, but some of the things in the `RPC` namespace might be helpful outside.

**Comment by rec** [comment]
I think that ledgerToJson could certainly move, e.g.!

**Comment by rec** [comment]
So are we good?  This is just deleting this unused functionality.  Other changes will happen... later.

**Comment by nbougalis** [comment]
:+1:

**Comment by miguelportilla** [comment]
:+1:

**Comment by rec** [comment]
I'll rebase this before you even see this message.  :-)

**Pull request closed without merging**
