### PR TITLE
[TRIVIAL] Remove ConnectionImpl::returnMessage.

### PR DESCRIPTION
**Pull request by miguelportilla**
Remove orphaned function declaration.

### CODE REVIEW

**Comment by vinniefalco** [comment]
Gonna just throw this out there - you removed the declaration not the definition.

**Comment by ximinez** [comment]
I'm glad I'm not the only one who continually gets "delcaration" and "definition" mixed up.

**Comment by vinniefalco** [comment]
Here's an easy way to remember. Missing "definitions" cause "undefined" linker errors.

**Comment by miguelportilla** [comment]
Yeap.

**Comment by nbougalis** [comment]
Merged: 3394129894aea7862f8b027b0e906f7442c75276

**Pull request closed without merging**
