### PR TITLE
Create CNAME

### PR DESCRIPTION
**Pull request by bondareko**

### CODE REVIEW

**Comment by nbougalis** [comment]
What exactly is this?

**Comment by vinniefalco** [comment]
The CNAME links the GitHub pages to a DNS address, its for publishing html content.

**Comment by nbougalis** [comment]
Publishing HTML content? Like the help docs? And what's `ipv6.kontrakt.co` then?

**Comment by vinniefalco** [comment]
Oh! LOL... I didn't see the author. That looks shady AF. The GitHub account is "github-co" and the domain name sounds Russian. Looks like a phishing attempt.

**Pull request closed without merging**
