### PR TITLE
Get rid of warning on soci.cpp file.

### PR DESCRIPTION
**Pull request by rec**
@seelabs

### CODE REVIEW

**Comment by vinniefalco** [comment]
Prefer "Fix warning" instead of "Get rid of warning"...
I will amend the message

**Comment by vinniefalco** [comment]
There's nothing trivial about this...the flag should only be passed for clang and gcc, but not msvc.
Also, the replacement SConstruct framework needs to support this use-case.

**Comment by seelabs** [comment]
I messed this up. I tested on mac and linux to make sure the warning went away and saw the visual studio projects did not change so I did not test windows.

**Comment by vinniefalco** [comment]
But Tom is the author?

**Comment by rec** [comment]
Well... I don't see how to fix this with the current system.

This preparation happens at the top, before we decide which toolchain to use.

The new system, which I really want to get back to, handles this very easily, it's just a rule in the module - we have a lot like these.

**Comment by vinniefalco** [comment]
@rec We could put `target`, `variant`, and `toolchain` in the `Env` and then conditionally set the flag in the function that adds soci.cpp by looking at the `Env`. A workaround until your code is merged.

**Comment by rec** [comment]
what if you build with msvc and g++ on the same (Windows) system?  which does it pick?

**Comment by vinniefalco** [comment]
There's a different instance of `Env` for each target

**Comment by vinniefalco** [comment]
Closing until its fixed

**Pull request closed without merging**
