### PR TITLE
Miscellaneous cleanups:

### PR DESCRIPTION
**Pull request by nbougalis**
* Clarify use of cancel view in OfferCreate transactor
* Reduce OfferStream public interface
* Reduce severity of some developer-only logging from ERROR to DEBUG

@vinniefalco, @ximinez

### CODE REVIEW

**Comment by vinniefalco** [comment]
Suggested:
`Tidy up offer crossing`
:+1:

**Comment by ximinez** [comment]
Travis failure is not spurious: https://travis-ci.org/ripple/rippled/jobs/71452166

It also fails in Windows for the same reason.

**Comment by ximinez** [comment]
Other than the problem with `JLOG`, the changes look good.

**Comment by nbougalis** [comment]
Yeah, I forgot the header. Will fix.

**Comment by vinniefalco** [comment]
Can you please improve `JLOG`, using the structure of `WriteLog`, in a separate commit?

**Comment by nbougalis** [comment]
Yep

**Comment by nbougalis** [comment]
@HowardHinnant is `JLOG` good now?

**Comment by HowardHinnant** [comment]
Testing this is in my queue, but still a bit out...

**Comment by HowardHinnant** [comment]
non-unity build:
````
clang++ -o build/clang.release.nounity/src/ripple/app/tx/impl/SetRegularKey.o -c -Wall -frtti -std=c++11 -Wno-invalid-offsetof -Wno-mismatched-tags -Wno-deprecated-register -Wno-sign-compare -Wno-char-subscripts -Wno-format -g -Wno-redeclared-class-member -Wno-deprecated -Wno-deprecated-declarations -Wno-unused-variable -Wno-unused-function -O3 -fno-strict-aliasing -DOPENSSL_NO_SSL2 -DDEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER -DHAVE_USLEEP=1 -DBOOST_ASIO_HAS_STD_ARRAY -D_FILE_OFFSET_BITS=64 -DBEAST_COMPILE_OBJECTIVE_CPP=1 -I/usr/local/Cellar/openssl/1.0.1g/include -I/Users/howardhinnant/Development/boost_1_58_0 -Isrc -Isrc/beast -Ibuild/proto -Isrc/soci/src src/ripple/app/tx/impl/SetRegularKey.cpp
src/ripple/app/tx/impl/OfferStream.cpp:51:9: error: use of undeclared identifier 'JLOG'
        JLOG(j_.error) <<
        ^
src/ripple/app/tx/impl/OfferStream.cpp:62:9: error: use of undeclared identifier 'JLOG'
        JLOG(j_.error) <<
        ^
src/ripple/app/tx/impl/OfferStream.cpp:72:5: error: use of undeclared identifier 'JLOG'
    JLOG(j_.trace) <<
    ^
src/ripple/app/tx/impl/OfferStream.cpp:104:13: error: use of undeclared identifier 'JLOG'
            JLOG(j_.trace) <<
            ^
src/ripple/app/tx/impl/OfferStream.cpp:118:13: error: use of undeclared identifier 'JLOG'
            JLOG(j_.warning) <<
            ^
src/ripple/app/tx/impl/OfferStream.cpp:145:17: error: use of undeclared identifier 'JLOG'
                JLOG(j_.trace) <<
                ^
src/ripple/app/tx/impl/OfferStream.cpp:150:17: error: use of undeclared identifier 'JLOG'
                JLOG(j_.trace) <<
                ^
7 errors generated.
scons: *** [build/clang.release.nounity/src/ripple/app/tx/impl/OfferStream.o] Error 1
scons: building terminated because of errors.
````

**Comment by ximinez** [comment]
Ditto on @HowardHinnant's failure.

**Comment by nbougalis** [comment]
Bah, I _again_ missed adding the right header file. One second.

**Comment by ximinez** [comment]
Build works now. :+1:

**Comment by HowardHinnant** [comment]
Builds with no warnings.  Passes unittest and npm.  I've been up for 10min without sync (release + assert).  I'll give it a few more minutes, then stop and try again with a clear db...

**Comment by HowardHinnant** [comment]
Had trouble shutting it down.  Appeared to hang with 20 threads, and 2% cpu usage for about 4min.  Force-quit it.

**Comment by HowardHinnant** [comment]
Sync'd and stopped after clearing the db.

**Pull request closed without merging**
