### PR TITLE
Pathfinding cleanup:

### PR DESCRIPTION
**Pull request by nbougalis**
* Remove unused code
* Do not use `pointer` and `ref` type aliases
* Misc. cleanups

### CODE REVIEW

**Comment by HowardHinnant** [comment]
:+1: 

I am seeing a sporadic unittest failure which I do not believe is introduced with this P/R:

ripple.http.Server
Opened '' (ip=127.0.0.1:40000, http)
#85 accept:    127.0.0.1
#5 failed: shutdown: Socket is not connected
#85 destroyed: 1 request

**Comment by vinniefalco** [comment]
@HowardHinnant This fixes the spurious Server error:
https://github.com/ripple/rippled/pull/1552

**Comment by scottschurr** [comment]
:+1:

**Comment by vinniefalco** [comment]
Good changes

**Pull request closed without merging**
