### PR TITLE
Websocket 0.40

### PR DESCRIPTION
**Pull request by rec**
This is a series of changes where I first clean up our WebSocket (0.2) library a little, then create a generic interface for it, then implement that generic interface for 0.4.  

There were some fairly large differences between 0.2 and 0.4 and I still haven't resolved them all.  If you switch the default version to 0.4 it does not pass the unit tests, nor does it use the AutoSocket - but I wanted to get this out to get criticisms and suggestions.

### CODE REVIEW

**Comment by rec** [comment]
Reviewers: @miguelportilla @vinniefalco

**Comment by rec** [comment]
Reviewer: @JoelKatz

**Comment by miguelportilla** [comment]
You need to run scons vcxproj to update the VS files.

**Comment by miguelportilla** [comment]
Won't compile on Windows...

1>C:\ripple labs\rippled\src\ripple/websocket/WebSocket02.cpp(66): error C2955: 'ripple::websocket::EndpointPtr' : use of alias template requires template argument list
1>          C:\ripple labs\rippled\src\ripple/websocket/WebSocket.h(71) : see declaration of 'ripple::websocket::EndpointPtr'
1>C:\ripple labs\rippled\src\ripple/websocket/WebSocket02.cpp(69): error C2912: explicit specialization 'EndpointPtr ripple::websocket::makeEndpoint<v02>(HandlerPtr &&)' is not a specialization of a function template
1>C:\ripple labs\rippled\src\ripple/websocket/WebSocket02.cpp(69): fatal error C1903: unable to recover from previous error(s); stopping compilation

**Comment by rec** [comment]
More back and forth with Mickey, but no luck.

so the head has my best try for "correct typenames" but I don't predict it'll fix that issue.  I switched the order of two typedefs to see if very similar code with different types fails.

**Comment by HowardHinnant** [comment]
I'm pretty good at working around compiler bugs.  If you can point me to the lines of code that caused the error above (or to the current error and the lines of code it flags), I'll see if I get any ideas for workarounds.

**Comment by HowardHinnant** [comment]
Is ripple/app/websocket/WSConnection.h missing from github?

**Comment by vinniefalco** [comment]
@HowardHinnant `ripple/websocket/WSConnection.h` (not app/)

**Comment by miguelportilla** [comment]
@HowardHinnant  yes it seems to be missing from the project. Its not in the directory you mentioned either, Vinnie.

**Comment by vinniefalco** [comment]
@miguelportilla Then how did you get compile errors in WSConnection.h ?

**Comment by miguelportilla** [comment]
Ah it was renamed to Connection.h

**Comment by miguelportilla** [comment]
I did not get compile errors in WSConnection.h I was just answering Howard's question

**Comment by rec** [comment]
@HowardHinnant - you volunteered to help me get past these compilation errors on Windows, still up for it?  :-)

**Comment by HowardHinnant** [comment]
Sure!

**Comment by rec** [comment]
So this now compiles on Windows - and I rebased all the tweaks back into well-organized chunks.

Remember, there is still a zinger I haven't resolved - this brings the 02 and 04 code in in parallel, but I haven't yet figured out how to integrate the AutoSockets, and (likely as a result) I don't disconnect problem from a connection with 04.

I wanted to start the review, however, because I'd gotten so far and wanted to see if it was reasonable and would all work...

**Comment by vinniefalco** [comment]
I'm finding the structure of the classes and free functions to be quite confusing. We should make the Version its own structure with member types and functions, rather than templating a world of free functions and types at namespace scope on a Version class enum. This will simplify things greatly, do away with explicit instantiations and overloads, and possibly combine what was 4 structures down into two.

**Comment by rec** [comment]
So this is the same comment as the other two, yes?

OK, let me give this a try!  It'll be much easier now I know what it looks
like...

**Comment by vinniefalco** [comment]
@rec Yeah pretty much the same comment

**Comment by rec** [comment]
OK!  

I made the suggested restructuring, which came out well.  You can see just the new change here:  I also merged the changes into the existing change list, and it's here:  https://github.com/rec/rippled/commits/websocket-alt

**Comment by rec** [comment]
Ping ping ping ping @JoelKatz @miguelportilla 

This is getting a bit old now.  What I'd really like to do is to check this in, and then check in a later change to turn on autosockets and to make the npm tests work when v04 is turned on.

**Comment by miguelportilla** [comment]
@rec VS compiler fixes: https://github.com/miguelportilla/rippled/commits/websocket

**Comment by rec** [comment]
Ping!  ping ping ping!

**Comment by miguelportilla** [comment]
LGTM :+1:

**Comment by vinniefalco** [comment]
Needs to be completely squashed
:+1:

**Comment by rec** [comment]
All right, I squashed it as much as I felt was good. 

Reasoning:

1. the huge, boring move needs its own commit.
2. the second, tiny change is significant and needs to be noted - and doesn't fit into any other change.
3. this is a huge change that only effects existing code.
4. the 04 interface is brand-new code.
5. and there's a tiny change that's in src/websocketpp and has to be separate...

**Comment by vinniefalco** [comment]
@rec "Make websocket code generic" needs a better commit message and some exposition.

**Comment by rec** [comment]
I rewrote several commit messages.

**Comment by vinniefalco** [comment]
Much better!

**Comment by rec** [comment]
Not so fast... There's a new warning I still don't know how to get rid of.

**Comment by HowardHinnant** [comment]
What's the warning?  Maybe I can help...

**Comment by rec** [comment]
(Booted Travis, looks like a misfire.)

@HowardHinnant - here's the warning:  http://codepad.org/ef2KcbcE

Thought I got rid of it before but I didn't.  It only appears under gcc...

The crazy part is the message seems clear BUT:

1. `std::recursive_mutex` is definitely defined, and
2. this type is used successfully a few lines later!

**Comment by HowardHinnant** [comment]
Yeah, drop `typename` and the warning will go away.

**Comment by rec** [comment]
Done!

**Comment by rec** [comment]
Alls rights!

I can see that I did make this change pointed out by Mickey, and that it does change behavior.  I don't see how that would lead to a hang on shutdown exactly, but it is a behavior change that occurs on shutdown, and reverting it makes the problem going away.

**Comment by rec** [comment]
I really - really - don't want to squash this down any more.  The changes are big enough and hard enough to audit as it is.  Glueing most of these into one massive 58 file, 4000 line change makes them simply impossible.

**Pull request merged**
