### PR TITLE
Make tx() function against a read-only postgres instance.

### PR DESCRIPTION
**Pull request by mtrippled**
### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### CODE REVIEW

**Review by cjcobb23 — APPROVED** [review]

**Review by cjcobb23 — COMMENTED** [review]
Should we also bump the schema version? I know we talked about how we are the only ones running this, but we do have multiple environments. Without bumping the version, we have to deploy the change manually in all of those environments right?

**Review by natenichols — APPROVED** [review]

**Comment by mtrippled** [comment]
> 

Bumping the schema version means following the steps in the doc, which is fine I guess, but more complex.

Instead, this will ensure that any new deploiyments will get the correct version. But the way to fix existing deployments is to implement the TX stored proc at the psql shell.

**Comment by cjcobb23** [comment]
I think this would be a good opportunity to test the schema version update logic. I vote for bumping the version here.

**Comment by manojsdoshi** [comment]
@mtrippled This is already merged closing it out.

**Pull request closed without merging**
