### PR TITLE
Replaces sqdb with soci (RIPD-141).

### PR DESCRIPTION
**Pull request by seelabs**
* Brings the soci subtree into rippled.
* Validator, peerfinder, and SHAMapStore use new soci backend.
* Optional postgresql backend for soci (if POSTGRESQL_ROOT env var is set).
* BasicConfig support for legacy values.

@josh-ripple @nbougalis

### CODE REVIEW

**Comment by vinniefalco** [comment]
Consider
`BasicConfig support for legacy values:`
and
`Use soci in some places:`

**Comment by seelabs** [comment]
The travis fail is due to a rippled.cfg file without a database_path section. Will fix.

**Comment by vinniefalco** [comment]
I'd like to see two more commits placed on this:
1. Remove sqdb, sqlite from beast
2. Add sqlite to rippled at `src/sqlite/sqlite.c` etc

**Comment by nbougalis** [comment]
Also, please consider whether we can/should update to a newer version of `sqlite.c`.

**Comment by seelabs** [comment]
@vinniefalcoI I will remove beast/move sqlite and add a commit.

**Comment by seelabs** [comment]
I split some of this PR into PR #853. I am also working on another set of PR that this one will be rebased on top of. The final commit "use soci in some places" may still be reviewed.

**Comment by rec** [comment]
Ping!  This change is so old, it's encoded in EBCDIC.  :-P

**Comment by rec** [comment]
(You can always close a pull request and reopen it with all the comments intact, as long as you keep exactly the same branch behind it...)

**Comment by vinniefalco** [comment]
@josh-ripple What do you say about this?

**Comment by vinniefalco** [comment]
Why close?

**Comment by seelabs** [comment]
I'll be making a new PR on top of this one shortly (days). Since they are closely related I decided to fold them into one.

**Pull request closed without merging**
