### PR TITLE
Only report 'delivered_amount' for executed payments

### PR DESCRIPTION
**Pull request by nbougalis**
Reviews: @ximinez, @rec

### CODE REVIEW

**Comment by nbougalis** [comment]
(Must add JIRA ticket to commit message: RIPD-827)

**Comment by ximinez** [comment]
Simple and pretty clearly correct. :+1:

**Comment by rec** [comment]
Thought I'd already commented on this! 

:+1:

**Comment by nbougalis** [comment]
Merged as 040982e3210c9f459c7a684635acdb7acdde02cc

**Pull request closed without merging**
