### PR TITLE
record setting memos

### PR DESCRIPTION
**Pull request by peersafe**
Saving memos field in AccountRoot node

### CODE REVIEW

**Comment by nbougalis** [comment]
Thank you for the submission. Unfortunately, it's not quite ready for a pull request yet. Not only does it fail to pass unit tests, but the change is, at best, incomplete: it does not modify the `AccountRoot` format to allow the presence of the `sfMemos` field and it is lacking unit tests exercising the new functionality.

Moreover, it does not offer any insight on the rationale behind this change, an examination of alternative solutions/implementations or any kind of cost-benefit analysis associated with adding new fields to the `AccountRoot` object.

Please consider explaining what problem you are trying to solve/address, why this implementation is better than other possible alternative solutions and why this is a problem that must be solved or addressed in `rippled`.

**Comment by peersafe** [comment]
Yes, forget to add the sfMemos subfield of the  AccountRoot. 

I am trying to save some extra information(e.g. Username, Gender) via [settings transaction](https://ripple.com/build/rippleapi/#settings), but can not retrieve the memos via [getSettings](https://ripple.com/build/rippleapi/#getsettings), so I thought It is a bug.

Do you have any other implementation?

**Comment by JoelKatz** [comment]
Since this requires a change to the ledger format, it would have to be connected to an amendment. Otherwise, servers that do not have this code would reject as invalid AccountRoot entries that had memos.

Also, depending on what you want to use this for, there might have to be either a very strict limit on how big the memos field can be or a charge against the reserve based on the size of the memo field. The base reserve is calibrated against the ledger bloat that an account adds -- giving more storage for free could disrupt this balance.

You could also just use the Domain field for this. It's not intended for this purpose, but it has the semantics you want -- you can set it to any value and retrieve it. If a hash of this data is sufficient because you have an external system it can be used in, you can also use the WalletLocator field for this purpose. (It was added to support certain wallet implementations that were never implemented.)

**Comment by peersafe** [comment]
Thanks a lot. So i will close this pull request.

**Pull request closed without merging**
