### PR TITLE
LookupLedger correctly sets validated for ledgers requested by index.

### PR DESCRIPTION
**Pull request by rec**
https://ripplelabs.atlassian.net/browse/RIPD-698

Reviewers: @JoelKatz @nbougalis

### CODE REVIEW

**Comment by JoelKatz** [comment]
:-1: This sets validated even when the ledger's not validated. Consider someone who specifies a ledger by hash.

**Comment by nbougalis** [comment]
I'm not entirely convinced that this is doing what it claims to do.

**Comment by rec** [comment]
> Consider someone who specifies a ledger by hash.

The code path for that case hasn't changed!  If we are wrong now in that case, we are still wrong.

What you're saying is that the code that was there has always been completely wrong.  So how do we fix it?

**Comment by JoelKatz** [comment]
The code path for that case has changed. You changed it. This code decides whether to set the validated flag regardless of how the ledger was specified.

**Comment by rec** [comment]
> The code path for that case has changed. You changed it. 

I'm sorry, I guess I'm completely confused now.

This pull request _only_ changes the case where the user _did not_ pass in the hash.  If the user _did_ pass in the hash, then nothing has changed.  

Are you referring to some previous change?  I can't see any changes to this behavior in the history...?

**Comment by JoelKatz** [comment]
Oh, duh, you found and fixed the bug!
:+1:

**Comment by rec** [comment]
Probably replaced by https://github.com/ripple/rippled/pull/823

**Pull request closed without merging**
