### PR TITLE
Remove unused unl module code

### PR DESCRIPTION
**Pull request by vinniefalco**
UNLHorizon is test code anyway

### CODE REVIEW

**Comment by nbougalis** [comment]
:+1:

**Comment by vinniefalco** [comment]
I should probably remove the whole module, including the manager.

**Comment by scottschurr** [comment]
I just took a quick glance.  But assuming it builds in all circumstances it's hard to see what could go wrong.  I'll give it a novice's :+1:.

**Comment by ximinez** [comment]
:+1: Builds and passes tests in Windows debug builds. Reading through the removed code, it doesn't appear to do anything significant as long as `RIPPLE_HOOK_VALIDATORS` is left unset.

My one concern is the `shouldDrop` function, which can cause a peer connection to fail / drop if something takes more than a minute. However, from what I can tell, this is not a particularly significant problem, and there are other timeouts that can accomplish the same thing.

**Comment by vinniefalco** [comment]
@ximinez Whats the concern? All the code is removed

**Comment by ximinez** [comment]
@vinniefalco The concern is whether removing the code will cause us to lose valuable / necessary functionality. I am reasonable convinced that it won't, but I wanted to mention it in case I misunderstood.

**Comment by vinniefalco** [comment]
Oh.... well, that code was all experimental and should not have made it to production.

**Comment by ximinez** [comment]
Then it's a good thing it's getting removed. :smiley:

**Pull request closed without merging**
