### PR TITLE
Integrate NuDB

### PR DESCRIPTION
**Pull request by vinniefalco**
This brings NuDB up to the latest version

### CODE REVIEW

**Comment by HowardHinnant** [comment]
I'm duplicating the errors reported by travis and ci:
```
src/test/nodestore/import_test.cpp:358:28: error: unknown type name 'nodeobject_codec'
        using codec_type = nodeobject_codec;
                           ^
```
I can't find `nodeobject_codec` anywhere so I'm at a loss to suggest the correct fix.

**Comment by nbougalis** [comment]
`nodeobject_code` is under `ripple::NodeStore`

**Comment by vinniefalco** [comment]
`nodeobject_codec` is removed in this PR. The problem is that `import_test.cpp` has rocksdb stuff which isn't compiled on Windows.

**Comment by HowardHinnant** [comment]
Cherry-pick this to fix gcc/clang errors: https://github.com/HowardHinnant/rippled/commits/nudb

**Comment by vinniefalco** [comment]
I added Howard's commit

**Comment by HowardHinnant** [comment]
👍

**Comment by seelabs** [comment]
CMakeLists.txt needs to be updated. You can cherry pick this to get the needed changes: https://github.com/seelabs/rippled/commit/c361e30afa849cb2366c0530fca3da5c362becb5
:+1: after that.

**Comment by vinniefalco** [comment]
@seelabs Thank you, I have added the CMake changes

**Comment by nbougalis** [comment]
Merged as commits 79159ffd87bf86e92ab5af6fffd5cc93c205a630, bd93ecbd6bf0d1fa605c764f94751c3aed2f39d8 and 3b639afac2352e441f3dbf28b6a70b65cdf89552

**Pull request closed without merging**
