### PR TITLE
Replace beast::SharedPtr with std::shared_ptr

### PR DESCRIPTION
**Pull request by scottschurr**
Commit is from @JoeLoser.  It is being resubmitted so CI can run against it.

Problem:
Unneeded uses of `beast::SharedPtr` can be replaced with `std::shared_ptr` to remove some code maintenance. Also, as discussed in https://github.com/ripple/rippled/pull/2551, we'll get the `noexcept` behavior we want for free provided by our vendor implementation of `std::shared_ptr`.

Reviewers:
@seelabs @scottschurr

See https://github.com/ripple/rippled/issues/2556

### CODE REVIEW

**Comment by scottschurr** [comment]
:+1: Nice cleanup!  There are no bugs in code that is absent!

The only things I spotted were some truly minor considerations regarding placement of spaces.  This was made yet more confusing because you were working with old code that doesn't conform to what (I think) are the latest approaches.

- I'm pretty sure that we usually leave no space between the opening `<` of a template usage and the preceding alphanumeric.  So we would usually write:
```
    std::vector<std::shared_pt<Source>> m_sources;
```
not
```
    std::vector <std::shared_ptr <Source>> m_sources;
```

- At least at one point in the recent past there was a somewhat confusing rule for spaces before an opening paren `(`.  If there's nothing inside the parens, then there's no space.  If there's stuff inside the parens then there's one space.  So we would typically write:
```
New (std::string const& name, Strings const& strings);
```
not
```
New(std::string const& name, Strings const& strings);
```
But there are plenty of examples in the code base where this guidance is not followed.  It's also possible that I'm not up on the latest preferences.  At any rate, I don't think the the spacing tidiness is required for this pull request.

**Comment by JoeLoser** [comment]
Thanks for the quick feedback turnaround, Scott. I know things are busy with the recent holiday and upcoming Rapperswil meeting -- hope you have fun in Switzerland!

As you have noted, there is a mix of the old code-formatting style and the new one in various parts of the code.  So, I went ahead and fixed up the spacing issues you have pointed out. Feel free to cherry-pick it at [JoeLoser@rippled/310ea1007](https://github.com/JoeLoser/rippled/commit/310ea100736ee8c608e89f67356feb849a9f7b55)

**Comment by scottschurr** [comment]
:+1: Nice format tidying.  Thanks for taking the time.

**Comment by HowardHinnant** [comment]
Fwiw, I reviewed these changes and they look good to me. 👍

**Comment by seelabs** [comment]
If we do this, Source should no longer inherit from `beast::SharedObject` and we can remove `beast::SharedObject` as well. Here is a commit to cherry pick: https://github.com/seelabs/rippled/commit/d343a72f1112a798219b5305021a917151e28d8a

**Comment by scottschurr** [comment]
@seelabs Great spotting!  Thanks.

**Comment by JoeLoser** [comment]
@seelabs less lines of code, the better. Thanks!

**Comment by mellery451** [comment]
in f0cc7c4c8

**Pull request closed without merging**
