### PR TITLE
Apply clang-tidy modernize-use-override check

### PR DESCRIPTION
**Pull request by JoeLoser**
**Problem**:
Several functions were missing the `override` keyword.

**Solution**:
Mark every function that needs the `override` keyword as such.

**Questions**:

1. Do we wish to apply this to forked vendor code such as Beast?
2. Do we wish to turn on `-Wsuggest-override` or mark it as an error even?

**Reproduce**:
First, run CMake with exporting a compile commands database. This is as simple as adding `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` to your usual CMake invocation. Then, here is an example invocation of running `clang-tidy` with just this one check enabled:

```
~/bin/run-clang-tidy.py \                                                                                                                                                                         
-p _build  \
-clang-tidy-binary ~/bin/llvm6/bin/clang-tidy \
-clang-apply-replacements-binary ~/bin/llvm6/bin/clang-apply-replacements \
-checks="-*,modernize-use-override" \
-fix
```

Some notes about this:

1. `_build` is just the name of the CMake build directory I use. This just needs to be wherever you denote so that `clang-tidy` can find the `compile_commands.json` database.
2. Replace the paths of `run-clang-tidy.py`, `clang-tidy`, and `clang-apply-replacements` with your appropriate paths. For reference, my `~/bin/llvm6` is just a convenient symlink to my `llvm6` top directory. Things like `run-clang-tidy.py` which I use often I just symlink in place to `~/bin`.

**Future Work**

1. We can manually apply several other checks to the codebase in a sweeping fashion. I recommend doing it one check or a few at a time to make the history in the codebase very clear without coupling too much as these can change a good amount of code at once.  I am happy to pick ones I think may be good and apply them, or we can agree to some as a team and go from there.
2. I suspect Ripple could benefit greatly from applying clang tooling in an automatic fashion. It may make sense at a later point to create a `.clang-tidy` file and have it run as part of CI. This would help fortify good coding standards beyond others pointing these simple automatable things during code reviews.

@seelabs

### CODE REVIEW

**Comment by seelabs** [comment]
Rather than closing and re-opening your PRs, I'm going to leave them open until they are marked passed before I close/reopen. We'll miss out on jenkins, but we can deal with any jenkins issues at the very end.

**Comment by JoeLoser** [comment]
Sounds good, thanks! You can assume that anything that makes it to a PR from me will at a minimum build and pass all unit tests on Mac with a Clang 6 unity build.

**Comment by seelabs** [comment]
Good finds. I am in favor of turning on `suggest-override` for gcc. It's too bad that clang doesn't have the same warning (we do build with `inconsistent-missing-override` but as you've found that only flags warnings if the class has marked at least one member with `override` and has forgotten others.

**Comment by seelabs** [comment]
@JoeLoser Here's another patch you may want to cherry pick. This one turns on the `suggest-override` warning for gcc and handles the warning from `ripple.pb.h` by making the directory that file lives in a system directory: https://github.com/seelabs/rippled/commit/6db2e777ad509b98fca9593f245483b8b44b7410

**Comment by JoeLoser** [comment]
@seelabs good call on the protobuf file. All of your patches LGTM. I'll cherry pick them tonight. Thanks for the help! 

How do you and the rest of the seem feel about using other clang-tidy checks in general?

**Comment by seelabs** [comment]
@JoeLoser While I've heard about clang-tidy, I've never used it myself. I'd have to play around with it  before I have an informed opinion.

**Comment by mellery451** [comment]
@JoeLoser I've mostly experimented with the direct CMake integration (`CMAKE_CXX_CLANG_TIDY`) to see if it provided anything helpful. I had some trouble with globbing checks (e.g. `-checks=*`) when I initially tried it (probably a cmake bug) - and didn't get much past that.

One possibility is to add a "tidy build" option to our cmake that turns on clang-tidy for the build with a special subset of checks that we care about. I'm not sure what those should be exactly, but I bet we could come up with an initial list. If we do that, then the checks can be added to CI pretty easily.

**Comment by seelabs** [comment]
:+1: from me once the other patches are added.

**Comment by JoeLoser** [comment]
@mellery451 I see. The CMake integration certainly had some bugs at first with parsing multiple arguments so I suspect you got burned by that when using the default checks with `-fix`.

In any regard, I agree that a build configuration of running clang-tidy with a set of checks is a worthwhile thing to do. I'm quite busy this week since I'm travelling for work, but I'll create a GitHub issue later tonight to track this idea. On that issue, we can volley back and forth to form a decent initial list of checks we'd like to enable and go from there.

**Comment by seelabs** [comment]
Closed and reopened as https://github.com/ripple/rippled/pull/2533 so jenkins runs.

**Pull request closed without merging**
