### PR TITLE
Fix typo in LedgerMaster.cpp

### PR DESCRIPTION
**Pull request by MarkusTeufelberger**
I just randomly stumbled over this one, seems to be the only instance of this specific typo.

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
https://github.com/ripple/rippled/blob/develop/src/ripple/app/main/Main.cpp#L260 also looks suspicious but I'm not sure which word is actually missing ("Load the specified ledger and start from .").

**Comment by nbougalis** [comment]
Thanks for fixing this.

**Comment by JoelKatz** [comment]
Maybe it was supposed to be "and start from it"? Or maybe just "Load, and start from, the specified ledger"? Or "Load the specified ledger to start from"? It looks like whoever wrote that (me?) couldn't decide what wording to use and split the difference.

**Comment by MarkusTeufelberger** [comment]
I wondered for a while what the use case for such a command would be anyways, but I guess it is useful to recover from a fork in case your server _really_ got messed up (don't load the most recent - forked off - ledger, but load an earlier one that shares history with the majority ledger and rejoin the consensus, since then you'd switch over to the correct branch).

**Comment by JoelKatz** [comment]
@MarkusTeufelberger It's useful to test transactions in standalone mode against a particular live ledger or to replay the close of a past ledger.

**Pull request closed without merging**
