### PR TITLE
Proposed 0.80.1

### PR DESCRIPTION
**Pull request by bachase**

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
Please add #2269 and #2273... I'm waiting for a while on this already.

**Comment by mDuo13** [comment]
I second adding those two commits, since they only touch Python files and not the core code, and having Python3 compatibility in scons will make it much easier to build the release on some systems

**Comment by bachase** [comment]
@MarkusTeufelberger I added them. Thanks for your patience and contribution!

**Comment by MarkusTeufelberger** [comment]
Thanks! \*cough\* #2273 \*cough\*

**Comment by bachase** [comment]
Its squashed into 5a9c3c7 ;)

**Comment by MarkusTeufelberger** [comment]
Ah great, I just looked at the commit message! :D

**Pull request merged**
