### PR TITLE
Simplify journal

### PR DESCRIPTION
**Pull request by scottschurr**
Only the top-most commit needs reviewing.  The two lower commits are from other pull requests.

The Journal API is affected.  There are two uses for the Journal::Severity enum:

- It is used to declare a threshold which log messages must meet in order to be logged.

- It declares the current logging level which will be compared to the threshold.

I've renamed those uses that affect the threshold to `threshold()` rather than `severity()` to make the usage easier to distinguish.  The current logging level is still called level.

Additionally, Journal no longer carries a Severity member.  All handling of the `threshold()` is now delegated to the Journal::Sink.  I'm hoping this will help remove some blurring of responsibilities.  This change also helps with unit testing since a Sink is virtual and can be customized, but a Journal cannot be customized.

Sinks are no longer constructed with a default threshold of kWarning; their threshold must be passed in on construction.  This means that a Log will construct all of its Sinks with the Log's current `threshold()`.  That seems to help with some logging problems we've observed.

I intend to submit a follow-on pull request that will use array access syntax to access the Streams in a Journal.  That change will have the potential to make Journal instances much lighter weight.

Reviewers: @nbougalis @vinniefalco

### CODE REVIEW

**Comment by vinniefalco** [comment]
HELLO +1.35% !!!!

**Comment by scottschurr** [comment]
Addressed @vinniefalco's excellent comments and piled @nbougalis's "Simplify logging" commit on top.

CircleCI has failed twice in the same way, but it appears to be docker infrastructure that's failing?
```
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
```

**Comment by vinniefalco** [comment]
This needs a rebase and squash and I think we're good to go

**Comment by scottschurr** [comment]
Squashed and rebased to 0.31.0-b10.

**Comment by vinniefalco** [comment]
:+1:

**Comment by nbougalis** [comment]
:+1:

**Pull request closed without merging**
