### PR TITLE
0.28.0-b2

### PR DESCRIPTION
**Pull request by nbougalis**

### CODE REVIEW

**Comment by ximinez** [comment]
My changes look good. Waiting for build and tests before signing off.

**Comment by vinniefalco** [comment]
:+1:

**Comment by ximinez** [comment]
Test failures in Windows builds. http://ideone.com/Dc0HHj

**Comment by ximinez** [comment]
Info dump:
```
$ git bisect bad
1d449702bfe8c12e1c7eef4a58929768605b8f6b is the first bad commit
commit 1d449702bfe8c12e1c7eef4a58929768605b8f6b
Author: Vinnie Falco <vinnie.falco@gmail.com>
Date:   Wed Jan 21 16:51:19 2015 -0800

    Refactor Serializer and SerializerIterator interfaces:

    * Remove unused members
    * SerialIter holds only a pointer and offset now
    * Use free functions for some Serializer members
    * Use SerialIter in some places instead of Serializer

:040000 040000 754a8381a9892ae6660116dcd518a94cab277d69 2a646d588a3bfea1fe4f1e55e40ce8fae43911f9 M      Builds
:040000 040000 0ce1d6b186c38e3b7cafe7fc61bc098dd712950c 1ed8eb5c522443913b96148a46723c590c9a171e M      src

EdHennis@MOIST /C/Dev/rippled-merge ((1d44970...)|BISECTING)
$ git bisect log
# bad: [70a007f068ce3c98932a0ad530c23b5b012bca49] Set version to 0.28.0-b2
# good: [b5c7232d6f2b84a446c7df3ee321ed621d152777] Set version to 0.28.0-b1
git bisect start 'HEAD' 'upstream/develop'
# good: [dc111a8fc8b5b7acd53262c9cbb32b9865752c33] Initialize canDelete_ properly in the constructor.
git bisect good dc111a8fc8b5b7acd53262c9cbb32b9865752c33
# good: [69efcce8f5adb57c5ebd18b41c2e27eb69c90889] Support a "--noserver" command line option in tests: * Run npm/integration tests without launching rippled, using a   running instance of rippled (possibly in a debugger) instead. * Works for "npm test" and "mocha"
git bisect good 69efcce8f5adb57c5ebd18b41c2e27eb69c90889
# bad: [3d3ff49ac709697f041ea2bc5e92cc0af068421c] Remove buffer_view
git bisect bad 3d3ff49ac709697f041ea2bc5e92cc0af068421c
# bad: [1d449702bfe8c12e1c7eef4a58929768605b8f6b] Refactor Serializer and SerializerIterator interfaces:
git bisect bad 1d449702bfe8c12e1c7eef4a58929768605b8f6b
# first bad commit: [1d449702bfe8c12e1c7eef4a58929768605b8f6b] Refactor Serializer and SerializerIterator interfaces:
```

**Comment by josh-ripple** [comment]
I don't see any +1 for "Constrain valid inputs for memo fields (RIPD-712)".

**Comment by ximinez** [comment]
Builds now succeed, and all tests pass. Rippled starts, syncs with memory backend on Windows, and stops.

**Pull request merged**
