### PR TITLE
HTML Documentation Framework

### PR DESCRIPTION
**Pull request by vinniefalco**

### CODE REVIEW

**Comment by ximinez** [comment]
Another suggestion: CMake custom target to build the docs. Not included in the "all" target, so won't build automatically, and won't negatively affect anyone without the toolchain. If built under VS, creates a project that gives access to the files under `docs/` for editing within the IDE.

https://github.com/ximinez/rippled/commit/6069fc8b18fc2a765b1f448f060085fadbcf66ff

**Comment by ximinez** [comment]
@vinniefalco On Ubuntu 16.04, I'm getting an error running `b2`:
```
~/dev/rippled/docs (vf-doc=)$ $BOOST_ROOT/b2
warning: mismatched versions of Boost.Build engine and core
warning: Boost.Build engine (/home/eah/boost_1_61_0/b2) is 2015.07.00
warning: Boost.Build core (at /usr/share/boost-build/src) is 2014.03-svn
boost.jam: No such file or directory
../Jamroot:10: in modules.load
ERROR: rule "boost.use-project" unknown in module "Jamfile</home/eah/dev/rippled>".
/usr/share/boost-build/src/build/project.jam:325: in load-jamfile
/usr/share/boost-build/src/build/project.jam:64: in load
/usr/share/boost-build/src/build/project.jam:113: in load-parent
/usr/share/boost-build/src/build/project.jam:464: in initialize
/usr/share/boost-build/src/build/project.jam:306: in load-jamfile
/usr/share/boost-build/src/build/project.jam:64: in load
/usr/share/boost-build/src/build/project.jam:145: in project.find
/usr/share/boost-build/src/build-system.jam:535: in load
/usr/share/boost-build/src/kernel/modules.jam:289: in import
/usr/share/boost-build/src/kernel/bootstrap.jam:139: in boost-build
/usr/share/boost-build/boost-build.jam:8: in module scope
```
This occurs whether or not `b2` is in my `$PATH`

**Comment by vinniefalco** [comment]
Sounds like you have a misconfigured system

**Comment by ximinez** [comment]
I `apt remove`d all of the system boost packages, and it's working now. Fortunately, nothing else depended on them.

**Comment by ximinez** [comment]
I'm taking this PR over.

**Pull request closed without merging**
