### PR TITLE
ledger_request index must be positive.

### PR DESCRIPTION
**Pull request by ximinez**
Nearly trivial.

Reviewers: @miguelportilla @scottschurr.

### CODE REVIEW

**Comment by vinniefalco** [comment]
How the hell does a one line change cause 0.11% less coverage?

**Comment by ximinez** [comment]
That's a great question!

**Comment by ximinez** [comment]
Here's part of the reason why:

Develop: https://codecov.io/github/ripple/rippled/src/ripple/overlay/impl/OverlayImpl.cpp?ref=d7935192dd9db58463a6ac38a0906d0b9d78ecc8#l-105
This branch: https://codecov.io/github/ripple/rippled/src/ripple/overlay/impl/OverlayImpl.cpp?ref=a3d8f947e13eb1cb1be120f366bbc4a422f7eac1#l-105

For some reason, running the tests in develop, the overlay thread stays running long enough for the entire `on_timer` function to run all the way through _once_. (The second column from the left is a hit count.) However, on the branch for this PR, it looks the `Application` is getting stopped before that one instance of `on_timer` gets started (or maybe called at all based on the hit counts). And because of that one missed call, the implications cascade from there, causing about some significant chunk (or maybe all) of these 150 statements not to get tested.

What can be done about it? Probably nothing right now. If I rebase off of #1471, I could write a unit test that'll cover the `ledger_request` function. That PR gets all the way through this `on_timer` function 3 times (https://codecov.io/github/ximinez/rippled/src/ripple/overlay/impl/OverlayImpl.cpp?ref=c561361cad50cf86473e2b74eb1ff1c1522ec5b5#l-105), *plus* I'd be able to test the new lines, and at least some of the rest of the related function. 

Thoughts?

**Comment by ximinez** [comment]
Ok, I went ahead and rebased against #1471, so you can ignore those commits, and wrote a test. We'll see how the code coverage compares against that branch's 56.81%.

**Comment by ximinez** [comment]
57.02% - 56.81% = +0.21% increase.

**Comment by scottschurr** [comment]
I only looked at the last 2 commits.  Assuming I was looking at the right stuff, :+1:.  Nice tests.  *Great* to be able to test RPC commands with C++ unit tests!

**Comment by ximinez** [comment]
@scottschurr Yes, that is the right stuff to look at.

**Comment by miguelportilla** [comment]
I left a couple of comments that can optionally improve the test, but not holding this back. 
:+1:

**Comment by ximinez** [comment]
Rebased against 0.31.0-b3. Only relevant commits are included now.

**Comment by scottschurr** [comment]
:+1:
Still looks good to me.

**Comment by ximinez** [comment]
Rebased against 0.31.0-b4.

**Comment by ximinez** [comment]
@miguelportilla I added a few test cases to search for a hash.

I also included the commit from #1508 and rewrote the relevant test.

**Comment by ximinez** [comment]
Squashed!

**Comment by ximinez** [comment]
Rebased off of #1513 and squashed both change sets. Once CI passes, this will be ready to remerge into -b5 #1516.

**Comment by nbougalis** [comment]
Merged as 7c82adcc8496c0782f5d250504f20f0b294ea72b, dd5d938aa3b21d257114efa6a171f8bed93598de, f9f2b8124dacdd729916755e89938cb784cbe2b3, 040d7ebb46fb158c8d6488270c14d7919442e5ef, 9786e432f8a812c5540633c196b2d5c2206fe44d and 4d72fc225a49a876bce82761a60bc088c67b3752.

**Pull request closed without merging**
