### PR TITLE
Proposed 0.28.0-b1

### PR DESCRIPTION
**Pull request by nbougalis**
Reviews: @JoelKatz, @miguelportilla, @vinniefalco, @rec

### CODE REVIEW

**Comment by JoelKatz** [comment]
:+1:

**Comment by vinniefalco** [comment]
Is there a ticket number for "Enable Amendments from config file or static data" ?

**Comment by vinniefalco** [comment]
Consider
"Fix order of construction of Application members"
instead of
"Do not take references to uninitialized members"
Rationale: Why admit that we passed references to uninitialized objects?

**Comment by nbougalis** [comment]
Re: rewording: done. Will show up in next push.

**Comment by seelabs** [comment]
@vinnie: ripd-746 https://ripplelabs.atlassian.net/browse/RIPD-746

**Comment by nbougalis** [comment]
I will update the commit message to include the ticket number. Thanks @seelabs.

**Comment by vinniefalco** [comment]
"Force microsecond granularity for sqlite lock backoff algorithm" sounds kind of heavy handed. Like we're pushing something to do something it doesn't normally do.

**Comment by HowardHinnant** [comment]
:-1:  I'm getting a compile error on OS X:
src/ripple/app/misc/AmendmentTableImpl.cpp:693:21: error: use of undeclared identifier 'getApp'
    auto& walletDB (getApp ().getWalletDB ());
                    ^
src/ripple/app/misc/AmendmentTableImpl.cpp:712:21: error: use of undeclared identifier 'getApp'
    auto& walletDB (getApp ().getWalletDB ());
                    ^
src/ripple/app/misc/AmendmentTableImpl.cpp:734:12: error: use of undeclared identifier 'getApp'
    return getApp ().getValidations ().getValidations (hash);
           ^
3 errors generated.

**Comment by HowardHinnant** [comment]
I believe the cause is the non-testing of the non-unity build.  I will be pushing a fix as soon as I work through the missing #includes.  There appear to be several.  Hoping to get it done before scrum...

**Comment by nbougalis** [comment]
Thanks Howard!

**Comment by vinniefalco** [comment]
@HowardHinnant The cause is a missing include

**Pull request merged**
