### PR TITLE
Better continuations.

### PR DESCRIPTION
**Pull request by rec**
Note that continuations are still disabled for websockets, due to an issue I haven't been able to resolve...

Reviewers: @HowardHinnant @vinniefalco

### CODE REVIEW

**Comment by rec** [comment]
Inlined all those members.  Not moving things to core, pending a later change.  Contemplating the `JobQueue` change...

**Comment by vinniefalco** [comment]
Unfortunately still does not work in VS2013... we can try again in VS2015.

**Comment by HowardHinnant** [comment]
@vinniefalco I'm not positive what the above comment is referring to.  Could you expound? Thanks.

**Comment by HowardHinnant** [comment]
This gets the following build failure on libc++.  This isn't a libc++ bug.  We will likely get similar errors on upgrade to libstdc++-5.x and VS-2015 (the error has become mandated by the C++ standard).
````
src/ripple/app/ledger/impl/LedgerConsensusImp.cpp:637:17: error: no viable conversion from '__bind<std::__1::shared_ptr<ripple::Ledger>
      (ripple::InboundLedgers::*)(const ripple::base_uint<256, void> &, unsigned int, ripple::InboundLedger::fcReason),
      ripple::InboundLedgers *, ripple::base_uint<256, void> &, int, ripple::InboundLedger::fcReason>' to 'const std::function<void (Job &)>'
                std::bind (
                ^~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1448:5: note: candidate
      constructor not viable: no known conversion from '__bind<std::__1::shared_ptr<ripple::Ledger> (ripple::InboundLedgers::*)(const
      ripple::base_uint<256, void> &, unsigned int, ripple::InboundLedger::fcReason), ripple::InboundLedgers *, ripple::base_uint<256, void>
      &, int, ripple::InboundLedger::fcReason>' to 'nullptr_t' for 1st argument
    function(nullptr_t) _NOEXCEPT : __f_(0) {}
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1449:5: note: candidate
      constructor not viable: no known conversion from '__bind<std::__1::shared_ptr<ripple::Ledger> (ripple::InboundLedgers::*)(const
      ripple::base_uint<256, void> &, unsigned int, ripple::InboundLedger::fcReason), ripple::InboundLedgers *, ripple::base_uint<256, void>
      &, int, ripple::InboundLedger::fcReason>' to 'const std::__1::function<void (ripple::Job &)> &' for 1st argument
    function(const function&);
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1450:5: note: candidate
      constructor not viable: no known conversion from '__bind<std::__1::shared_ptr<ripple::Ledger> (ripple::InboundLedgers::*)(const
      ripple::base_uint<256, void> &, unsigned int, ripple::InboundLedger::fcReason), ripple::InboundLedgers *, ripple::base_uint<256, void>
      &, int, ripple::InboundLedger::fcReason>' to 'std::__1::function<void (ripple::Job &)> &&' for 1st argument
    function(function&&) _NOEXCEPT;
    ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/functional:1454:41: note: candidate
      template ignored: disabled by 'enable_if' [with _Fp = std::__1::__bind<std::__1::shared_ptr<ripple::Ledger>
      (ripple::InboundLedgers::*)(const ripple::base_uint<256, void> &, unsigned int, ripple::InboundLedger::fcReason),
      ripple::InboundLedgers *, ripple::base_uint<256, void> &, int, ripple::InboundLedger::fcReason>]
                                        __callable<_Fp>::value &&
                                        ^
src/ripple/core/JobQueue.h:42:60: note: passing argument to parameter here
                         std::function <void (Job&)> const&) = 0;
                                                           ^
1 error generated.
````

**Comment by HowardHinnant** [comment]
Working on a fix for the above error...

**Comment by rec** [comment]
dammit!  :-)  thanks for catching this.  why isn't continuous integration catching it?

**Comment by rec** [comment]
(Or I could just drop the last commit - but it seemed so short and useful...)

**Comment by HowardHinnant** [comment]
I know the nature of the error, but not the exact cause.  The error is that the indicated `bind` does not represent a functor with the `std::function`'s signature:  `void (Job&)`.  I am not yet sure what change caused this mismatch, nor the best way to fix it.

**Comment by rec** [comment]
I'm going to revert the last unrelated change.

**Comment by rec** [comment]
Dumped it.  It only took me a few seconds' work, I'll attack it again some other time.

**Comment by HowardHinnant** [comment]
Ah!  Best guess:  `boost::function` is more permissive than `std::function` with regard to matching signatures between the `function` and the functor.

**Comment by HowardHinnant** [comment]
It makes me wonder if we have a latent bug ...

**Comment by vinniefalco** [comment]
@HowardHinnant VS doesn't swallow return types in `std::function`

**Comment by HowardHinnant** [comment]
My best guess is that VS also demands compatible signatures.  This is a rare case where VS-2013 is more standards compliant than gcc-4.8.2.

**Comment by HowardHinnant** [comment]
There's an easy way to change the bind to return void:  `bind<void>(...`.  But that doesn't fix the problem on libc++ (and I'm guessing not on VS either).

**Comment by rec** [comment]
I have a plan to fix this up.  :-D  But not right this second.

**Comment by HowardHinnant** [comment]
It isn't going to be easy to fix if you don't have an environment to reproduce it.

**Comment by rec** [comment]
If I replace all the `std::bind` with lambdas it'll work automatically!

**Comment by HowardHinnant** [comment]
PS:  I'm hanging on to this for just a bit longer because I think Tom has accidentally turned a (potential) run time error into a compile time error.  And I want to understand it a little better before I let it go back to a run time issue.

I don't think a mechanical lambda substitution will change the error.  We need to either change the signature of the `std::function` in `JobQueue::addJob`, or we need to change the signature of the functor (be it a bind or a lambda) being added to the queue in `LedgerConsensusImp::handleLCL`.  And silently accepting mismatching signatures is just a little bit scary...

**Comment by rec** [comment]
All right, since I have it up, let's try again and see if the first quick lambda fix just does it.

**Comment by HowardHinnant** [comment]
I've only glanced at Tom's fix, but I think it will work.  I'll be testing it as soon as I complete testing my own fix (which looks like it is working).  If Tom's fix works, I'll prefer his to mine, as it is simpler.

**Comment by rec** [comment]
I'm actually getting rid of a bunch of binds, and some of these are exposing interesting behavior and simplifications...

**Comment by HowardHinnant** [comment]
It's a pretty cool fix Tom.  You've taught me a new trick today:  You can use lambdas to *add* parameters to a function.

**Comment by rec** [comment]
I'm actually changing all the jobs to lambdas - revealing some interesting details (like copies) I never noticed.

**Comment by HowardHinnant** [comment]
Testing Tom's latest now.  For your amusement, here is what I had done: https://github.com/HowardHinnant/rippled/commit/18e88adca455b5a9008a740872f32a166a567973 (which did pass tests).

**Comment by HowardHinnant** [comment]
Tom's latest, modified to with `using JobFunction = std::function <void (Job&)>;`  passes all tests for me.  With that change I'll give it thumbs up.

**Comment by vinniefalco** [comment]
Builds in VS2013
:+1:

**Comment by rec** [comment]
Now, what do you think about this knock-on change?

https://github.com/rec/rippled/commit/e81c54466c635273a137dbed570e8cf6ee707f35

**Comment by HowardHinnant** [comment]
I think this is a good direction, but I would prefer to see it in another P/R to make a future use of git bisect more effective.

Can you search your current branch for `boost::function` and stomp on anything you might find?

**Comment by rec** [comment]
> I think this is a good direction, but I would prefer to see it in another P/R to make a future use of git bisect more effective.

 `git bisect` goes by commit so as long as I keep the commits unsquashed, it won't be an issue.  I can definitely pull it out into its own change if you like.

**Comment by HowardHinnant** [comment]
I'll make a deal with you ... Do this first:
> Can you search your current branch for boost::function and stomp on anything you might find?
Then I'll review the addition.

**Comment by rec** [comment]
I got rid of the last one right there....

**Comment by HowardHinnant** [comment]
Thanks, reviewing...

**Comment by HowardHinnant** [comment]
Oh, this new stuff is on another branch...

**Comment by rec** [comment]
Sure, but I could pull that over - in fact, let me do that now you're interested.  :-D

**Comment by HowardHinnant** [comment]
While I don't want this whole stack squashed, there definitely needs to be _some_ squashing and the current commit messages don't have the appropriate [FOLD] markers.

**Comment by rec** [comment]
> It used to be possible to tell when functions are dispatched from the JobQueue but with this change that is no longer possible.

I'm not sure what you mean?  Can you give a specific example?

**Comment by rec** [comment]
> While I don't want this whole stack squashed, there definitely needs to be some squashing and the current commit messages don't have the appropriate [FOLD] markers.

`fixup` >> [FOLD] - because fixup is part of git.

When you commit, you use this form:  `git commit --fixup <ID-of-commit-to-fold-into`.  Then `git rebase -i --autosquash` automatically puts the changes beside each other and marks them as fold...!

**Comment by HowardHinnant** [comment]
Ah!  Learn a little more git every day, thanks!
:+1:

**Comment by vinniefalco** [comment]
:+1:

**Comment by nbougalis** [comment]
Marking as passed with two thumbs up from Vinnie and Howard.

**Pull request closed without merging**
