### PR TITLE
Updates to ledger publication engine

### PR DESCRIPTION
**Pull request by JoelKatz**
Clean up the publication engine, add inline comments, add information to README.md file, make two tiny functional changes.

Reviewers: @vinniefalco, @nbougalis

### CODE REVIEW

**Comment by rec** [comment]
Rebooted Travis for the new year.  Try a rebase?

**Comment by rec** [comment]
Still failing - always the same timeout...!

**Comment by vinniefalco** [comment]
The damn ticket test again?

**Comment by JoelKatz** [comment]
I wonder if something breaks in standalone mode.

**Comment by rec** [comment]
This doesn't even build!  :-)

Closing it without prejudice, you can always reopen it.

**Pull request closed without merging**
