### PR TITLE
Refactoring Medley

### PR DESCRIPTION
**Pull request by vinniefalco**
Many functions and classes that used a Ledger now use a BasicView. Calls to cachedRead are changed to call member read on the view, note that this bypasses the SLECache optimization. To restore the optimization, the BasicView passed at the top of call stacks should be wrapped with a caching view, coming in future commits.

### CODE REVIEW

**Comment by vinniefalco** [comment]
Reviewers: @HowardHinnant @ximinez

**Comment by vinniefalco** [comment]
Rebased

**Comment by ximinez** [comment]
> the BasicView passed at the top of call stacks should be wrapped with a caching view, coming in future commits.

Should this commit wait to be merged until the caching view changes are implemented?

**Comment by vinniefalco** [comment]
@ximinez Nope, we should just plunge forward and fix it later

**Comment by HowardHinnant** [comment]
:+1:

**Comment by ximinez** [comment]
:+1: 

And now I can make my joke: "Refactoring Medley? Where is `Medley` defined?"

**Comment by sublimator** [comment]
Oh dad!

**Pull request closed without merging**
