### PR TITLE
Remove websocketpp support (RIPD-1293)

### PR DESCRIPTION
**Pull request by mellery451**
Remove legacy websocketpp code. Make `ws` and `wss` synonyms for `ws2` and `wss2`.

### CODE REVIEW

**Comment by nbougalis** [comment]
Re: @bachase's commit about certificates: I'm not sold. If this script is used only for our CI then we should update the commit message to reflect that and go about something else. But if this script is used by users, then we absolutely should verify the certificate instead of blindly trusting it.

**Comment by bachase** [comment]
@nbougalis definitely agree.  #1909 fixes it without ignoring certificate issues.

**Comment by vinniefalco** [comment]
This would have been a bit more friendly if the commit to remove the websocketpp sources was separate, and followed the commit to remove the support from within rippled. But the changes look good!

**Comment by mellery451** [comment]
@vinniefalco that's a good point - let me see if I can break this up into two commits.

**Comment by mellery451** [comment]
I'm seeing some npm test failures with these changes on macOS, so this will not be ready until I can resolve that.

**Comment by mellery451** [comment]
my latest change to the uniport test resolves the issues I was seeing with npm tests on macOS.

**Comment by vinniefalco** [comment]
:+1:

**Comment by nbougalis** [comment]
:+1:

**Comment by vinniefalco** [comment]
Why are there 100 fewer covered lines?

**Comment by mellery451** [comment]
I'm only speculating...but perhaps there were lines being hit in files that have been removed? It looks like Hits + Misses == Total Lines Deleted (diff). I can try to dig into these results more if needed.

**Comment by vinniefalco** [comment]
Don't go crazy over it, just wondering why

**Comment by nbougalis** [comment]
Merged as 3d0314c6214ad916060468bbc6f9714817edbcb1

**Pull request closed without merging**
