### PR TITLE
Changes to enable mingw compilation (don't pull yet)

### PR DESCRIPTION
**Pull request by MarkusTeufelberger**
See https://github.com/ripple/rippled/issues/1299 for a progress report.

This PR is to make sure I don't mess up stuff early on and to get some test runs going.

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
Apparently the asserts/tests fail when using the beast/ByteOrder methods. They are supposed to be used like that though, right? Alternatively I'd just use https://gist.github.com/panzi/6856583 instead for the relevant functions...

**Comment by vinniefalco** [comment]
What's the status on this? Its bit-rotting.. :-(

**Comment by MarkusTeufelberger** [comment]
I know... :-(
How do I actually solve the beast ByteOrder stuff? This seems to be crashing the unit tests and I very likely just added a & or * too much or too little somewhere...
The other changes (checking for _WIN32, writing "windows.h" in lower case letters and maybe even replacing std::ifstream/ofstream with the boost methods) should be less controversial and could be cherry-picked.

I don't want to patch the SConstruct file just yet, it doesn't really make sense to have a broken build in there.

Snappy at least can be built for mingw (I found some packages), so it is only a matter of following the instructions elsewhere and writing them in the SConstruct.
I doubt however that the boost issues with coroutine and context are going to be resolved soon (they are written in parts for an MS exclusive assembler). This means that is not feasible to compile rippled with mingw at the moment, since rippled depends quite a bit on these modules and a rewrite just because it would be nice to be able to cross-compile would be overkill too (after all, the VS2015 build works with their cost-free version).

I'll leave this open for a bit (maybe I'll manage to fix the ByteOrder stuff), but in general while the changes are nice to have for code quality (\src\ripple\basics\ByteOrder.h can be removed, ifdefs are more correct etc.) I'm afraid I won't manage to compile rippled with mingw any time soon.

**Comment by nbougalis** [comment]
@MarkusTeufelberger Can this be closed for now?

**Comment by MarkusTeufelberger** [comment]
sure

**Pull request closed without merging**
