### PR TITLE
Simplify calculation of transfer fee

### PR DESCRIPTION
**Pull request by nbougalis**
This is a simplification to the way we handle the transfer fee: it eliminates a couple of function calls, and avoids subtracting an amount only to then readd it and expecting to get back the original minuend.

We may want to just reject this, pending Scott D's refactor - I leave that up to you.

Reviews: @JoelKatz, @seelabs

### CODE REVIEW

**Comment by seelabs** [comment]
@nbougalis Apart from simplifying the code, what you've done in this PR is replace the calculation: `amt + (transferRate*amt - amt) with `transferRate*amt`. One way these two calculations will differ is when mantissas of `transferRate*amt` and `amt` differ by ten or less. In that case, the old calculation will charge a fee of zero, and the new calculation will charge a small fee.

This difference could cause some transactions to now fail that would have succeeded with the old calculation.

My thoughts: Your PR improves the code, and improves the accuracy of the fee calculation. But it may also introduces a change to what transactions will succeed (though that may be just a theoretical concern). I'm very close to a PR for the new payment code. With that so close I don't think we should make this change. What do you think?

**Comment by nbougalis** [comment]
@seelabs: yep, I figured this could trigger miniscule differences which is why I tagged you, although I haven't seen one in over 40 hours of runtime.

The new payment code is obviously going to clean this and more up, and if you and David want to drop this PR in favor of the new code, I'm fine with that.

**Comment by JoelKatz** [comment]
I like the simplification, but we can also hold off. I'm fine either way.
:+1:

**Comment by seelabs** [comment]
I incorporated these changes into the main flow PR, so I'm closing this one.

**Pull request closed without merging**
