### PR TITLE
Update ripple.proto

### PR DESCRIPTION
**Pull request by donovanhide**
## High Level Overview of Change

Remove vestigial comments from not implemented Proof Of Work scheme for peer connections.

### Type of Change
- [X] Documentation Updates

### CODE REVIEW

**Comment by donovanhide** [comment]
@nbougalis One for you maybe.

**Review by nbougalis — APPROVED** [review]
This looks good.

**Comment by donovanhide** [comment]
Had  a quick look, but my knowledge of CMake is zero and there's an awful lot of it in Protobuf.cmake! Not sure if it just as trivial as changing the filename in the protogen input parameter as can't see where the output file name is decided.

**Comment by ximinez** [comment]
> Had a quick look, but my knowledge of CMake is zero and there's an awful lot of it in Protobuf.cmake! Not sure if it just as trivial as changing the filename in the protogen input parameter as can't see where the output file name is decided.

I think it's really just that simple. Rename the file, update the parameter to the new filename....

**Comment by donovanhide** [comment]
Done :-)

**Comment by donovanhide** [comment]
Not quite so simple in the end...

```
Searching 35953 files for "ripple.pb.h"

/Users/donovanhide/rippled/src/ripple/overlay/Message.h:
   40  // VFALCO NOTE If we forward declare Message and write out shared_ptr
   41  //             instead of using the in-class type alias, we can remove the
   42: //             entire ripple.pb.h from the main headers.
   43  //
   44  

/Users/donovanhide/rippled/src/ripple/overlay/Slot.h:
   29  #include <ripple/overlay/Squelch.h>
   30  #include <ripple/protocol/PublicKey.h>
   31: #include <ripple.pb.h>
   32  
   33  #include <algorithm>

/Users/donovanhide/rippled/src/ripple/overlay/impl/ProtocolMessage.h:
   33  #include <memory>
   34  #include <optional>
   35: #include <ripple.pb.h>
   36  #include <type_traits>
   37  #include <vector>

/Users/donovanhide/rippled/src/ripple/protocol/messages.h:
   32  #endif
   33  
   34: #include "ripple.pb.h"
   35  
   36  #endif

/Users/donovanhide/rippled/src/test/overlay/compression_test.cpp:
   40  #include <boost/endian/conversion.hpp>
   41  #include <algorithm>
   42: #include <ripple.pb.h>
   43  #include <test/jtx/Account.h>
   44  #include <test/jtx/Env.h>

/Users/donovanhide/rippled/src/test/overlay/reduce_relay_test.cpp:
   24  #include <ripple/overlay/impl/Handshake.h>
   25  #include <ripple/protocol/SecretKey.h>
   26: #include <ripple.pb.h>
   27  #include <test/jtx/Env.h>
   28  

6 matches across 6 files
```

**Pull request closed without merging**
