### PR TITLE
Remove checking minimum version of Boost and OpenSSL at runtime

### PR DESCRIPTION
**Pull request by JoeLoser**
**Summary:**
As I was in the process of correctly specifying the correct Boost version minimum from 1.57 to 1.67 in `CheckLibraryVersions.cpp`, @mellery451 nicely pointed out that having these runtime checks at all doesn't make much sense since we check the minimum Boost and OpenSSL versions at CMake configure time. Having the check at build time is much better than runtime.

This PR is split into two commits as such:

1. Specify correct Boost minimum version (1.67 instead of 1.57)

    Since we require a min Boost version of 1.67 as of recently (for Beast), we also remove the conditional 
    checks that existed for us to know whether `Boost.Process` is available or not. We can always 
    assume it is available now.
 
2. Remove `CheckLibraryVersions` entirely and its associated unit tests.

Requested reviewers:
@wilsonianb @ximinez

### CODE REVIEW

**Comment by JoeLoser** [comment]
@mellery451 any idea why Travis build failed with error "E: Unable to locate package gcc-5"? Is it possible to retry the Travis job?

**Comment by mellery451** [comment]
I'm guessing some transient condition..I restarted it.

**Comment by miguelportilla** [comment]
LGTM 👍

**Comment by JoeLoser** [comment]
@mellery451 great point.  I went ahead and removed the file and its unit tests in 176897fbe09adffec3a688ed02de856383187ed6.

I'm happy to reword the commits, squash, or such.  I intentionally didn't mark the second one as "FOLD" as they are slightly separate changes (due to removing Boost Process checks), but it's not a big change, so it can probably all be squashed into one. Better to keep them decoupled until someone tells me otherwise, though.

**Comment by mellery451** [comment]
in 06d0ff6e5

**Pull request closed without merging**
