### PR TITLE
Proposed changes to code style and experimental .clang-format

### PR DESCRIPTION
**Pull request by seelabs**

### CODE REVIEW

**Comment by bachase** [comment]
👍 😍 
Thanks for putting this together.  I'm happy with the current rules.

**Comment by seelabs** [comment]
I'm adding @nbougalis as a reviewer. Code style is really his call (of course everyone else is always welcome to comment).

**Comment by mellery451** [comment]
FWIW, I've tested this config with the vim formatter and I like the results

**Comment by bachase** [comment]
https://github.com/llvm-mirror/clang/blob/master/tools/clang-format/git-clang-format might be helpful

**Comment by scottschurr** [comment]
I'm not convinced that requiring a space between a unary `!` and the thing it's operating on is always the best for reading clarity.  To be fair, it often is...

**Comment by seelabs** [comment]
@scottschurr I also prefer no space after unary `!`. We have lots of code that already does this (in fact the `.clang_format` rules do this - I couldn't figure out how to make it add a space). I'll add a commit that removes the rule from our official code style.

Of course, it's up to @nbougalis to set the official code style.

**Comment by nbougalis** [comment]
I'm fine with removing the mandatory "space before `!`" rule.

**Comment by JoeLoser** [comment]
Glad to see this land soon. 👍

**Comment by nbougalis** [comment]
Included in #2629 as aa4e3a98f74c08f870f5136eecc4fa89d6d09186.

**Pull request closed without merging**
