### PR TITLE
Small cleanups to nudb comments.

### PR DESCRIPTION
**Pull request by rec**
Tiny tweaks to the comments.

Reviewer: @vinniefalco

### CODE REVIEW

**Comment by vinniefalco** [comment]
Very nice thanks

**Comment by rec** [comment]
Are we closing this? @vinniefalco

**Comment by rec** [comment]
I'm going to close this, since you mentioned that you were using these comments elsewhere.  I'm going to keep the branch for a bit, however, so let me know...

**Comment by vinniefalco** [comment]
I'd like to see this cleaned up and merged. There's some mistakes in the generated .md (for example, some backquoted strings in tables)

**Comment by rec** [comment]
Let me fix the backquotes in the tables!  Interestingly, my local viewer seems to show those as code, but that's wrong.

**Comment by vinniefalco** [comment]
:+1: Nice, thanks

**Comment by rec** [comment]
Done. There were rebase conflicts, you might or might not want to check it again to make sure I got those right.

**Comment by rec** [comment]
I'm going to mark this as approved, you can change it back if you like!  :-)

**Pull request closed without merging**
