### PR TITLE
Fail if vcxproj generates new things

### PR DESCRIPTION
**Pull request by tdfischer**

### CODE REVIEW

**Comment by nbougalis** [comment]
:+1: on this, unit test failure and all.  Thanks @tdfischer!

I'd suggest you stack a commit on top of this that fixes the vcxproj file and push so that we make sure it builds and passes, and then we can squash the commits together and merge.

**Comment by tdfischer** [comment]
@nbougalis I'm not actually sure how one "fixes" the vcxproj file. I've been out of rippled for too long :(

**Comment by nbougalis** [comment]
`scons vcxproj` should do the work for you - the just `commit -am` etc, etc.

**Comment by vinniefalco** [comment]
Merged to https://github.com/ripple/rippled/pulls

**Pull request closed without merging**
