### PR TITLE
Use soci in some places.

### PR DESCRIPTION
**Pull request by seelabs**
Validator, peerfinder, SHAMapStore, RpcDB, TxnDB, LedgerDB, WalletDB use soci backend.

@ximinez @nbougalis

### CODE REVIEW

**Comment by vinniefalco** [comment]
Travis fails SociDB unit test `ripple.app.SociDB select`
https://travis-ci.org/ripple/rippled/jobs/52917900#L695

**Comment by ximinez** [comment]
Confirmed. The tests pass in Windows, so the problem must be unique to
Linux.

On Tue, Mar 3, 2015 at 12:13 PM, Vinnie Falco <notifications@github.com>
wrote:

> Travis fails SociDB unit test ripple.app.SociDB select
> https://travis-ci.org/ripple/rippled/jobs/52917900#L695
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ripple/rippled/pull/909#issuecomment-76988981>.
>



-- 
*Edward Hennis | *Senior Software Engineer | *Ripple Labs Inc.*
ed@ripple.com | www.ripple.com | *www.ripplelabs.com
<http://www.ripplelabs.com/>*
T. 352.327.8769

**Comment by vinniefalco** [comment]
Might have to do with the directory path and permissions or something

**Comment by seelabs** [comment]
The problem is linux only - works on windows on mac. The problem is retrieving std::int64 values from a soci::row on linux.

**Comment by ximinez** [comment]
Tests all now pass on all builds in Windows and Linux.

**Comment by seelabs** [comment]
I just pushed changes that address the PR comments. Most are trivial and do not need to be re-reviewed. The exception to that is the WALCheckpointer in SociDB.h, that needs to be reviewed. It mirrors the code in SqliteDatabase. Since I believe this code is going away I didn't think it was worthwhile to refactor the SqliteDatabase to use this implementation.

**Comment by ximinez** [comment]
I think that covers everything for me.

:+1:

**Comment by rec** [comment]
Marked as rebase, wanna approve this?

**Comment by seelabs** [comment]
@rec It's only had one review, so definitely don't approve yet.

**Comment by nbougalis** [comment]
:+1: on this from me - all of my concerns where already brought up by Ed.

**Comment by vinniefalco** [comment]
Does rippled stop correctly with these WAL changes?

**Comment by ximinez** [comment]
@vinniefalco I did several start/stop cycles during the course of my review and live testing. It worked correctly every time.

**Comment by rec** [comment]
All right!  We did the push, let's resolve this and get it in...

One... more... rebase.... :-)

**Comment by seelabs** [comment]
Rebased.

**Comment by nbougalis** [comment]
Merged as c7cfd23, d0ef2f7, 9b837a2, d37802a and 97623d2.

**Pull request closed without merging**
