### PR TITLE
Update boost max to 1.77

### PR DESCRIPTION
**Pull request by legleux**
The findBoost module emits warnings with boost below this level.
This updates the max version the warnings will be produced for.
I have usually been using 1.75 with no issues.

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### CODE REVIEW

**Review by scottschurr — APPROVED** [review]
:+1: LGTM

**Comment by seelabs** [comment]
@legleux Not a big deal, but this PR doesn't need the whole team to review it. Typically we have two reviewers per PR (and of course anyone is always welcome to comment in a PR). I'd suggest removing all but two reviewers.

**Review by seelabs — APPROVED** [review]
:+1: LGTM

**Review by PaulMark88 — APPROVED** [review]

**Review by manojsdoshi — APPROVED** [review]
LGTM

**Review by intelliot — APPROVED** [review]

**Comment by manojsdoshi** [comment]
@legleux this is already merged so closing it out.

**Pull request closed without merging**
