### PR TITLE
VS2015!

### PR DESCRIPTION
**Pull request by nbougalis**
With Visual Studio 2015 officially released, this PR removes the `noreturn` emulation and the now obsolete `beast::static_initializer` in favor of new magic statics, and makes use of the `[[noreturn]]` attribute.

This **does not** include a VS2015 project file, and, if merged, would mean that RippleD can no longer be compiled under VS2013.

### CODE REVIEW

**Comment by rec** [comment]
:+1:

**Comment by rec** [comment]
Reviewers: @vinniefalco @rec @HowardHinnant (for C++ comments)

**Comment by scottschurr** [comment]
@sublimator It might be smart to get AppVeyor switched over to VS 2015 before this pull request gets merged.

**Comment by nbougalis** [comment]
@rec: yes - my editor strips trailing whitespace and this happened without me realizing. I don't think it's a big deal.

**Comment by vinniefalco** [comment]
Our project does not build in VS2015 yet. This pull request is premature.

**Pull request closed without merging**
