### PR TITLE
Update RippleD.vcxproj*

### PR DESCRIPTION
**Pull request by josh-ripple**

### CODE REVIEW

**Comment by nbougalis** [comment]
obviously correct if generated by `scons vcxproj`: :+1:

**Comment by rec** [comment]
The * does jump out at you in the list of commits.  Could I convince you to change the commit to "Update VS project files."?

**Comment by nbougalis** [comment]
Yes, please edit the title and push an update.

**Comment by josh-ripple** [comment]
@rec: Rebase onto what?  It's already one commit on the latest develop (0.28.0-b16).

**Comment by rec** [comment]
Sorry, I was abusing the "Rebase" flag.  What I mean was:

"The code is correct, just change the commit (text)."

Another way of seeing this was that I wanted to mark it approved, but I didn't want it eligible for the pull robot until the commit name was changed - thus Passed+Rebase.

**Comment by josh-ripple** [comment]
Ah.  I've done the same, but I was confused because the Rebase label was added after the new commit.

**Comment by nbougalis** [comment]
Merged as 0083c326295c969a38be836907a48901fb481490

**Pull request closed without merging**
