### PR TITLE
Make Coro a nested type of JobQueue

### PR DESCRIPTION
**Pull request by miguelportilla**
Documentation preview: [https://miguelportilla.github.io/](https://miguelportilla.github.io/)

### CODE REVIEW

**Comment by vinniefalco** [comment]
"Make Coro a nested type of JobQueue"?

**Comment by seelabs** [comment]
:+1: Reviewed the renames and confirmed `scons --assert gcc.release.nounity` runs without error (along with the other usual build targets & tests).

**Comment by vinniefalco** [comment]
Documentation preview?

**Comment by nbougalis** [comment]
Merged as 4b261b12a484f11e47afa34f77e12e9226e7b54c

**Pull request closed without merging**
