### PR TITLE
Unroll some unity files in the nounity build

### PR DESCRIPTION
**Pull request by mellery451**
This PR makes the nounity (classic) build behave slightly more correctly by unrolling a few more unity sources. I expect the nounity builds to fail on this branch without the changes in https://github.com/ripple/rippled/pull/2368, so *this* change should only be merged along with or after PR2368 (which is already passed and low risk).

### CODE REVIEW

**Comment by scottschurr** [comment]
Changes look good to me. Everything builds well for me on mac OS.  I'll give a thumbs up after the debug nounity failures on Jenkins are figured out.  That's interesting because debug.nounity worked just fine for me on mac OS -- both cmake and scons.

You also did us the favor of identifying a bit of dead code.  If you'd like to remove that dead code in this pull request you can cherry-pick this commit: https://github.com/scottschurr/rippled/commit/f22f907e80ad3c525f2e8bb65805a92ae1c8f3a4

And, just for a thought for future work, we could consider replacing uses of `getComputerName()` with `asio::host_name()`.  But that would be a different pull request.

**Comment by mellery451** [comment]
@scottschurr -- yep, in this case, I wanted to see the failure (to make sure I captured the original deficiency). Now that we have, I can either cherry pick or just wait and rebase. Thanks for your change...I'll grab that shortly.

**Comment by miguelportilla** [comment]
I am seeing linker errors with nounity on VS2017. This occurs using the VS integrated cmake, command line cmake, and the cmake generated VS solution. The unity builds compile fine.

```error LNK2001: unresolved external symbol "public: void __cdecl SpookyHash::Init(unsigned __int64,unsigned __int64)" (?Init@SpookyHash@@QEAAX_K0@Z) ```

**Comment by miguelportilla** [comment]
@mellery451 Cherry-picking https://github.com/ripple/rippled/pull/2368 did not help.

**Comment by miguelportilla** [comment]
Reverting the CMakeList.txt changes (back to 0.90.0-rc1) allows the non unity build to link.

**Comment by miguelportilla** [comment]
@mellery451 Last commit fixes the issue. The non-unity build is successfully linking. 👍

**Comment by mellery451** [comment]
rebased. this builds properly with the @MarkusTeufelberger `#include` fixes, so marking as passed.

**Comment by MarkusTeufelberger** [comment]
Also check out #2399 :-)

**Comment by MarkusTeufelberger** [comment]
Should also fix #2159 by the way.

**Comment by mellery451** [comment]
Merged in 605ace764

**Pull request closed without merging**
