### PR TITLE
Remove incompatible OS X switches in Test.py

### PR DESCRIPTION
**Pull request by miguelportilla**

### CODE REVIEW

**Comment by HowardHinnant** [comment]
I needed to set the execute permission flags on Test.py: https://github.com/HowardHinnant/rippled/commits/test_script
After that, everything built fine.

**Comment by miguelportilla** [comment]
@HowardHinnant 100755 → 100644  Thanks, will fix.

**Comment by HowardHinnant** [comment]
👍

**Comment by scottschurr** [comment]
I had the same file permission issue as @HowardHinnant, so I invoked with
```python Builds/Test.py -a```
It took a while 😄 but it all worked.  :+1:

**Pull request closed without merging**
