### PR TITLE
Massive scons refactoring!

### PR DESCRIPTION
**Pull request by rec**
Lots of exciting changes here.  I still have more extraction to do - eventually SConstruct will be tiny - but this is enough for now.

Looking for Windows testers with patience for this one.

### CODE REVIEW

**Comment by vinniefalco** [comment]
How do I build the beast "hello world" using this new SConstruct?

**Comment by rec** [comment]
You can't directly do it yet.  By the end of all this there will be nothing at all in the main SConstruct and it'll be near trivial to do.

**Comment by vinniefalco** [comment]
I think we should close this until the work is done and we have a "hello world" compiling.

**Comment by vinniefalco** [comment]
also, vcxproj is out of date

**Pull request closed without merging**
