### PR TITLE
Enable C++-14

### PR DESCRIPTION
**Pull request by seelabs**
@miguelportilla @nbougalis

### CODE REVIEW

**Comment by seelabs** [comment]
The code and the travis changes are ready for review. Unfortunately, I need to do some more work to get circleci tests working. Don't review circleci changes yet.

**Comment by seelabs** [comment]
Circleci now runs successfully. Note rippled no longer runs runder gdb for unittest as gdb segfaults with  a clang 3.6 compiled rippled (gdb segfaults, not rippled).

**Comment by seelabs** [comment]
The static linking isn't quite working yet, don't review the last commit. (I broke the linux clang build, gcc works as expected)

**Comment by seelabs** [comment]
OK, static link problems are fixed & clang build on linux works, all commits open for review.

**Comment by vinniefalco** [comment]
Builds successfully on VS2015

**Comment by vinniefalco** [comment]
:+1: for me, did not test on gcc/clang

**Comment by miguelportilla** [comment]
Unity/non Unity/Debug/Release build and all tests pass on OS X/LLVM 7.0.0 and Windows/VS2015.

Ubuntu 15.04/GCC 5.2/Clang 3.6 encounters: error: no member named 'make_reverse_iterator' in namespace 'std' (Scott is aware of this problem)

**Comment by seelabs** [comment]
The issue that @miguelportilla brings up (clang builds fail on linux distros that ship with gcc 4) is caused by clang using the standard library from gcc 4 instead of gcc 5. The best solution I have come up with is to use update-alternatives to use the new lib (see the circle.yml file for how to do this). However, updating the compiler like this is likely to cause problems (as we know with the ABI issues).

**Comment by nbougalis** [comment]
Looks good as is, but I don't gcc 5.x to test with. 

@seelabs one small nitpick: it seems that `beast/cxx14/type_traits.h` is only used in three places:
1. src/beast/beast/asio/waitable_executor.h
2. src/beast/beast/container/buffer_view.h
3. src/beast/beast/container/detail/aged_ordered_container.h

I suspect that we don't need it in `waitable_executor.h` and `buffer_view.h` which leaves only `aged_ordered_container.h`. If that's the case, should we just remove the file and move the workaround directly in the file that needs it?

**Comment by seelabs** [comment]
@nbougalis You're right, `cxx14/type_traits.h` is not needed in buffer_view.h or waitable_executor.h. Removed. I'd still like to keep this workaround in a separate file. It's a useful workaround for a defect in the standard, so we may use it elsewhere. Also, when new standards come out, it's easy to see where our workarounds live and remove them as needed.

**Comment by nbougalis** [comment]
:+1:

**Comment by vinniefalco** [comment]
@nbougalis FYI, w.r.t. what we should do with the workaround, we should emulate boost.

**Pull request closed without merging**
