### PR TITLE
Set configured administrative privileges upon initial

### PR DESCRIPTION
**Pull request by mtrippled**
websocket connection.

### CODE REVIEW

**Comment by vinniefalco** [comment]
Well that's lame, `-4` lines of code coverage

**Comment by nbougalis** [comment]
:+1:

**Comment by vinniefalco** [comment]
Commit message needs editing. Suggested multi-line message:
```
Set admin privileges on websocket:

When the websocket connection is established, any configured administrative
privileges are applied to resource limits.
```

**Comment by mtrippled** [comment]
@vinniefalco The commit message has been changed.

**Comment by miguelportilla** [comment]
:+1:

**Pull request closed without merging**
