### PR TITLE
Clean up test documentation and a log message.

### PR DESCRIPTION
**Pull request by rec**
I changed test/README.md to fix a missing word and to change the mocha call:

http://stackoverflow.com/questions/9722407/how-do-you-install-and-run-mocha-the-node-js-testing-module-getting-mocha-co

Also, tweaked a log message.

### CODE REVIEW

**Comment by rec** [comment]
Reviewer: @ximinez @nbougalis

**Comment by rec** [comment]
btw, sorry for the extra diffs - your editor seems to allow you to leave whitespace at the end of the line and mine doesn't.

When it's code, I turn that off to keep the diffs lean, but in this case it's just dox so I don't care.

**Comment by ximinez** [comment]
Thanks for cleaning this up.

:+1:

**Comment by nbougalis** [comment]
:+1:

**Pull request closed without merging**
