### PR TITLE
Remove LevelDB and HyperLevelDB backends:

### PR DESCRIPTION
**Pull request by vinniefalco**
The LevelDB and HyperLevelDB are removed from the backend choices. Neither were recommended for production environments. As RocksDB is not available on Windows platforms yet, the recommended backend choice for Windows is NuDB.

Reviewers should pay special attention to the SConstruct and rippled-example.cfg changes.

### CODE REVIEW

**Comment by ximinez** [comment]
Is anybody using these backends in the wild?

**Comment by vinniefalco** [comment]
@ximinez hyperleveldb most likely not, and leveldb is not recommended for production anyway. So if people are using them, they will need to switch. Hard to imagine though, because level and hyper create problems with I/O load during compactions.

**Comment by ximinez** [comment]
@vinniefalco  Works for me.

**Comment by miguelportilla** [comment]
:+1:  I am glad we are removing these!

**Comment by josh-ripple** [comment]
I would rewrite "determine if beneficial" as "determine if it's beneficial".  Other than that, looks good. :+1:

**Comment by nbougalis** [comment]
Merged as f3c1f634447440b320227fd864c57fb6075842ee

**Pull request closed without merging**
