### PR TITLE
Improved parsing of universal port configuration settings (RIPD-856)

### PR DESCRIPTION
**Pull request by miguelportilla**

### CODE REVIEW

**Comment by nbougalis** [comment]
The `config-example.js` file needs to be updated: it specifies `admin = allow` which is no longer allowed.

**Comment by miguelportilla** [comment]
@nbougalis Thanks, updated.

**Comment by nbougalis** [comment]
:+1:

**Comment by vinniefalco** [comment]
:+1:

Note that `beast::IP::Endpoint` is deprecated

**Comment by miguelportilla** [comment]
Updated config-example.js as Nik mentioned.

**Comment by nbougalis** [comment]
:+1:

**Comment by miguelportilla** [comment]
Doesn't compile in Windows. gmtime_r is linux only.

**Comment by nbougalis** [comment]
Merged as b1f6cb349ba0a753fe8856e1354b4aa410b5cdb2

**Pull request closed without merging**
