### PR TITLE
Improve openssl directory finding

### PR DESCRIPTION
**Pull request by seelabs**
@HowardHinnant @scottschurr Please test both cmake and scons builds.

### CODE REVIEW

**Comment by HowardHinnant** [comment]
How do you build with cmake?  My first try was `cmake nounity debug`.

**Comment by ximinez** [comment]
@HowardHinnant We do still need to work on the documentation. Try
```
mkdir build/cmake.nounity.debug
cd build/cmake.nounity.debug
cmake ../.. -Dtarget=nounity.debug
cmake --build .
./rippled --unittest
```
(I'm not positive where the executable will end up in your default build system, so that path may be wrong.)

**Comment by HowardHinnant** [comment]
👍

**Comment by scottschurr** [comment]
Both scons and cmake builds worked great for me.  I did both clang.debug.nounity and clang.release builds using both scons and cmake. :+1:

**Comment by ximinez** [comment]
This had a non-trivial conflict building the 0.40.0-b8 branch. Please rebase once develop is updated. (Hint: the relevant functionality has been moved to `Builds/CMake/CMakeFuncs.cmake`.)

**Comment by seelabs** [comment]
Rebased on to 0.40.0-b8

**Comment by bachase** [comment]
Merged as cdaafeb

**Pull request merged**
