### PR TITLE
Miscellaneous bug fixes

### PR DESCRIPTION
**Pull request by ximinez**
All of these issues came up when doing work on ripple-libpp. There are 5 seperate commits, because each commit solves one issue. I don't plan to squash them. I suggest reviewing each commit separately.

### CODE REVIEW

**Comment by ximinez** [comment]
Oops. I didn't write tests for the new code here. I'll push a commit ASAP.

**Comment by HowardHinnant** [comment]
That's going to ruin a perfectly good comment I had! ;-)

**Comment by HowardHinnant** [comment]
```
src/test/unity/protocol_test_unity.cpp:34:10: fatal error: 'test/protocol/TER_test.cpp' file not found
#include <test/protocol/TER_test.cpp>
         ^
1 error generated.
```

**Comment by ximinez** [comment]
My tests! Mine! No share!

**Comment by HowardHinnant** [comment]
Still 👍  for me.

**Comment by scottschurr** [comment]
Merged to rippled develop as 7e9ac16c225897b9d86bc3622680992895d8634d, 46004158a2fc48c9451ddf9ea663c617e983f70e, 96ece1b9f01a305ed5a3deae25bbe1b6f4a7f4cf, f7a7f13287d17d91b029ef32a64dfac1ef42a071, and 9cc542fe676d830e0f4d35a07f7a3d17b765eaf4

**Pull request closed without merging**
