### PR TITLE
Remove DinD Service from container build template

### PR DESCRIPTION
**Pull request by northrup**
Refactor how our Docker calls are invoked on the GitLab runners using `services` methods and moving away from Docker-in-Docker.

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
If you want to get rid of `docker build` alltogether, I can recommend taking a look at `kaniko` by the way.

**Review by manojsdoshi — APPROVED** [review]
LGTM

**Comment by nbougalis** [comment]
Kaniko looks interesting, @MarkusTeufelberger. Thanks for the pointer. This isn't really my field of expertise, so I'll let others decide whether this should be done.

**Comment by northrup** [comment]
@MarkusTeufelberger that is a good point, and we have `kaniko` elsewhere, for the image building that we do that's a good idea and I'll look to refactor those, we also use docker here to spawn build jobs within a CI run.

**Pull request merged**
