### PR TITLE
Respond 200 on empty HTTP request to support GCE ingress health check

### PR DESCRIPTION
**Pull request by tlongwell-ripple**
https://github.com/ripple/rippled/issues/3307

### CODE REVIEW

**Comment by tlongwell-ripple** [comment]
For https://github.com/ripple/rippled/issues/3307

**Comment by MarkusTeufelberger** [comment]
Why wouldn't you do your health checks on an actual health check endpoint instead?

**Comment by tlongwell-ripple** [comment]
Having a public HTTP health check endpoint would be a great feature. It should use some heuristic (like info from server_info) to return a meaningful response in addition to a 200.

This 200 is just an indication that the rippled server is running and accepting connections on a particular port. It is not meant to denote health wrt network synchronization/load/etc.

This was a suggestion from @nbougalis as a one-off build for a particular use case I have. My biggest motivation for opening the PR is really to have Travis run and see if this unexpectedly breaks anything.

**Comment by MarkusTeufelberger** [comment]
A non 200 response would also indicate that it is running and accepting connections.

**Comment by tlongwell-ripple** [comment]
Responding with a 200 allows this dumb endpoint to be used with a GKE ingress https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#health_checks

The ingress allows changing the path of the health check, but not the accepted response code. The response code must be exactly 200.

**Comment by MarkusTeufelberger** [comment]
You can set a path for readiness probes there, the /crawl endpoint for example would be a good workaround for this patch.

**Comment by MarkusTeufelberger** [comment]
See https://github.com/ripple/rippled/issues/2809 for some discussion on this topic by the way.

**Comment by intelliot** [comment]
Markus, that's a good idea. Docs are here: https://xrpl.org/peer-crawler.html

Example request: `https://s1.ripple.com:51235/crawl`

**Comment by carlhua** [comment]
@MarkusTeufelberger  @intelliot  I really appreciate the feedback. I will prioritize #2809 to be discussed in the near future.  This fix is simply to provide a 200 response for the load balancer. Lets review this PR while #2809 undergoes discussion.

**Comment by intelliot** [comment]
If this is for a load balancer, I think it might make sense to return 200 only if the server is synced with the network.

Sidenote: the `/crawl` endpoint does provide a 200 response:
```
% curl -I https://s1.ripple.com:51235/crawl
HTTP/1.1 200 OK
Server: rippled-1.4.0
Content-Type: application/json
Connection: close
Transfer-Encoding: chunked
```

**Comment by HowardHinnant** [comment]
Removing myself as reviewer.  The C++ looks fine.  But I'm not qualified to say if this is something that should be done for rippled.

**Comment by carlhua** [comment]
@nbougalis do we want this as part of 1.6?

**Comment by nbougalis** [comment]
I think we should fold the idea behind this into #3365 and consider following the guidelines provided by @MarkusTeufelberger in that thread. I'd suggest that we just close this.

**Pull request closed without merging**
