### PR TITLE
Allow Journal to be copied/moved

### PR DESCRIPTION
**Pull request by bachase**
I could be convinced this is an undesirable change, but it greatly simplifies some consensus related work I am doing.

### CODE REVIEW

**Comment by scottschurr** [comment]
This is not a topic I feel strongly about, but I'd like to do some sanity checking.  I _think_ it was Vinnie's position that Journals should be immovable.  A Log, on the other hand, is a very lightweight reference to a Journal, that that's what we should be moving around.  I'm guessing Vinnie would want to know what you want to do with the Journal that can't be done with a Log.

**Comment by bachase** [comment]
@scottschurr Could you point me to the `Log` class you are referencing?

**Comment by HowardHinnant** [comment]
@scottschurr Or maybe vice-versa? https://github.com/bachase/rippled/blob/febedc480435ddd56cae199dba4923b2a4dc32a7/src/ripple/beast/utility/Journal.h#L50-L52

**Comment by scottschurr** [comment]
Gaaaah.  I should know better than to try to talk about this stuff from memory.  Sorry, my mistake.  `Logs` (https://github.com/ripple/rippled/blob/develop/src/ripple/basics/Log.h#L49) is actually fairly heavy weight.  The `Journal`, what you're playing with, is light weight.

If I'd looked at your code, instead of just reading the headline, I'd see that the problem you really want to solve is making the `Journal` assignable after the fact.  They were previously copyable and moveable, but they were not assignable.

Personally, I have nothing against making `Journal`s assignable.  But having a `Journal` carry a pointer to a `Sink` instead of a reference to a `Sink` is a disadvantage, since a pointer can be null.

It would be good to see the use cases you're trying to solve before we make the change.

**Comment by HowardHinnant** [comment]
I've completed a visual once-over of `Journal` and I believe that the invariant that `m_sink` always refers to a `Sink` remains in place (before and after this change).  A comment by the `m_sink` member declaration that an invariant is that it is always non-null would be helpful to add.

*  The `Journal` copy constructor appears to me to be needlessly non-trivial.  I recommend having the compiler provide it.

*  As it stands now, we have:

1.   `~Journal()` is user-declared and compiler-provided.
2. `Journal (Journal const& other)` is user-declared and user-provided, but does the same thing as the compiler-provided copy constructor would do.
3. `Journal& operator=(Journal const&)` is not user-declared and is compiler-provided.

The implicitly provided copy assignment operator is currently being provided under deprecated behavior since the destructor and copy constructor are user-declared.

I recommend implicitly defaulting all three of these, or explicitly defaulting all three.  Either path will eliminate the dependence on deprecated behavior.

**Comment by HowardHinnant** [comment]
@scottschurr:  I believe this is a brief description of Brad's use case: https://ripplelabs.slack.com/archives/C02GE9NBA/p1511279746000806

**Comment by bachase** [comment]
I've squashed and made the commit message clearer per @scottschurr's suggestion.

The motivation: I have a type implementing a generic code that needs to log in some cases, but the generic code doesn't know anything about logging. The most convenient approach was for me to store the `Journal` in the type itself. The type must be assignable. I tried avoiding this design, but couldn't come up with a good alternative.

**Comment by scottschurr** [comment]
@HowardHinnant: Thanks for the reference.  @bachase, sorry for piping up before I really understood what was going on.  I'll try to avoid tripping over myself next time.  Carry on.

**Comment by bachase** [comment]
Piping up is good! Please continue to do so when something stands out to you.

**Comment by seelabs** [comment]
In 0.90.0-b3

**Pull request closed without merging**
