### PR TITLE
Consensus helpers cleanup

### PR DESCRIPTION
**Pull request by nbougalis**
I'm again listing you all in this commit, to get eyeballs since it's touching critical code. The first commit ("Refactor consensus") was already reviewed earlier.

@vinniefalco, @JoelKatz, @ximinez, @rec, @scottschurr, @seelabs, @HowardHinnant, @miguelportilla

### CODE REVIEW

**Comment by ximinez** [comment]
Code changes and moves look good. Everything builds. I left one suggestion to improve a comment, but it's not critical. :+1:

**Comment by scottschurr** [comment]
Looks good to me.  :+1:

**Comment by HowardHinnant** [comment]
Everything looks ok except for one mandatory comment that must be fixed.

**Comment by HowardHinnant** [comment]
My comment above was incorrect as Ed pointed out.  Please ignore.

:+1: Looks good to me.

**Comment by nbougalis** [comment]
Thanks all - will address all your comments.

**Comment by ximinez** [comment]
It looks like Github ate the comments from all the prior commits. :(
However, as best as I can tell, the current rebased and squashed commit still looks good. :+1: 
Is it safe to mark this one as passed?

**Comment by ximinez** [comment]
Woops. I just realized this one has the same link error found at https://github.com/ripple/rippled/pull/1111#issuecomment-112212644, with the fix described at https://github.com/ripple/rippled/pull/1111#issuecomment-112214722

**Comment by nbougalis** [comment]
Vinnie and I have found a couple of more things that could be done; unless I can get them done pretty quickly, I'll close this and reopen it in a day or two.

**Pull request closed without merging**
