### PR TITLE
Add dev docs generation to Jenkins:

### PR DESCRIPTION
**Pull request by mellery451**
Switch to pure doxygen HTML for developer docs. Remove docca/boostbook
system. Convert consensus document to markdown. Add existing markdown
files to doxygen input set.

This is how it looks when built/stored by jenkins:

https://ci.ops.ripple.com/view/rippled-dev/job/mellery-rippled/job/mellery-doxs/Doxygen/

### CODE REVIEW

**Comment by mellery451** [comment]
@bachase I shuffled a few more files around and I believe that images are working now in generated docs (doxygen) and in github rendering. Please let me know if you agree.

**Comment by bachase** [comment]
Clean looks good. I found one last image issue in the consensus simulation framework README if you want to grab it https://github.com/bachase/rippled/commit/81659e479d2382b216216389193cd68fcf1e726e.

**Comment by bachase** [comment]
A little late, but I believe you can also remove the `Jamroot` file in the top-level directory.

**Comment by mellery451** [comment]
closing this because I'm folding into a cumulative jenkins change (forthcoming)

**Pull request closed without merging**
