### PR TITLE
Send a websocket ping before timing out in server

### PR DESCRIPTION
**Pull request by vinniefalco**
This fixes a problem where idle websocket client connections could be disconnected due to inactivity.

### CODE REVIEW

**Comment by vinniefalco** [comment]
@donovanhide This branch fixes timeout problems seen by in-house testing and also other people running rippled. It _should_ fix your problem. If not then there is some other issue, and we will need additional information in order to address it.

**Comment by donovanhide** [comment]
Seems good so far, but I'll be able to confirm after 24 hours of connectedness.

Did the race kick in because I had two connections from the ip address?

**Comment by vinniefalco** [comment]
Two connections from the same IP will still have different remote ports, so will be distinct. The "race" referred to in the Beast commits are a related, internal bug.

**Comment by vinniefalco** [comment]
David has changes to this branch. It will have to be resubmitted.

**Pull request closed without merging**
