### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by yana-novikova**
@vinniefalco @nbougalis

### CODE REVIEW

**Comment by rec** [comment]
We only need one copyright notice per file...?

**Comment by vinniefalco** [comment]
@rec The copyright notices are for each image

**Comment by vinniefalco** [comment]
Fails Travis... lol

**Comment by miguelportilla** [comment]
Consider instead of placing a copyright notice next to each image, using one at the bottom of the page.

All Images Copyright © 2015 Ripple labs, All Rights Reserved.

**Comment by vinniefalco** [comment]
@miguelportilla Can you please submit a patch?

**Comment by vinniefalco** [comment]
Can we please finish this already?!

**Pull request closed without merging**
