### PR TITLE
Add a sensible pass limit to the payment engine

### PR DESCRIPTION
**Pull request by JoelKatz**
This adds a limit of 1,000 passes to the payment engine. It protects against possible cases where the execution of a pass fails to exhaust the liquidity that made that very pass possible or cases where two passes alternate providing liquidity for each other.

### CODE REVIEW

**Comment by ximinez** [comment]
:+1:

**Comment by vinniefalco** [comment]
"sensible" is not a sterile word. Suggested:
`Limit excessive numbers of passes in the payment engine"

**Comment by ximinez** [comment]
How about "Limit number of passes in the payment engine"? 

Removes all judgmental and value-implying words.

**Comment by JoelKatz** [comment]
What is a "sterile" word?

**Comment by vinniefalco** [comment]
+1 to Ed's suggestion

**Comment by JoelKatz** [comment]
It seems the opposite of clarity. The other suggestions explain why this change was made and what forms the basis for the chosen limit. He's just removed that information, leading to a commit message that you can only understand if you're familiar with the issue.

**Comment by vinniefalco** [comment]
@JoelKatz You already gave the answer:
```
Limit number of passes in the payment engine:
This adds a limit of 1,000 passes to the payment engine. It protects against possible cases where the execution of a pass fails to exhaust the liquidity that made that very pass possible or cases where two passes alternate providing liquidity for each other.
```

**Comment by JoelKatz** [comment]
In the pull request, but those aren't retained anywhere AFAIK.

**Comment by vinniefalco** [comment]
@JoelKatz I'm saying, that could be the commit message

**Comment by JoelKatz** [comment]
That's better. At least then you can find it in the commit message. But I still don't see why we should remove useful information from the short message. The value judgment explains why the change was made and it pretty close to the most useful information about the change you could have.

**Comment by vinniefalco** [comment]
How about
```
Limit passes in the payment engine to prevent endless looping:
This adds a limit of 1,000 passes to the payment engine. It protects against
possible cases where the execution of a pass fails to exhaust the liquidity
that made the pass possible or cases where two passes alternate
providing liquidity for each other.
```

**Comment by JoelKatz** [comment]
I'm going to add some logging to this case. I can put the new commit message in that change and then the person merging can use the new log message.

**Comment by vinniefalco** [comment]
That looks so good, I'm going to print it out and frame it!

**Comment by nbougalis** [comment]
:+1:

**Comment by rec** [comment]
Reviewers: @nbougalis @ximinez

**Comment by JoelKatz** [comment]
This is only sort of a Tx Change. It doesn't require coordinated deployment.

**Comment by rec** [comment]
The Tx Change flag precisely means, "A transaction change that DOES require coordinated deployment", so I'm taking it off again.   :-)

(This is so the pull robot knows which pull requests are safe to build into the next develop branch...)

**Pull request closed without merging**
