### PR TITLE
State accounting:

### PR DESCRIPTION
**Pull request by mtrippled**
Record total duration spent in and every transition to each
possible server state. Display as counters through server_info
RPC call.

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
Similar to #1354 - please consider exposing this via the statsd interface too.

**Comment by mtrippled** [comment]
@miguelportilla @scottschurr I just rebased this against the tip of develop.

**Comment by scottschurr** [comment]
I just took a quick look at the feature set you're providing.  For similar measurements I've made in the past it has been really useful to be able to clear the counters.  Is there an RPC command you could leverage to clear the counters?  If that's possible, then I'd suggest reporting your five value pairs plus the time that this recording session started.

Does that seem to you like it would be useful?

**Comment by mtrippled** [comment]
@scottschurr Hi, Scott. Sampling this data over time and then diffing the results from each sample has the same effect that you're describing. That's how monitoring systems calculate network interface bandwidth usage, for example.

I've been collecting this data from a couple of servers for the past week or so on systems that are using the commit in this PR. I wrote a python script that gathers the data and formats into tab-delimited. The 1st 5 columns after timestamp and hostname are the # of transitions. The last 5 columns are the total microseconds in each state:

2015-10-21 20:48:48.249404	estch15	1	2	5942	2351	5861	1092769	11019243	77998366323	671320512	948179180760
2015-10-21 20:49:48.804219	estch15	1	2	5944	2352	5864	1092769	11019243	78013319899	671320532	948224777506
2015-10-21 20:50:49.368213	estch15	1	2	5944	2352	5864	1092769	11019243	78013319899	671320532	948285337484
2015-10-21 20:51:49.927837	estch15	1	2	5945	2352	5865	1092769	11019243	78017931487	671320532	948341288305
2015-10-21 20:52:50.500131	estch15	1	2	5945	2352	5865	1092769	11019243	78017931487	671320532	948401851655
2015-10-21 20:53:51.009783	estch15	1	2	5945	2352	5865	1092769	11019243	78017931487	671320532	948462376173
2015-10-21 20:54:51.558449	estch15	1	2	5945	2352	5865	1092769	11019243	78017931487	671320532	948522897981
2015-10-21 20:55:52.078287	estch15	1	2	5945	2352	5865	1092769	11019243	78017931487	671320532	948583444753
2015-10-21 20:56:52.640976	estch15	1	2	5945	2352	5865	1092769	11019243	78017931487	671320532	948643997926
2015-10-21 20:57:53.160925	estch15	1	2	5945	2352	5865	1092769	11019243	78017931487	671320532	948704526138

From here it is a matter of calculating differences and we'd have a per-minute rate for each column. And the durations can be compared against one another to report % of time in each state, or not-full, and so forth.

**Comment by mtrippled** [comment]
Of note in those particular data points is that there were 3 transition to the syncing state during the sampling period (5945-5942), 1 to tracking (2352-2351) and 4 to full (5865-5861). The corresponding durations for each field increased as a result.

**Comment by scottschurr** [comment]
Fair enough.  You've clearly thought about it.  Thanks for the explanation.

**Comment by mtrippled** [comment]
Hi, @miguelportilla @scottschurr 
I just pushed changes based on Mickey's recent suggestions. I don't know how to reply to each comment individually now that the new commit has been made, so I'm just putting all of Mickey's suggestions, with my responses, as follows:

==================================

 miguelportilla added a note 8 hours ago

This member is not necessary and can be removed. Use stateNames in its place instead.
---------------------------------------

As Scott S alluded, feeding Json::Value a Json::StaticString means it doesn't
have to construct a StaticString out of a string. Creating the object once
for each JSON value name saves that construction on each call.

..............

 miguelportilla added a note 8 hours ago

This member is not necessary and can be removed. Use stateNames in its place instead.
-------------------------------------------

see above about setting Json::Value names.

..............

 miguelportilla added a note 8 hours ago

This should be const. The element type should be std::string. The assignment and double curlies should not be necessary.
static std::array const stateNames {"disconnected", "connected", "syncing", "tracking", "full"};
----------------------------------

Fixed. I had to add a constructor for Json::StaticString to take std::string.

.................

 miguelportilla added a note 8 hours ago

This member is not necessary and can be removed. Use stateNames in its place instead.
----------------------------------

Repeat suggestion, see above.

................

 miguelportilla added a note 9 hours ago

This member is not necessary and can be removed. Use stateNames in its place instead.
---------------------------------

Repeat suggestion, see above.

.................

 miguelportilla added a note 8 hours ago

'transitions_' and 'dur_' add no value. I recommend in-lining "transitions" and "duration_us" in the single spot they are used.

What does '_us' signify?
---------------------

transitions_ and dur_ are both StaticString objects, constructed once.
Otherwise, Json::Value needs to construct StaticString objects each time
JSON is output with those names. us is microseconds like Scott S said.

......................

 miguelportilla added a note 8 hours ago

'now' can be in-lined, the local is unnecessary and not useful. If you are going to create a local here I recommend 'elapsed', which would be useful for debugging purposes.
----------------------
Fixed.

........................

 miguelportilla added a note 8 hours ago

Consider something like this non const implementation which avoids making copies and updates the current mode duration.
-------------------------
I think it's better to optimize for spending minimum time in locks even
if it means possibly spending more time overall, such as the trade-off between
only doing a copy within the lock vs doing all of the work within the lock but
avoiding the copy.

Sampling the system time generally requires a syscall, for example, which can
be relatively expensive.

.........................

 miguelportilla added a note 6 hours ago

You may want to consider having each counter initialized with a member state name. That would remove the necessity of copying it each time json() is called. It would also simplify this loop. You might also be able to write transitions as integer rather than a string which would remove the conversion.
------------------------
Same answer as above about avoiding a copy vs minimizing lock usage.

**Comment by mtrippled** [comment]
@scottschurr I've put the extra curly braces back to avoid clang warnings.

@miguelportilla I've moved the JSON fields "transitions" and "duration_us" to a better place so that they're out of the StateAccounting class. The array still needs to be there so that the names can be assigned by iterating through the mode/state enumerator.

@miguelportilla I've also made Counters.transitions 32bit so it doesn't require converting to a string for JSON. I don't think it's conceivable for there to be billions of state transitions to overflow the counter.

**Comment by mtrippled** [comment]
@scottschurr I reverted the StaticString construction.

**Comment by scottschurr** [comment]
Looks great to me.  :+1:

**Comment by miguelportilla** [comment]
:+1:

**Comment by nbougalis** [comment]
Merged as fdd012c4206b4ad6242fc3dc6ede248e193f36b6.

**Pull request closed without merging**
