### PR TITLE
Optimize queries for account_tx to work around SQLite query planner

### PR DESCRIPTION
**Pull request by mtrippled**

### CODE REVIEW

**Comment by mtrippled** [comment]
The unit test is failing because the manual filter threw off the LIMIT clause's results. I have to rethink this.

**Comment by mtrippled** [comment]
I rewrote the SQL in the original instead of making a manual filter. It passes unit tests and improves performance.

**Comment by sublimator** [comment]
How big is a full history sqlitedb these days? Is it even still possible?

**Comment by bachase** [comment]
👍

**Comment by ximinez** [comment]
Nit: Remove the `.` from the commit message.

**Comment by mtrippled** [comment]
@ximinez You're right that the original query should be slightly faster because it only joins on those 2 fields once, whereas the new version essentially takes the union of 2 distinct search queries that each join on those 2 fields. But the query planner for the original version wasn't picking up the index for one or both of the operands of the OR expression in the query.

**Comment by bradsavon** [comment]
This is referenced in https://ripple.com/dev-blog/rippled-version-0-81-0/ but not merged?

**Comment by mtrippled** [comment]
@bradsavon It will get merged into the develop branch, which will turn into 0.90. This was put into the current production code because it will contribute to stability right away.

**Comment by bradsavon** [comment]
Great, thanks for clarification

**Comment by seelabs** [comment]
In 0.90.0-b3

**Pull request closed without merging**
