### PR TITLE
Store index before publish (RIPD-1052, RIPD-1053)

### PR DESCRIPTION
**Pull request by miguelportilla**
Fixes an issue where validated ledgers where being published before we had stored the new index.

@JoelKatz

### CODE REVIEW

**Comment by BobWay** [comment]
That’s cool. Does that mean that the behavior where sometimes account_tx doesn’t contain a previously published ledger will go away?

**Comment by miguelportilla** [comment]
@BobWay Absolutely, this will definitely fix the account_tx issues that were reported in RIPD-1052 and RIPD-1053.

**Comment by JoelKatz** [comment]
:neckbeard::+1:

**Comment by BobWay** [comment]
That's awesome Miguel!

**Comment by nbougalis** [comment]
Merged as 3e5ec9197797d0c257159532b54e3c12c82495da.

**Pull request closed without merging**
