### PR TITLE
Consolidate RPC utility functions (RIPD-947)

### PR DESCRIPTION
**Pull request by miguelportilla**
Consolidated miscellaneous RPC functions in separate files into a single header and source file.

### CODE REVIEW

**Comment by ximinez** [comment]
Reviewers: @ximinez @scottschurr

**Comment by ximinez** [comment]
Just a code reorg. No actual changes, except for deleting a couple of unused classes. :+1:

**Comment by ximinez** [comment]
PS. So why did code coverage drop?

**Comment by vinniefalco** [comment]
@ximinez Good question. I have yet to figure out how the code coverage deltas are computed.

**Comment by scottschurr** [comment]
:+1: Looks good to me.

**Pull request closed without merging**
