### PR TITLE
Log ledger data request times:

### PR DESCRIPTION
**Pull request by vinniefalco**
Tracks the turnaround time between a TMGetLedger and its corresponding TMLedgerData. This works for both originated and relayed messages.

Reviewers: Only the most recent commit is part of this set, the others are from another pull request.

### CODE REVIEW

**Comment by rec** [comment]
Reviewers?

I can do this, I don't have too many on the line.

**Comment by vinniefalco** [comment]
@rec Just need to make one tweak before reviewing

**Comment by ximinez** [comment]
Reviewers: @ximinez @rec

**Comment by ximinez** [comment]
:+1:

**Comment by rec** [comment]
But it's never been compiled.  Why put it in?

Isn't there a way to have it compile, but guaranteed never to execute?  Like, a static const bool you check?

**Comment by rec** [comment]
Can I get you to rebase against develop so we can just see the (now two) commits that are part of this?

**Comment by vinniefalco** [comment]
Both ideas are good

**Comment by mtrippled** [comment]
This is useful for data gathering. However, I've had it twice cause rippled to hang on a machine. I'm not positive that it's related to this patch, but the only other things I've added to the build I'm using are output lines to the debug.log. This is useful for data gathering, and if it's available as compile flag that's probably for the best.

**Comment by JoelKatz** [comment]
This breaks relaying. Since every request already has a request cookie, it's not eligible for relaying when received.
https://github.com/ripple/rippled/blob/develop/src/ripple/overlay/impl/PeerImp.cpp#L1787-L1792
A temporary fix might be to send requests that we want the other side to relay without a cookie. We won't be able to measure their latency, but there's not much we can do about that.

**Comment by vinniefalco** [comment]
@JoelKatz Since these are protobufs, can I just add a new field "key" and leave the request cookie alone? Older versions will forward them as-is, or no? Or will that fail because it won't know to copy that field to build the `TMLedgerData` response?

**Comment by rec** [comment]
Which protocol buffer type are you adding the new field `key` to?

**Comment by vinniefalco** [comment]
@rec Two solutions are possible:
1. Add `uid` to `TMGetLedger` and `TMLedgerData`, when replying with `TMLedgerData` set the `uid` to the `uid on the corresponding `TMGetLedger`
or
2. Add a "relay" flag to the type and use that instead of the cookie to indicate if the message should be relayed. Then the cookie is available to use always.

Both of these require a network upgrade to work fully.

**Comment by vinniefalco** [comment]
Pushed a fix that only logs the times for relayed messages, to solve a bug where originated messages would no longer be eligible for relay (because they set the requestcookie).

**Comment by JoelKatz** [comment]
@vinniefalco You can add a new optional field and it won't create any problems. But existing servers will not preserve it.

**Comment by vinniefalco** [comment]
Throwing this out because David says its not useful.

**Pull request closed without merging**
