### PR TITLE
Remove OpenSSL Base64 encoding dependency (RIPD-1238)

### PR DESCRIPTION
**Pull request by willwray**

### CODE REVIEW

**Comment by miguelportilla** [comment]
:+1:

**Comment by vinniefalco** [comment]
That was easy :-)

**Comment by nbougalis** [comment]
:+1:

**Comment by willwray** [comment]
What happens next? Who's merge-master?

It's tempting to hit the merge button on GitHub.com but I see advice on  SO against doing that.
I guess it's best to merge PRs in batch at end of day to save devs from having to update often.

**Comment by vinniefalco** [comment]
This will go into the next beta version

**Comment by nbougalis** [comment]
Merged as 69b91065c5a2bd1e6d618c40b7d9e104dd762bee

**Pull request closed without merging**
