### PR TITLE
Link Postgres statically 

### PR DESCRIPTION
**Pull request by legleux**
## High Level Overview of Change
Postgres was linked dynamically now it's static.
Had to tack on a few more libraries.

### Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor (non-breaking change that only restructures code)
- [ ] Tests (You added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation Updates
- [ ] Release

### CODE REVIEW

**Review by cjcobb23 — APPROVED** [review]

**Review by thejohnfreeman — APPROVED** [review]

**Comment by thejohnfreeman** [comment]
Curious: is it possible to just install the Postgres shared libraries when they are built as an External Project?

**Comment by cjcobb23** [comment]
> Curious: is it possible to just install the Postgres shared libraries when they are built as an External Project?

Install them system wide? You can just install all of this via the package manager actually.

**Comment by thejohnfreeman** [comment]
Hmmm, #3881 wasn't entirely clear. Let me spell out my understanding of the issue:

On a system without Postgres installed, if you build rippled (with CMake), it will download and build Postgres as an External Project. Then if you install rippled (with CMake), it will installed rippled and supporting libraries, but not Postgres, such that if you run rippled from the installed location (`/opt/ripple/rippled` in the example in #3881), then it will complain that Postgres shared libraries cannot be found.

Is that a fair assessment?

**Comment by cjcobb23** [comment]
> Hmmm, #3881 wasn't entirely clear. Let me spell out my understanding of the issue:
> 
> On a system without Postgres installed, if you build rippled (with CMake), it will download and build Postgres as an External Project. Then if you install rippled (with CMake), it will installed rippled and supporting libraries, but not Postgres, such that if you run rippled from the installed location (`/opt/ripple/rippled` in the example in #3881), then it will complain that Postgres shared libraries cannot be found.
> 
> Is that a fair assessment?

Pretty much. Though I don't know for sure that all supporting libraries are also installed. We link supporting libraries statically by default, in which case they don't need to be installed. In the linked issue, the libraries were being linked statically. Postgres was being built as a shared library always though.

**Review by manojsdoshi — APPROVED** [review]
LGTM

**Pull request closed without merging**
