### PR TITLE
Replace few macros as constexpr constants

### PR DESCRIPTION
**Pull request by seelabs**
New PR for https://github.com/ripple/rippled/pull/2508

### CODE REVIEW

**Comment by scottschurr** [comment]
@JoeLoser, thanks for the contribution!  You have a nice, tidy little cleanup here.

That said, there's always a complication.  This one is a personal preference.  We'll see what other members of the team think.

The 6 constants that you've converted from macros to `constexpr` are all `UPPER_CASE` as befits a macro.  As Herb Sutter said in C++ Coding Standards item 16...

> ... always give them SCREAMING_UPPER_CASE_AND_UGLY names...

The trick is that, thanks to your fix, they are no longer macros.  But they retain their uppercaseness.  So when I'm reading source code I worry that they might be macros, even though they are not.

Some folks think that all constants should be all upper case.  That's not my position, and I don't think many on the team would agree with that position.  But I could be wrong; it happens.  A lot.

At any rate, my personal preference would be to tweak the names a bit since we no longer have macros in our hands (thankfully).  A possible approach would be to use the model provided by the TER codes (https://github.com/ripple/rippled/blob/develop/src/ripple/protocol/TER.h).  They have a short lower case prefix followed by ugly all caps.  I find this a useful hint, at least in this code base, that what I have is not a macro, but is a constant.

So I'll suggest renaming the values to:

- `txnSQL_NEW`
- `txnSQL_CONFLICT`
- `txnSQL_HELD`
- `txnSQL_VALIDATED`
- `txnSQL_INCLUDED`
- `txnSQL_UNKNOWN`

But I'm also open to being told that's silly by my team mates.

The name change should not be too bad.  I think it will show up only in Transaction.cpp and STTx.cpp.

**Comment by JoeLoser** [comment]
[Here](https://github.com/JoeLoser/rippled/commit/1d1de0958ff4693c537888620eb49dcf039f99e2) is a proposed patch taking into account the feedback from @scottschurr. Someone with more knowledge of this particular neighborhood of code may have a better identifier for [the enum identifier](https://github.com/JoeLoser/rippled/commit/1d1de0958ff4693c537888620eb49dcf039f99e2#diff-e29a42283d218be546efb2410c71ef51R33) here.  Please bikeshed it. :)

**Comment by seelabs** [comment]
@JoeLoser I pushed your patch. FYI, I prefer not to force push PR until they are squashed at the end, that way it's easier for reviewers to easily see what's changed. In this case, the patch isn't too large so I didn't mind for this one (and the team does that sometimes too).

**Comment by seelabs** [comment]
@JoeLoser I pushed your patch. FYI, I prefer not to force push PR until they are squashed at the end, that way it's easier for reviewers to easily see what's changed (i.e. it would have preferred the patch was built on this PR instead of develop). In this case, the patch isn't too large so I didn't mind for this one (and the team does that sometimes too).

**Comment by JoeLoser** [comment]
@seelabs Thanks for the explanation.  Looks like the team likes to use feedback from a PR and commit it as `[FOLD] some message here`. Once all of the feedback is addressed and others have approved, it suffices to just squash at that point.  So, I'll adopt that style from now on.

**Comment by scottschurr** [comment]
On the topic of `enum` vs `enum class` I can give my own impressions.  But be aware that my opinions do not necessarily reflect those of my team mates.

My personal opinion is that I'm biased in favor of `enum class` over `enum`.  But there are some situations that call for `enum`, so I'm not an all-or-nothing kind of guy.  I'd prefer to take the instances of `enum` on a case-by-case basis and understand the benefits of the conversion before necessarily making the jump to `enum class`.  If we decide to leave an `enum` as a non-scoped `enum` it may deserve a comment in the code providing the justification.

How did we end up with so many non-scoped `enum`s?  I'd guess that most of those enums were written before scoped `enum`s were available in our compilers.  So I think it's primarily a legacy issue.

That said, what are the reasons to leave an `enum` as a non-scoped `enum?  I can think of two off the top of my head, but there may be more I'm not thinking about right now:

1. If it is desirable to be able to convert the `enum` easily to its underlying type, then converting the `enum` to `enum class` may be counterproductive.

2. Sometimes using instances of scoped `enum`s can get wordy (or at least charactery), and I have team mates who have a strong bias toward fewer characters.

That said, this appears to be one of the cases where the primary point of the constants is to be names for specific `char` values.  So, to me at least, this is a situation where `enum class` doesn't pay off.

What *does* pay off in this case is specifying the underlying type of the `enum`.  With a non-scoped `enum` the underlying type is selected by the compiler.  In our specific case all of the members of the `enum` are intended to be thought of as `char`.  We should tell the compiler that.  Otherwise the underlying type might be `int` or `unsigned int` and we'd end up doing needless (and occasionally dangerous) narrowing conversions.

So, after all this thrashing around, my inclination for the enum declaration looks something like this:

```
enum TxnSql : char
{
    txnSqlNew = 'N',
    txnSqlConflict = 'C',
    txnSqlHeld = 'H',
    txnSqlValidated = 'V',
    txnSqlIncluded = 'I',
    txnSqlUnknown = 'U'
};
```
Reasons:

1. In this code base prefer initial cap camel case for types.  `TxnSql` is a type.
2. Make sure the underlying type of the enum is what you want.
3. In this code base prefer initial lower camel case for values.
4. This `enum` is  primarily used to give names to `char` values.  So a scoped `enum` would be counterproductive.
5. Because the `enum` is not scoped, the enumerators need long names since they will leak into the surrounding scope.

Just my take.  Hope that helps.

**Comment by JoeLoser** [comment]
@scottschurr that helps a lot, actually! Very insightful into your thought process and reasoning for things. In all parts of the informative response, I agree.

Thanks for being patient and helping me understand the preferred style for the codebase. Sorry it took a few round trips of back and forth for such a simple change.

I'll post a patch later tonight.

**Comment by JoeLoser** [comment]
@seelabs A patch taking into the latest feedback from @scottschurr can be found here at [JoeLose/rippled@ f0af85e](https://github.com/JoeLoser/rippled/commit/f0af85ec680f9320bc0aeba98acb3d66088f01be)

I simply created a new branch `sttx_macros` from `seelabs:joe-constexpr` so it should be rebased properly and such.  Should be good to just cherry-pick.

**Comment by seelabs** [comment]
Pushed latest patch from @JoeLoser

**Comment by JoeLoser** [comment]
@scottschurr of course, glad to contribute. Thanks for the review. Since you've approved these changes, do you mind marking the PR with the passed label so it can go into the upcoming dev-next branch?

**Comment by scottschurr** [comment]
@JoeLoser, we can't mark as passed yet.  We still need to hear from @ximinez.

**Comment by seelabs** [comment]
In 1.1.0-b2

**Pull request closed without merging**
