### PR TITLE
Changed strand_.post to strand_.dispatch

### PR DESCRIPTION
**Pull request by tanisman**
asio already has a built-in function for this operation.
You can check source code: https://github.com/chriskohlhoff/asio/blob/master/asio/include/asio/detail/impl/strand_service.hpp#L58-L63
Referance: http://www.boost.org/doc/libs/1_65_1/doc/html/boost_asio/reference/io_service/dispatch.html

### CODE REVIEW

**Comment by JoelKatz** [comment]
This will result in an endless loop as `BasePeer::close` dispatches a call to `BasePeer::close`. Instead, dispatch a call to `impl().ws_.lowest_layer().close(ec)`. We should probably audit all calls to `strand::running_in_this_thread` to see if we can make this improvement in more places.

**Comment by tanisman** [comment]
My mistake sorry, I have just edited this code on browser when saw `strand_.running_in_this_thread` call.
Passing impl().ws_.lowest_layer.close as CompletionHandler to `dispatch` instead of passing `BasePeer::close` will fix the problem.However after I sent pr I have seen there is a lot more call to `strand_.running_in_this_thread` but I haven't got much time clone and change all calls.

**Comment by JoelKatz** [comment]
I think the general way to do it would be to change things like:

```
template<class Handler, class Impl>
void
BaseWSPeer<Handler, Impl>::
send(std::shared_ptr<WSMsg> w)
{
    if(! strand_.running_in_this_thread())
        return strand_.post(std::bind(
            &BaseWSPeer::send, impl().shared_from_this(),
                std::move(w)));
    if(do_close_)
        return;
    if(wq_.size() > port().ws_queue_limit)
    {
        JLOG(this->j_.info()) <<
            "closing slow client";
        cr_.code = static_cast<beast::websocket::close_code>(4000);
        cr_.reason = "Client is too slow.";
        wq_.erase(std::next(wq_.begin()), wq_.end());
        close();
        return;
    }
    wq_.emplace_back(std::move(w));
    if(wq_.size() == 1)
        on_write({});
}
```

To this:

```
template<class Handler, class Impl>
void
BaseWSPeer<Handler, Impl>::
send(std::shared_ptr<WSMsg> wmsg)
{
    strand_.dispatch(
        [this, w = std::move(wmsg), sthis = impl().shared_from_this()]()
        {
            if(do_close_)
                return;
            if(wq_.size() > port().ws_queue_limit)
            {
                JLOG(this->j_.info()) <<
                    "closing slow client";
                cr_.code = static_cast<beast::websocket::close_code>(4000);
                cr_.reason = "Client is too slow.";
                wq_.erase(std::next(wq_.begin()), wq_.end());
                close();
                return;
            }
            wq_.emplace_back(std::move(w));
            if(wq_.size() == 1)
                on_write({});
        });
}
```

I think it might make the code slightly harder to understand. It also requires an extra call to `shared_from_this` in the case where we don't have to dispatch. I'm not sure it's an improvement in the general case.

**Comment by nbougalis** [comment]
@tanisman, do you plan on updating this PR to address the feedback by David Schwartz? If not, should we consider closing this for now?

**Pull request closed without merging**
