### PR TITLE
NuDB: Reduce storage requirements of the database

### PR DESCRIPTION
**Pull request by vinniefalco**
This introduces the following external changes in nudb:
* lz4 is the current compression codec
* buckets store hashes instead of full keys
* existing databases are no longer compatible (delete them)

Internal changes:
* Added `varint`
* `Codec` is a template argument
* Removed `buffers` pessimization
* Fetch handler signature change

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
"existing databases are no longer compatible"
*shakes fist angrily at the sky*

Ah well, if it makes the database smaller...

**Comment by vinniefalco** [comment]
@MarkusTeufelberger Existing *nudb* databases. Do you have a nudb database?

**Comment by MarkusTeufelberger** [comment]
Yes, importing from RocksDB at the moment.

I'll put that on hold for a while until 0.28 comes out, no worries. Not production by far. :wink:

**Comment by vinniefalco** [comment]
Yeah...sorry about that! If its any consolation, I'm working on an optimized rocksdb to nudb import tool that will make it easy to import.

**Pull request closed without merging**
