### PR TITLE
[CI] get lcov from github

### PR DESCRIPTION
**Pull request by MarkusTeufelberger**
...instead of sourceforge.com (which seems to be in its final breaths)

### CODE REVIEW

**Comment by sublimator** [comment]
Cool, thanks!

**Comment by vinniefalco** [comment]
Is SourceForge dying?

**Comment by MarkusTeufelberger** [comment]
Well, they pulled off stuff like this: https://sourceforge.net/blog/gimp-win-project-wasnt-hijacked-just-abandoned/ (the "DevShare" program has been abandoned now, after their latest sale - they seem to change owners quite often these days)

"Mirrored projects are sometimes used to deliver easy-to-decline third-party offers, and the original downloads are always available."

The main reason for suggesting this change though: At least a few of your recent travis builds failed only because sourceforge.com was unreachable (you are downloading lcov 1.12 from scratch on every CI build) and github is usually more reliable in hosting stuff, hence why I changed the link.

**Comment by vinniefalco** [comment]
Thanks! Those spurious CI failures are indeed quite irritating.

**Comment by HowardHinnant** [comment]
merged.

**Pull request closed without merging**
