### PR TITLE
Add FlowV2 to supportedAmendments

### PR DESCRIPTION
**Pull request by seelabs**

### CODE REVIEW

**Comment by seelabs** [comment]
I need to figure out how to test this

**Comment by nbougalis** [comment]
There's nothing to test. I'm assuming that `5CC22CFF2864B020BD79E0E1F048F63EF3594F95E650E43B3F837EF1DF5F4B26` is the value returned from `feature("FlowV2")`?

**Comment by seelabs** [comment]
@nbougalis Yes, that's how I got the hash. I wanted to try to turn the amendment on locally to make sure I got everything right so we don't have to do another rc.

**Comment by ximinez** [comment]
Here's your test, approximately:

**Comment by ximinez** [comment]
Here's your test, approximately:
```
void testSupportedAmendments()
{
    for(auto const& amend : supportedAmendments())
    {
         expect(amend.substr(0, 64) == feature(amend.substr(65)));
    }
}
```

**Comment by seelabs** [comment]
Pushed a unit test for supported amendments.

**Comment by ximinez** [comment]
Looks good, assuming CI passes. :+1:

**Pull request closed without merging**
