### PR TITLE
TimeKeeper

### PR DESCRIPTION
**Pull request by vinniefalco**
Time management functionality from NetworkOPs is refactored and put in its own class. `NetClock::time_point` is offered in interfaces. This doesn't propagate the `time_point` change to all sites yet.

### CODE REVIEW

**Comment by HowardHinnant** [comment]
Clang gives these warnings:
````
src/ripple/core/impl/SNTPClock.cpp:252:13: warning: add explicit braces to avoid dangling else [-Wdangling-else]
            else
            ^
src/ripple/core/impl/SNTPClock.cpp:249:13: warning: add explicit braces to avoid dangling else [-Wdangling-else]
            else if (query->second.replied)
            ^
src/ripple/core/impl/TimeKeeper.cpp:98:13: warning: add explicit braces to avoid dangling else [-Wdangling-else]
            else
            ^
1 warning generated.
````

**Comment by HowardHinnant** [comment]
unittest ends ingloriously:
````
ripple.tx.Taker IOU to IOU
Longest suite times:
    1.3s ripple.app.Path
    1.0s ripple.shamap.sync
9.0s, 87 suites, 365 cases, 287233 tests total, 0 failures
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: thread::join failed: No such process
Abort trap: 6
````

**Comment by vinniefalco** [comment]
err..these were fixed already - looking into it

**Comment by HowardHinnant** [comment]
`abstract_clock::elapsed` should be marked deprecated.  We currently only use it in ripple/resource/impl/Logic.h.  It is a dangerous break in the unit's type-safety.

**Comment by vinniefalco** [comment]
Agree, removed

**Comment by HowardHinnant** [comment]
We need to forbid copying `abstract_clock` so that we don't accidentally slice it in production code.  However we do copy the concrete test clock in tests, so allow for that: https://github.com/HowardHinnant/rippled/commit/52d79a6b7b157dbd782ed1d9d56d43d673c73f32

**Comment by vinniefalco** [comment]
Nice, this helps shore up an area where I've been having anxiety - how to mark special members in abstract bases.

**Comment by HowardHinnant** [comment]
:+1:  This looks like a solid stepping stone on the road to chrono!

**Comment by vinniefalco** [comment]
I'm reluctant to refactor or make improvements to the `SNTPClock` implementation.  There's no unit test coverage for it, and adding coverage would be difficult (since it contacts external servers). There's a chance of breakage, with no way to know if it broke, and its critical code because the clock values are used for consensus.

**Comment by miguelportilla** [comment]
Some of the code could use some refactoring but I am not holding the PR back.  :+1:

**Pull request closed without merging**
