### PR TITLE
Eclipse HOWTO with pictures

### PR DESCRIPTION
**Pull request by crazyquark**
A little README to explain how to compile rippled with Eclipse. With pics.

### CODE REVIEW

**Comment by crazyquark** [comment]
OK OK, will come back later with a better README :)

**Comment by crazyquark** [comment]
Cleaned up.

**Comment by nbougalis** [comment]
Thanks for doing this. Did you mean to close this or would you still like us to review this for inclusion?

**Comment by crazyquark** [comment]
I have now some more changes that do not make sense in the context. I probably need to make a separate branch with only the Eclipse stuff and do a pull request from there. I don't know how else to selectively merge. So, yes, I meant to close it. I will come back with a cleaner pull request.

**Pull request closed without merging**
