### PR TITLE
nudb Tidying 

### PR DESCRIPTION
**Pull request by vinniefalco**
Not much to say

### CODE REVIEW

**Comment by rec** [comment]
Obviously correct.  :+1:

**Comment by ximinez** [comment]
As long as it builds, it must be correct. :+1:

**Comment by ximinez** [comment]
Still good.

**Comment by rec** [comment]
Oi!  Now it's not "Trivial" any more!

You can't keep adding stuff on the end of an approved code review...

**Comment by rec** [comment]
:+1:

**Comment by vinniefalco** [comment]
@rec Agree, that's why I updated the title

**Comment by rec** [comment]
(booted travis.  do we pay them?)

**Comment by ximinez** [comment]
Still looks ok. :+1:

**Comment by vinniefalco** [comment]
I'm finding more tidying necessary with nudb for the current work I'm doing, and since I prefer to squash these sort of things down I am going to close this pull request until I am certain that there is no more tidying to be done.

**Pull request closed without merging**
