### PR TITLE
WebSocket improvement medley:

### PR DESCRIPTION
**Pull request by vinniefalco**
These changes ensure the caller can block until the Application object can be fully prepared (especially listening sockets). Solves the problem where tests can attempt connections before the server sockets are ready. Fixes a deadlock on exit, and removes unused websocket04.

Reviewers: @ximinez @seelabs

### CODE REVIEW

**Comment by vinniefalco** [comment]
How the hell does removing 11,627 lines only increase coverage by 0.08%?!

**Comment by MarkusTeufelberger** [comment]
As far as I understand it, you are only measuring coverage for ripple and beast, not other code (like boost or rocksdb)

**Comment by seelabs** [comment]
:+1: Left some suggestions, but nothing that should hold this up.

**Comment by seelabs** [comment]
I created a commit to cherry pick that address my issues: https://github.com/seelabs/rippled/commit/876308e231c0a4b15771aebcde0961c66816082b (@ximinez please review). Ed's concerns are more difficult to address. I'll try to put together a commit for that as well.

**Comment by seelabs** [comment]
This commit should address the feedback in this review ( @ximinez - please review). https://github.com/seelabs/rippled/commit/1325ed57d747299150c5bcbff0cff5defeddf2b3

**Comment by ximinez** [comment]
@vinniefalco Needs rebase to address conflicts. I would guess that it's the vcxproj files.

**Comment by ximinez** [comment]
@seelabs 1325ed5 looks good, especially after squashing it into the previous. :+1:

**Comment by vinniefalco** [comment]
Merged Scott's changes

**Comment by nbougalis** [comment]
Merged as 07c4262392bffa31b199c2de3d6b7ef62c93a58f, 10a542198720c0abbf575086621c4212e684e78f and 77c0236cae270e82eedaef84d6a5f4198706712e.

**Pull request closed without merging**
