### PR TITLE
DeliverMin enable switch and precheck greater than dest amount

### PR DESCRIPTION
**Pull request by miguelportilla**
* Added in payment::precheck to return a tem if the deliverMin amount is larger than the destination amount.
* Removed precheck where sendMax greater than deliverMin.
* Modified unit test accordingly.

Revierwers: @JoelKatz @seelabs @nbougalis

### CODE REVIEW

**Comment by seelabs** [comment]
:+1:

**Comment by JoelKatz** [comment]
:+1:

**Comment by nbougalis** [comment]
:+1: from me

**Comment by vinniefalco** [comment]
Why are people putting a passed label on commits that are clearly wrong?

**Comment by vinniefalco** [comment]
Please fix this

**Comment by miguelportilla** [comment]
@vinniefalco Fixed commit message, rebased.

**Pull request closed without merging**
