### PR TITLE
nothing but fix the README title

### PR DESCRIPTION
**Pull request by lijiansong**
nothing, just fix the README

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
See #2120 which is a duplicate of this change.

**Comment by lijiansong** [comment]
@MarkusTeufelberger So, why don't you merge this formating fix?

**Comment by MarkusTeufelberger** [comment]
Because I'm not an employee of Ripple and I don't have merge rights here.

**Comment by lijiansong** [comment]
@MarkusTeufelberger okay, i see

**Comment by nbougalis** [comment]
Thanks for your contribution. This is a duplicate of #2120.

**Pull request closed without merging**
