### PR TITLE
Recompile only app.cpp if the GIT_COMMIT_ID changes.

### PR DESCRIPTION
**Pull request by rec**
Reviewers: @josh-ripple @vinniefalco

### CODE REVIEW

**Comment by josh-ripple** [comment]
This works for me. :+1:

**Comment by josh-ripple** [comment]
It would be nice if the burden were placed on a separate translation unit that compiles really quickly, but as is this is a huge improvement.

**Comment by vinniefalco** [comment]
@josh-ripple That change is in the pipe

**Comment by vinniefalco** [comment]
Total productivity loss due to excess recompilation: 1337 hours

**Comment by vinniefalco** [comment]
Merged

**Pull request closed without merging**
