### PR TITLE
Add jtx ledger advance.

### PR DESCRIPTION
**Pull request by ximinez**
jtx framework's version of common_ledger's `close_and_advance` function using a locally created last closed ledger variable. (Actually calls `close_and_advance` under the hood.)

Reviewers: @vinniefalco, @scottschurr (because I know he's working on something similar, and it would be good to integrate early.)

### CODE REVIEW

**Comment by scottschurr** [comment]
Looks nice and straightforward to me.  Hopefully I can use this when I convert the MultiSign unit tests to use the jtx framework.  :+1:.

**Comment by ximinez** [comment]
@vinniefalco @scottschurr Check out the pushed updates for working `Ledger const` changes!

**Comment by scottschurr** [comment]
Nicely done.  And the change from `shared_ptr<Ledger>` to `shared_ptr<Ledger const>` is being checked by the compiler.  So you can have high confidence you fixed all of the callers.  :+1:

**Comment by scottschurr** [comment]
Huh.  Nice follow through with the "x" branch.  And, as you said, it doesn't look too bad.  Since you're running experiments, it might be interesting to comment out the old (`Ledger (bool, Ledger&)`) constructor, do a build, and see how many places it is used.  If there are only a couple then it might be possible to remove the old constructor, possibly in a separate pull request.  Just a thought.

**Comment by ximinez** [comment]
@scottschurr So, obviously, if I comment out the non-const constructor, everything still builds fine, because it just silently converts. Not obviously, rippled still _seems_ to run fine with it that way, and was even able to sync. I didn't go further than that.

To find the usages, I made the non-const constructor private. That only gave 4 errors, and one of them was in the common_ledger tests. I pushed that change, but I'm not going to do anything more with it for now.

**Comment by scottschurr** [comment]
@ximinez Face palm about commenting out the non-`const` constructor.  Sorry I suggested that.  Making it private was, of course, the right approach.  Thanks for looking into it.  And, yeah, the investigation was definitely out of scope.  You and Vinnie can decide what you'd like to do with the "x" branch.  I'm good either way.

**Comment by vinniefalco** [comment]
As I said - pain.

**Comment by vinniefalco** [comment]
I don't think we're at the right point in time to muck with those `Ledger` ctors

**Pull request closed without merging**
