### PR TITLE
Add expiration to account_offers (RIPD-1049)

### PR DESCRIPTION
**Pull request by miguelportilla**

### CODE REVIEW

**Comment by ximinez** [comment]
Reviewers: @ximinez @scottschurr

**Comment by scottschurr** [comment]
Looks swell and straight forward to me.  Nice.
:+1:

**Comment by ximinez** [comment]
Good, safe-looking changes. It would be _better_ if it had a test. (Unfortunately, it would have to be an npm test, since the unit tests don't get to RPC handlers yet. There's already a `test/account_offers-test.js`.) :+1:

**Comment by scottschurr** [comment]
@ximinez Yup, I thought about testing when I looked at the change.  But I figured it was hopeless (right now) since we're in RPC land.  You have a good point about possibly extending an existing npm test.

**Pull request closed without merging**
