### PR TITLE
Remove tracking by node public key in Overlay

### PR DESCRIPTION
**Pull request by nbougalis**
@vinniefalco, @HowardHinnant

### CODE REVIEW

**Comment by vinniefalco** [comment]
:-1: If we change `Overlay` it should be to use `io_list`.

**Comment by nbougalis** [comment]
@vinniefalco: I don't disagree, but that is orthogonal to this PR. This doesn't change anything related to `io_list`. It just removes a map we're spending time and space maintaining but which serves no purpose. Also, it fixes a recursive call to a `std::mutex` in debug builds.

**Comment by HowardHinnant** [comment]
:+1:

**Comment by vinniefalco** [comment]
I guess I can live with it, if its squashed down.
:+1:

**Comment by nbougalis** [comment]
Merged as d321b446db882ea7b0dbaec4ed411f8b25e38401.

**Pull request closed without merging**
