### PR TITLE
Trivial: Add an explicit operator bool() to Json::Value.

### PR DESCRIPTION
**Pull request by rec**
@HowardHinnant @vinniefalco

### CODE REVIEW

**Comment by rec** [comment]
And this also shouldn't be much issue, we discussed this already.

**Comment by nbougalis** [comment]
I'm ok with this.

**Comment by rec** [comment]
OK, I've found an issue - not with this but with our JSON handling.

Usually when we return an empty error, we return `Json::nullValue` but sometimes we return an empty `Json::objectValue` like here:  https://github.com/ripple/rippled/blob/develop/src/ripple/rpc/impl/AccountFromString.cpp#L72

And sometimes when we test for empty we use `empty()` and sometimes we use `!` - which corresponds to `isNull`.

I propose that we re-define operator bool to be `! empty()`.  It's a little stronger, but it means that we can't ever have the issue of return an empty object (or array) and passing it back as if it were full.

**Comment by HowardHinnant** [comment]
Tom, I think you've uncovered an important ambiguity here!  If there are reasonably two interpretations for what `if (jv)` or `if (!jv)` mean, then when we use it throughout rippled we will constantly be having to check which meaning we chose (a year or two from now).

Instead I think we should remove the `operator!()` and *not* replace it with `operator bool()`.

I've just completed a survey of our current use of `operator!()` to investigate the cost of removing it.  It turns out we're not even using it!  Let's not start using it.  Let's get rid of it.

**Comment by vinniefalco** [comment]
Agree with @HowardHinnant

**Comment by vinniefalco** [comment]
Closing until this gets decided

**Pull request closed without merging**
