### PR TITLE
Properly fix race condition in ping_timer.

### PR DESCRIPTION
**Pull request by rec**
Reviewers: @HowardHinnant @nbougalis

### CODE REVIEW

**Comment by vinniefalco** [comment]
Suggested commit message:
```
Fix websocket ping timers:
* Use std::weak_ptr for WebSockets timer callbacks
* Disable pWebSockets pings if ping frequency is non-positive.
```

**Comment by HowardHinnant** [comment]
:+1:

**Comment by nbougalis** [comment]
:+1:

**Comment by rec** [comment]
Done.

**Pull request closed without merging**
