### PR TITLE
Fix RPC command logrotate so it doesn't fail.

### PR DESCRIPTION
**Pull request by rec**
Reviewers: @vinniefalco @mtrippled

### CODE REVIEW

**Comment by vinniefalco** [comment]
Obviously correct, just need to take the period off the end of "Set version to 0.27.0-b4."
:+1:

**Comment by mtrippled** [comment]
Has this been tested with the logrotate RPC call? What about the calls that would have failed previously for the same reason as logrotate?

**Comment by vinniefalco** [comment]
@mtrippled logrotate is fixed in this change set, and the other commit catches the other cases. do you agree?

**Comment by mtrippled** [comment]
:+1:

**Pull request merged**
