### PR TITLE
Update soci

### PR DESCRIPTION
**Pull request by vinniefalco**

### CODE REVIEW

**Comment by vinniefalco** [comment]
Needs check against gcc 5.x

**Comment by vinniefalco** [comment]
Reviewers: @miguelportilla @rec

**Comment by rec** [comment]
The second commit's name is inaccurate - you update a lot of things, not just `SConstruct`.

It bothers me that we have a commit that breaks the build, even though there's another commit to fix it right afterward - it breaks `git bisect` which we make a lot of use of in critical situations.  But I don't know a good way around it...

**Comment by vinniefalco** [comment]
@rec You are right about a commit that breaks the build. And I considered folding the changes into the Merge commit. But if I did that, you'd be looking at a diff with over 45,000 changed lines in 400 files, with my tiny set of changes mixed in there. So which do you want?

**Comment by rec** [comment]
As I said, "I don't know a good way around it."  I was asking if you had any ideas.

**Comment by vinniefalco** [comment]
Can't really think of anything to be honest, seems there's only two choices. I doubt we will need to bisect in between these commits, just think of them as a unit.

**Comment by rec** [comment]
The issue is that `git bisect` "randomly" lands between two commits and you have to then mark that commit as good or bad - which can be hard if you are on a commit that doesn't compile.  (And yes, I've run into this, but now I make sure each step compiles...)

We can work past it if it comes up, it's just a flaw in git.  

I actually came up with a way to fix this in the future (check in the new incompatible code into a new directory as one step;  change the SConstruct to point to the new directory and other fixes as one step) if we ever felt it was useful.

**Comment by vinniefalco** [comment]
@rec You can use `git bisect skip` or you can use `git reset` to manually direct the bisection.

**Comment by rec** [comment]
`git bisect skip` cool!

Don't forget to change the commit message... :-)

**Comment by seelabs** [comment]
I tested this against gcc 5.2. Build/unittest/npm/sync/stop. Unfortunately, gcc 5.2 repeatedly warns against the use of `auto_ptr` in boost, but that's unrelated to the soci update.

**Comment by HowardHinnant** [comment]
We could stick a `-Wno-depreated` (or however its spelled) in `SConstruct`.  I'd hate to block getting the important C++14 functionality we need over this issue.

**Comment by seelabs** [comment]
:+1:

**Comment by seelabs** [comment]
I tested defining `SOCI_CXX_C11`. all tests pass on linux. I think it's a good idea to define that. If you do, I'll test on the other platforms as well.

**Comment by vinniefalco** [comment]
Incorporated Scott's addition of `SOCI_CXX_C11` to SConstruct

**Comment by seelabs** [comment]
Tested `SOCI_CXX_C11` on all platforms. Still :+1:

**Comment by rec** [comment]
Does that fix the warnings?  Aces!

**Comment by seelabs** [comment]
@rec The `SOCI_CXX_C11` flag removes all the uses of `auto_ptr` except one, and I've never seen a warning for that one. So, yes this fixes the `auto_ptr` warnings in soci. (FYI, the one remaining use is a typedef in common-tests.h)

**Comment by miguelportilla** [comment]
I built the branch using Ubuntu 15.04 and gcc 5.2, got the following warnings:

In file included from src/beast/beast/module/core/core.unity.cpp:150:0,
                 from src/ripple/unity/beast.cpp:31:
src/beast/beast/module/core/text/LexicalCast.cpp: In instantiation of ‘void beast::LexicalCast_test::testThrowConvert(const string&, bool) [with T = long unsigned int; std::string = std::basic_string<char>]’:
src/beast/beast/module/core/text/LexicalCast.cpp:188:72:   required from here
src/beast/beast/module/core/text/LexicalCast.cpp:169:11: warning: variable ‘out’ set but not used [-Wunused-but-set-variable]
         T out;
           ^
src/beast/beast/module/core/text/LexicalCast.cpp: In instantiation of ‘void beast::LexicalCast_test::testThrowConvert(const string&, bool) [with T = unsigned int; std::string = std::basic_string<char>]’:
src/beast/beast/module/core/text/LexicalCast.cpp:191:61:   required from here
src/beast/beast/module/core/text/LexicalCast.cpp:169:11: warning: variable ‘out’ set but not used [-Wunused-but-set-variable]
src/beast/beast/module/core/text/LexicalCast.cpp: In instantiation of ‘void beast::LexicalCast_test::testThrowConvert(const string&, bool) [with T = int; std::string = std::basic_string<char>]’:
src/beast/beast/module/core/text/LexicalCast.cpp:196:61:   required from here
src/beast/beast/module/core/text/LexicalCast.cpp:169:11: warning: variable ‘out’ set but not used [-Wunused-but-set-variable]
src/beast/beast/module/core/text/LexicalCast.cpp: In instantiation of ‘void beast::LexicalCast_test::testThrowConvert(const string&, bool) [with T = short int; std::string = std::basic_string<char>]’:
src/beast/beast/module/core/text/LexicalCast.cpp:199:56:   required from here
src/beast/beast/module/core/text/LexicalCast.cpp:169:11: warning: variable ‘out’ set but not used [-Wunused-but-set-variable]

**Comment by vinniefalco** [comment]
@miguelportilla That's not a problem with the soci changes though?

**Comment by HowardHinnant** [comment]
Agreed that fixing this is beyond the scope of this patch.  But for the patch that enables updating to gcc-5.2, I think this can easily be fixed by adding to the test in src/beast/beast/module/core/text/LexicalCast.cpp:169:
````
(void)out;
````

**Comment by miguelportilla** [comment]
@HowardHinnant Building with 5.2 c++14 does not produce the warnings.

**Comment by miguelportilla** [comment]
The auto_ptr warnings seem to only appear with boost 1.58, they do not appear with 1.57

**Comment by seelabs** [comment]
I do not see the same warnings as @miguelportilla when compiling with gcc 5.2. A typical warning for me is: 

/home/swd/projs/common/boost_1_58_0/boost/get_pointer.hpp:27:40: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]

I talked with Mickey, and he is using boost 1.57 and I am using 1.58. That may be the difference.

**Comment by miguelportilla** [comment]
:+1: With the gcc 5.2  'upgrade', we may want to address the warnings or change our requirements.

**Comment by vinniefalco** [comment]
What's a fella gotta do to move us to gcc 5.x??

**Comment by rec** [comment]
so what's going on with this?  Can we mark it as approved?

**Comment by vinniefalco** [comment]
Its already marked Passed - what else did you want?

**Pull request closed without merging**
