### PR TITLE
Improve CMake find_boost compatibility:

### PR DESCRIPTION
**Pull request by ximinez**
* Put all the relevant calls together.
* Sensibly handle stage vs. stage64 lib directories.

### CODE REVIEW

**Comment by vinniefalco** [comment]
:+1:

**Comment by mellery451** [comment]
👍

**Comment by ximinez** [comment]
Removing "Passed" label because this breaks non-Windows builds.

**Comment by seelabs** [comment]
:+1:

**Comment by bachase** [comment]
Merged in f37aa1d6c8e049ebe6eeee9600fd805763c5e747

**Pull request closed without merging**
