### PR TITLE
Fix cmake clang build for sanitizers

### PR DESCRIPTION
**Pull request by mellery451**
This fixes the cmake clang sanitizer build. I've tried both sanitizers on mac and linux and all of them fail for me in some way, so I'm not adding either build to jenkins until I can resolve that.

### CODE REVIEW

**Comment by seelabs** [comment]
We should keep the SConstruct in sync too. Adding a conditional to line 448 should work.

**Comment by MarkusTeufelberger** [comment]
See also #2082 for ASAN/TSAN related problems

**Comment by scottschurr** [comment]
What's the correct way to enable one of the sanitizers?  I tried
```
cmake -Dtarget=${BUILD_TYPE} -DSANITIZE_ADDRESS=On -Dassert=true ../../..
```
as suggested here: https://github.com/arsenm/sanitizers-cmake.  Cmake responded:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    SANITIZE_ADDRESS
```
so apparently that's not it.

I have the same question for scons as well...

**Comment by mellery451** [comment]
@scottschurr ... for cmake, add this during generation `-Dsan=thread` or `-Dsan=address`.  For scons, I'm guessing it's `--sanitize=thread` or `--sanitize=address`, although I haven't tried it.

**Comment by seelabs** [comment]
In 0.90.0-b5

**Pull request closed without merging**
