### PR TITLE
Handle 64 bit integers in JSON by converting to string.

### PR DESCRIPTION
**Pull request by mtrippled**

### CODE REVIEW

**Comment by rec** [comment]
@nbougalis and I have discussed this problem in the past.

I'm initially very skeptical about this solution, even though it has the advantage of brevity.

It means that one integral type becomes a string but the rest stay integers.  "Round trips" - transformations C++ class -> json -> C++ or json -> C++ -> json - these are already broken, but this makes the brokenness permanent.

It means that two very similar seeming lines of code can result in Json with different types. It means that `(a == b) && (Json::Value(a) != Json::Value(b))` is now possible.

Is there an actual issue we need to solve?  If there isn't something pressing, my first thought would be to leave well enough alone.


IF we wanted to make this change, I have a counterproposal:

**Comment by rec** [comment]
My counterproposal:  

1. We should make the base integer type of Json::Value `std::int64_t`.

2. Existing code would be unaffected - in particular, `Json::Value::toInt()` and `Json::Value::toUInt()` would return exactly the same values they return now.

3. There would be two new constructors (uint64 and int64).

4. There would be _one_ new `ValueType` - `longValue`.

5. And this would require `asLong()` and `isLong()` and changes to `isIntegral()' and 'isNumeric()`

Note that in the 64-bit case I'm proposing we don't distinguish between signed and unsigned.  This means we do a poor job on numbers between `std::numeric_limits<std::int64_t>::max()` and `std::numeric_limits<std::uint64_t>::max()` but this isn't really an issue because:

* Right now we do a poor job on numbers above `std::numeric_limits<std::uint32_t>::max()` so we'd doing a lot better.

* If we're at the point where we really need that 64th bit to represent numbers, then we're screwed anyway.


Again, the big advantage to the counterproposal is that _old code is guaranteed to be unaffected_ but also that _we preserve round-trip_.

**Comment by mtrippled** [comment]
We're logging counters that have a tendency to exceed 32bits very rapidly, and I'll be logging more like this in instrumentation code that I'm working on. It is a workaround for something broken in JSON. Your counterproposal seems like a lot of work, and it's not going to solve the problem I'm facing, which is how to get JSON to represent 64bit integers.

**Comment by vinniefalco** [comment]
@mtrippled If this is for instrumentation purposes you could just use `std::to_string` instead of tinkering with the JSON library. It would be safer.

**Comment by rec** [comment]
It wouldn't be that much work!  :-)

**Pull request closed without merging**
