### PR TITLE
Fix htobe64 usage on musl by endian.h include

### PR DESCRIPTION
**Pull request by misery**

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
Combined with #2288 this might make rippled build on Alpine Linux or at least get it a whole lot closer to building there. Could someone from Ripple please take a look at it? @nbougalis etc.

**Comment by nbougalis** [comment]
@misery: I know this PR has languished here for a while, but I was going through it with the intent of merging it.

I'd prefer if we, instead, added the `#include` in `src/ripple/basics/ByteOrder.h`. Would you mind if I made that change to your PR, and then merged it?

**Comment by misery** [comment]
@nbougalis 
Thanks for your reply. Yeah, everything is fine for me. At least it is fixed... ;-)

**Comment by nbougalis** [comment]
Handled in #2511 by using Boost for endian conversions.

**Pull request closed without merging**
