### PR TITLE
Trivial: Add notes about Rippled's container classes.

### PR DESCRIPTION
**Pull request by rec**
Reviewers: @HowardHinnant @josh-ripple

### CODE REVIEW

**Comment by nbougalis** [comment]
I do not believe that this belongs in `README.md`. Perhaps `CODINGSTYLE.md` or somesuch document, but certainly not `README.md`.

**Comment by vinniefalco** [comment]
We need one giant README.md that contains this and everything else that is currently split up into different README.md files and we need the web app that compiles that markdown into a nice looking web page that looks like this: 
https://ripple.com/build/rippled-apis/

**Comment by rec** [comment]
We do have a lot of these usage notes spread in README.md already - it isn't a terrible place for coding information, being right in the first place a programmer might look.

I agree with Vinnie's idea that we should automatically exposed these READMEs.

**Comment by vinniefalco** [comment]
@nbougalis Imagine if we had one large README containing all the in-repo documentation. Imagine that we publish that README as a webpage at a URL similar to https://ripple.com/build/rippled-apis/ and including the index. Now we can just hand that to any new team member and they can get up to speed.

**Comment by josh-ripple** [comment]
:+1:

**Comment by nbougalis** [comment]
Merged as bb7d68b3b92e68f0438f9fc335c54a415b5d92b1

**Pull request closed without merging**
