### PR TITLE
Add noexcept qualifier to swaps and moves.

### PR DESCRIPTION
**Pull request by rec**
Reviewers: @HowardHinnant @scottschurr

### CODE REVIEW

**Comment by HowardHinnant** [comment]
This brings to my attention another concern, though it need not be handled in this P/R.  Wherever we have a member `swap`, and not a non-member `swap`, we risk the client attempting to call with non-member `swap` and accidentally picking up `std::swap(T&,T&)` which might be terribly inefficient.

We should make a sweep, and make sure that everything that we want to swap has a non-member `swap`.  Member `swap` is optional.  If we try to swap something with member swap we will either get the right function, or we will get a compile-time error if member swap does not exist.

**Comment by rec** [comment]
This is an excellent point and I'm going to do a tiny follow-up change to fix swap _just_ for `Json::Value` - the reason being that we make heavy use of this class and it constantly shows up in every profile.

**Comment by HowardHinnant** [comment]
:+1:

**Comment by scottschurr** [comment]
Just to reiterate, the justification here is that, yes we know that it is possible for these `swaps` or move constructors to throw, even though we're marking them as `noexcept`.  But we never expect to be able to recover if one of them *did* throw.  With this change we get faster execution speed in the non-throwing case, and a cleaner death (`std::terminate()`  is called) in the unlikely case where an exception passes through one of them.

If that understanding is correct then, yes, I'm on board.
:+1:

**Pull request closed without merging**
