### PR TITLE
Cleanups of LedgerEntrySet and TransactionEngine

### PR DESCRIPTION
**Pull request by nbougalis**
Reviews: @rec, @scottschurr

### CODE REVIEW

**Comment by rec** [comment]
Only quibbles really.

**Comment by scottschurr** [comment]
LGTM
:+1:

**Comment by scottschurr** [comment]
:+1: on the [FOLD]

**Comment by vinniefalco** [comment]
Needs a rebase

**Comment by nbougalis** [comment]
I have rebased and squashed the two commits into one. This is ready to go.

**Pull request closed without merging**
