### PR TITLE
Add detail::vectum (not public)

### PR DESCRIPTION
**Pull request by vinniefalco**
This class is not used anymore (its from nudb) but could come in handy later. Its not public (so it lives in detail/).

### CODE REVIEW

**Comment by rec** [comment]
Reviewers: @rec @josh-ripple

**Comment by vinniefalco** [comment]
The commit message is redundant, it should read "Add detail::vectum".

**Comment by rec** [comment]
Again, I feel `vectum` is a distracting name that doesn't say what it does.

In particular, since this code isn't used as it's checked in, it's going to sit in the codebase till someone figures out a use for it - which is much more likely to happen if it has a useful name.

The key idea is that each entry has padding that you can store stuff in and resize.  I'm partial to `PaddedVector` myself - or `PaddedEntryVector` - or `ResizableEntryVector`.

**Comment by josh-ripple** [comment]
I concur.

Though it does raise the question of where to put code that we might want to use later.  I think it's fine to leave it in Vinnie's repo, and the real issue is not where to store it but how to keep track of such mathoms.

**Comment by vinniefalco** [comment]
Good point about how to keep track of these things.

**Comment by vinniefalco** [comment]
We can revisit this when another need arises.

**Pull request closed without merging**
