### PR TITLE
Apply clang-tidy modernize-use-equals-default check

### PR DESCRIPTION
**Pull request by JoeLoser**
Requested reviewers:
@mellery451 @seelabs

### CODE REVIEW

**Comment by seelabs** [comment]
@JoeLoser Some of the changes are to out of class definitions. Except for unusual circumstances the ` = default` should be put in the class with the declaration. The "unusual circumstances" have to do with the destructor. A pure virtual destructor cannot be declared `default`, so those need to stay out of line. And if the destructor needs to see the definition of some forward declared class (i.e. the pimpl idiom with a `unique_ptr`) `default` won't work.

Here's a patch to cherry pick to move some of the `= default` to within the class: https://github.com/seelabs/rippled/commit/a2eae337053d9e853144a20d673b198f0b630a7a

Apart from that, this looks good to me. Thanks for the cleanup!

**Comment by seelabs** [comment]
This also needs to be rebased onto the latest develop when you get a chance.

**Comment by JoeLoser** [comment]
@seelabs good point about the out-of-line `= default` changes. Thanks for the cherry-pick. I took it and rebased too.

**Comment by JoeLoser** [comment]
@mellery451 I think we can remove the rebase label now.

**Comment by nbougalis** [comment]
Merged as 5f8037c55b0b268bbfbfc54997e152de4a6f9258

**Pull request closed without merging**
