### PR TITLE
More JLOG usage.

### PR DESCRIPTION
**Pull request by scottschurr**
This adds JLOG filtering to more logging statements.  These logging statements are not exercised by the unit tests, so they were not caught in the previous pass.  I found these by running the server on the network in a debugger.

Reviewers: @miguelportilla, @vinniefalco

### CODE REVIEW

**Comment by vinniefalco** [comment]
Seems okay, its a mechanical change of using `JLOG` with journals.
:+1:

**Comment by miguelportilla** [comment]
:+1:  :cow: :bell:

**Comment by kirkmicz** [comment]
Hi Good Dev..

Hi I've got this error "Overlay:DBG No [validation_manifest] section in config" in our rippled server.. may I know what is the reason of this issue.. THanks :)

**Comment by nbougalis** [comment]
@kirkmicz: it's nothing to worry about - it's a debug message informing you that there is no `validation_manifest` set on your server. The section is not required and your server will continue operating correctly.

Please note that GitHub pull requests are not the correct place for this kind of question. May I recommend posting future questions to the official ripple forum at https://forum.ripple.com/viewforum.php?f=2.

**Comment by kirkmicz** [comment]
Hi Sir @nbougalis thanks for that..

Yeah!, when I write the values for **ssl_key** and **ssl_cert** after I reload the rippled server it gives me that error. Is it normal?

**Comment by nbougalis** [comment]
@kirkmicz please ask your question on the official forum: https://forum.ripple.com/viewforum.php?f=2

**Pull request closed without merging**
