### PR TITLE
Remove using clauses of beast types in base_uint.h

### PR DESCRIPTION
**Pull request by JoeLoser**
Requested reviewers:
@seelabs @scottschurr

### CODE REVIEW

**Comment by scottschurr** [comment]
CI is started.  I'm about to head out for PTO for a week.  I just took a very quick glance at things and it looks fine to me.  If @seelabs is okay with it, I am too.

**Comment by JoeLoser** [comment]
Thanks, @scottschurr. Enjoy the vacation!

**Comment by scottschurr** [comment]
It's three non-unity builds that are failing.  I suspect there's a missing `#include` or two.

**Comment by seelabs** [comment]
Putting the `using` in the header defeats the purpose of namespaces; Given our unity builds, it's also a bad idea to put a `using` at any file scope. This is a good change.

It's interesting that the non-unity build failed with this change. The reason for that is another file has a `using beast::zero` that needs to be removed. In fact, there were two additional `using beast::zero;` that should be removed: one in `XRPAmount.h` and one in `IOUAmount.h`. Here's a commit to cherry pick that removes those `using`'s and adds the needed `beast::` namespace qualification where needed: https://github.com/seelabs/rippled/commit/b4efd03c15922ceea34ca122f2664fdbdddcd23c

**Comment by seelabs** [comment]
Given @scottschurr is on vacation, I'm removing him as a reviewer and adding @HowardHinnant

**Comment by JoeLoser** [comment]
@seelabs great catch with the other usages: your clean up far exceeded my original find. I'll look at it closely tonight, and cherry-pick. Thanks! :+1:

**Comment by JoeLoser** [comment]
@seelabs LGTM, I cherry-picked. I did notice you did not go to the extent of doing `#include <ripple/beast/utility/Zero.h>` in all the files you touched.  Do you think we should go sprinkle that in all of those files? The non-unity build passed just fine locally for me, so I suspect we're _okay_, but in general, I think we both prefer each header to be able to stand alone without dependencies on other headers.

**Comment by nbougalis** [comment]
I've folded @seelabs' commit into b5 (#2629).

**Comment by nbougalis** [comment]
Merged with #2629 as 79d819584f5d92d569e4b32524b968b26200bbf8

**Pull request closed without merging**
