### PR TITLE
[TRIVIAL] Don't include zero traffic levels

### PR DESCRIPTION
**Pull request by JoelKatz**
This fixes asserts in debug builds upon receiving the "print" command.

### CODE REVIEW

**Comment by nbougalis** [comment]
Weird clang failure... I don't see how this patch could trigger it.

**Comment by HowardHinnant** [comment]
I tested on OS X and didn't see any failures.

**Comment by seelabs** [comment]
I tested on clang 3.7 on linux and didn't see any failures.

**Comment by nbougalis** [comment]
Merged as 3c496b07f9dace1657b29faee354ae09cfaad82c.

**Pull request closed without merging**
