### PR TITLE
Replaces StringPairArray with Section in Config.

### PR DESCRIPTION
**Pull request by seelabs**
@miguelportilla @scottschurr

### CODE REVIEW

**Comment by vinniefalco** [comment]
Nice work

**Comment by nbougalis** [comment]
Very nice!

**Comment by miguelportilla** [comment]
Nice work, Scott!

LGTM :+1:

**Comment by scottschurr** [comment]
Looks swell to me.
:+1:

**Comment by seelabs** [comment]
@scottschurr @miguelportilla I added a commit that addresses the PR comments. The `maybe_get` function is new and definitely needs a review.

**Comment by scottschurr** [comment]
The latest commit looks correct to me.  I have some style suggestions, but no reasons to hold up the request.
:+1:

**Comment by miguelportilla** [comment]
Same here, latest commit looks correct to me. :+1:

**Comment by scottschurr** [comment]
:+1:
Looks great.  Thanks for your patience with the review process.

**Pull request closed without merging**
