### PR TITLE
New RPC/Utility.h contains declarations for Utility.cpp.

### PR DESCRIPTION
**Pull request by rec**
Extracted from an impending pull request...

### CODE REVIEW

**Comment by rec** [comment]
@mtrippled @miguelportilla 

Basically trivial.

**Comment by mtrippled** [comment]
:+1:

**Comment by miguelportilla** [comment]
:+1:

**Comment by vinniefalco** [comment]
Commit message is wrong, should read "declaration"

**Comment by miguelportilla** [comment]
warning C4099: 'ripple::RPC::Coroutine::Impl'

**Comment by rec** [comment]
The compile warning isn't connected to this change - it's been there for a few days and I already have a pull request to deal with it!  :-)

**Comment by rec** [comment]
(Pushed a new commit with a better message....)

**Comment by vinniefalco** [comment]
This doesn't really help anything yet why can't we include it in another future commit that uses it?

**Comment by rec** [comment]
I pulled it out of a longer, unrelated change because it got in the way.  I don't actually have anything in line to use it.

**Pull request closed without merging**
