### PR TITLE
Remove stray debugging line from nudb win32_file

### PR DESCRIPTION
**Pull request by vinniefalco**

### CODE REVIEW

**Comment by JoelKatz** [comment]
:+1:

**Comment by ximinez** [comment]
I'm surprised we got this far without problems, but nothing seems amiss.

In Windows, rippled builds and tests pass. Runs, just barely syncs with nudb, and eventually stops.

On Linux builds, rippled builds and test pass. Runs, syncs with nudb with no problems, and stops.

**Comment by vinniefalco** [comment]
@ximinez The stray line should not cause a problem, it just asks for write permission all the time even when its not needed (read permission is always granted).

**Comment by ximinez** [comment]
@vinniefalco Makes sense.

**Pull request closed without merging**
