### PR TITLE
Update Travis to bionic

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by nbougalis** [comment]
Thanks for your contribution. Other than testing on the "latest and greatest" is there a particular benefit we derive from this?

**Comment by gliptak** [comment]
While xenial is nearing EOL https://wiki.ubuntu.com/Releases at this time PR targets keeping up.

**Comment by carlhua** [comment]
@manojsdoshi  can we make sure that our package building is also upgraded - namely the ubuntu docker image?

**Comment by gliptak** [comment]
https://github.com/ripple/rippled/blob/b54d672710227e494dd774c3ca3a4bc0a9976233/Builds/containers/ubuntu-builder/Dockerfile#L1 ? Am I to add to this PR?

**Comment by carlhua** [comment]
> https://github.com/ripple/rippled/blob/b54d672710227e494dd774c3ca3a4bc0a9976233/Builds/containers/ubuntu-builder/Dockerfile#L1
> 
> ? Am I to add to this PR?

Yep!

**Comment by gliptak** [comment]
@carlhua updated

**Pull request closed without merging**
