### PR TITLE
Fix unsafe iterator dereference in PeerFinder

### PR DESCRIPTION
**Pull request by vinniefalco**
Found by one of our users:
https://forum.ripple.com/viewtopic.php?f=2&t=9129&p=61199#p61199

### CODE REVIEW

**Comment by seelabs** [comment]
:+1: Obviously correct.

**Comment by scottschurr** [comment]
:+1:
Looks right to me.

**Comment by nbougalis** [comment]
I am certain we fixed this very thing once before!

**Comment by vinniefalco** [comment]
We definitely did not

**Pull request closed without merging**
