### PR TITLE
Update http-parser

### PR DESCRIPTION
**Pull request by vinniefalco**
Brings the http parser up to the tip of the upstream master branch

### CODE REVIEW

**Comment by seelabs** [comment]
Both gcc and clang warn about unused enum in a switch statement:

src/beast/beast/http/impl/joyent_parser.cpp:64:12: warning: enumeration value ‘HTTP_BIND’ not handled in switch [-Wswitch]
     switch (m)
            ^
src/beast/beast/http/impl/joyent_parser.cpp:64:12: warning: enumeration value ‘HTTP_REBIND’ not handled in switch [-Wswitch]
src/beast/beast/http/impl/joyent_parser.cpp:64:12: warning: enumeration value ‘HTTP_UNBIND’ not handled in switch [-Wswitch]
src/beast/beast/http/impl/joyent_parser.cpp:64:12: warning: enumeration value ‘HTTP_ACL’ not handled in switch [-Wswitch]
src/beast/beast/http/impl/joyent_parser.cpp:64:12: warning: enumeration value ‘HTTP_MKCALENDAR’ not handled in switch [-Wswitch]
src/beast/beast/http/impl/joyent_parser.cpp:64:12: warning: enumeration value ‘HTTP_LINK’ not handled in switch [-Wswitch]
src/beast/beast/http/impl/joyent_parser.cpp:64:12: warning: enumeration value ‘HTTP_UNLINK’ not handled in switch [-Wswitch]

**Comment by seelabs** [comment]
If you're OK with modifying that file,this commit resolves the warnings: https://github.com/seelabs/rippled/commit/6b2e3a4f9938ef02b4412537d86e3531e1f8222e

**Comment by vinniefalco** [comment]
Added the missing case labels

**Comment by seelabs** [comment]
:+1:

**Comment by miguelportilla** [comment]
:+1:

**Pull request merged**
