### PR TITLE
Exit immediately in Resource::ManagerImp::~ManagerImp

### PR DESCRIPTION
**Pull request by vinniefalco**
Speeds up unit tests by 1900%!

Reviewers: @JoelKatz @scottschurr

### CODE REVIEW

**Comment by scottschurr** [comment]
The change looks good to me.  Sorry I introduced the problem in the first place.

There is a conflict with the `#include <beast/cxx14/memory.h>` changing to `#include <memory>`.  that looks like the only conflict.

So :+1: from me once the conflict is resolved.

**Comment by vinniefalco** [comment]
@scottschurr Guess we don't need `beast/Thread.h` either.. LOL. I fixed up the includes.

**Comment by scottschurr** [comment]
Looks swell to me.  I don't know why github is still griping about a conflict that needs to be resolved...

**Comment by vinniefalco** [comment]
@scottschurr And yet, when I rebased I got a conflict! Fixed..

**Comment by JoelKatz** [comment]
:+1:

**Comment by scottschurr** [comment]
:+1:

**Pull request closed without merging**
