### PR TITLE
Peer load tracking and master lock decongestion

### PR DESCRIPTION
**Pull request by JoelKatz**
Changes to accurately track and report peer load and decongest the master lock.

Reviewers needed.

### CODE REVIEW

**Comment by HowardHinnant** [comment]
This suggestion is unrelated to this PR except that it is working the same neighborhood.  But I strongly recommend, either in this PR, or a separate one, that in PeerImp.h, lines 130-131 we change the `std::list` to `std::deque`.  I've checked all usage of these containers in PeerImp.cpp and `std::deque` will do this queue job a lot faster.  `std::list` is doing an allocation/deallocation for each push/pop.  `std::deque` will quickly reach a steady state after which it will no longer allocate/deallocate.

Demo: https://ideone.com/j1oSge

**Comment by HowardHinnant** [comment]
I stumbled across another inefficiency that is "in the neighborhood".  In Application.h the function `masterLock` returns a `std::unique_ptr<std::unique_lock<std::recursive_mutex>>`.  There is no reason to use a `unique_ptr` here.  It is a needless heap allocation/deallocation.  `unique_lock` is just as movable as `unique_ptr`.  This function should return `std::unique_lock<std::recursive_mutex>`, either in this PR, or a separate PR.

**Comment by mtrippled** [comment]
Benchmarking shows no detectable improvement. Ledger close intervals destabilize after a few minutes of 130 transactions per second. It means that the bottleneck encountered in benchmarking is not addressed by this fix, but it might help in other regards. But until the particular bottleneck exposed in macro-benchmarking is fixed, further improvements from this or other enhancements are not measurable.

**Comment by HowardHinnant** [comment]
:+1:

**Comment by miguelportilla** [comment]
:+1:

**Comment by nbougalis** [comment]
Merged as 60a7abcef62e8e8f9bbd05c2337931cbde48e42e, 8de1b20bb5b53f7b358e9c823619a91b42cedfe9, 2f32910bef56406e222a734ffb6cb2e8d848de6b and 1c2f5d60a54bac6dc83aac9e80af71846279b249.

**Pull request closed without merging**
