### PR TITLE
Use ws2 as default in unit tests

### PR DESCRIPTION
**Pull request by miguelportilla**

### CODE REVIEW

**Comment by bachase** [comment]
👍

**Comment by scottschurr** [comment]
Interesting.  I did a release unity build on OS X with your code.  The unit tests all pass, but in the middle of the unit tests there was this, say, 20 second pause where I saw this:
```
ripple.app.RobustTransaction
ERR:Application Waiting for 'ServerHandler' to stop
ERR:Application Waiting for 'ServerHandler' to stop
ripple.app.SHAMapStore clearPrior
```
The tests all passed, but I thought you might be interested in the pause.  The pause is at least somewhat repeatable.  I ran the unit test three consecutive times.  It paused all three times. I timed the pause on the third run at approximately 90 seconds.

**Comment by vinniefalco** [comment]
Looks like a client did not disconnect, and the server is timing out

**Comment by miguelportilla** [comment]
@scottschurr Thanks for noticing that! The problem was some tests were not unsubscribing from streams. I pushed a fix.

**Comment by scottschurr** [comment]
:+1: Elegant solution to making WS2Client usage more wide spread.  The fixes to RobustTransaction_test.cpp seem to have done the job.

**Comment by bachase** [comment]
Merged in bf642404c72213cc73b725ab7dae37e5afda93eb

**Pull request closed without merging**
