### PR TITLE
Get rid of compilation warnings in Ledger.test.cpp

### PR DESCRIPTION
**Pull request by rec**
Reviewers: @HowardHinnant @ximinez

### CODE REVIEW

**Comment by vinniefalco** [comment]
Obviously correct, this doesn't need reviewers
:+1:

**Comment by vinniefalco** [comment]
On second thought, the commit message could be more sterile.
Suggest: "Fix compilation warnings."

**Comment by HowardHinnant** [comment]
> Obviously correct, this doesn't need reviewers
Famous last words. :-)
Nevertheless, :+1:

**Comment by rec** [comment]
Changed the message!

**Comment by ximinez** [comment]
:+1:

**Comment by vinniefalco** [comment]
Merged

**Pull request closed without merging**
