### PR TITLE
Port the "Default Ripple" changes from 0.27.3 into 0.28.0

### PR DESCRIPTION
**Pull request by nbougalis**
This is functionally identical to the code that shipped in 0.27.3-sp1.

### CODE REVIEW

**Comment by rec** [comment]
:+1: from me, but I'd like to see the original reviewers comment.

Summary:  this code is supposedly the same as what you reviewed, except that there was some merge fanciness there...

Nik said:
>  Two different versions of assert-diff in package.json.
> And, as a result of the merge, some fields in a tx that had been removed from newer versions of rippled.

**Comment by nbougalis** [comment]
Ping @JoelKatz and @sublimator. Can you quickly eyeball this to ensure that my conflict resolution meets your approval.

**Comment by sublimator** [comment]
The commit I added looks right. Haven't looked in detail at the rest.

**Comment by rec** [comment]
@JoelKatz - just a few moments of your time to check that this is correct.  All you need to do is conflict resolution...

**Comment by nbougalis** [comment]
I am adding the "Passed" label on this. The code is in `release` already and only trivial confict resolution had to be performed.

**Pull request closed without merging**
