### PR TITLE
Revert "Asynchronously write batches to NuDB. (#4503)"

### PR DESCRIPTION
**Pull request by mtrippled**
This reverts commit 1d9db1bfdd84e980e44e2f521990eaca42633d5e.

## High Level Overview of Change
Revert code that introduces problems associated with online deletion.

### Context of Change
The bug was introduced in PR #4503, which causes writes to block during online deletion. In turn, this delays persisting records to disk during consensus, which causes node desyncs.

### Type of Change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change that only restructures code)
- [ ] Tests (you added tests for code that already exists, or your new feature included in this PR)
- [ ] Documentation update
- [ ] Chore (no impact to binary, e.g. `.gitignore`, formatting, dropping support for older tooling)
- [ ] Release

### API Impact

- [ ] Public API: New feature (new methods and/or new fields)
- [ ] Public API: Breaking change (in general, breaking changes should only impact the next api_version)
- [ ] `libxrpl` change (any change that may affect `libxrpl` or dependents of `libxrpl`)
- [ ] Peer protocol change (must be backward compatible or bump the peer protocol version)

Run online deletion as normal. It should stay stable, and revert to behavior from 1.12 and previous.

## Future Tasks

If we proceed with this revert, there will there be no reason to consider #4762.

Closes #4762

### CODE REVIEW

**Comment by intelliot** [comment]
QA will check to see how this can be tested

**Review by ximinez — APPROVED** [review]
Clean revert.

**Comment by intelliot** [comment]
Internal tracker: RPFC-80

**Review by thejohnfreeman — APPROVED** [review]

**Comment by intelliot** [comment]
`Perf SignedOff`: "I think 4882 is good to go"

**Pull request merged**
