### PR TITLE
Convert PathRequest to use std::chrono (RIPD-1069)

### PR DESCRIPTION
**Pull request by miguelportilla**
Reviewers: @HowardHinnant @scottschurr

### CODE REVIEW

**Comment by HowardHinnant** [comment]
Overall looks good!  Just a few minor comments.

**Comment by miguelportilla** [comment]
Thanks Howard!

**Comment by HowardHinnant** [comment]
:+1:

**Comment by scottschurr** [comment]
Looks good to me.  :+1:

**Comment by nbougalis** [comment]
Merged as b69f0356ec7f957d1f99a3c3a7436b4988d4e10a

**Pull request closed without merging**
