### PR TITLE
Delete AddWallet.cpp again

### PR DESCRIPTION
**Pull request by josh-ripple**
I'm pretty sure this isn't supposed to be here.

### CODE REVIEW

**Comment by nbougalis** [comment]
It's not supposed to be - thanks for catching that. Obviously correct, :+1:

**Comment by rec** [comment]
:+1:

**Comment by nbougalis** [comment]
This needs to get included in 0.28.

**Comment by vinniefalco** [comment]
@nbougalis Are you sure? Its just a loose source file not included in any unity.

**Comment by nbougalis** [comment]
Then it should a very non-controversial merge!

**Comment by vinniefalco** [comment]
That is true

**Comment by vinniefalco** [comment]
Commit message should read
"Remove unused source file"

**Pull request closed without merging**
