### PR TITLE
Prefer std::array over C-style array

### PR DESCRIPTION
**Pull request by JoeLoser**

### CODE REVIEW

**Comment by seelabs** [comment]
Some of this code uses an iterator to get a pointer to the data (e.g. `pointer data() { return reinterpret_cast<pointer>(pn.begin()); }`)

I'd rather not use the iterator as I don't think it's guaranteed to be a pointer to the data (someone might define a bounds checking debug iterator, for example). We could use either `&pn[0]` or `pn.data()`; either would be fine with me.

**Comment by JoeLoser** [comment]
@seelabs sorry for the slow response - I blame CppNow :P

I'll take a look more closely at this neighborhood of code and take your feedback into account when I get some time tonight or tomorrow. Thanks!

**Comment by seelabs** [comment]
@JoeLoser You're at CppNow!?! Nice! We often have people from ripple at these conferences, but not this year. No rush on addressing the feedback, whenever you get around to it is great. If you don't have time just let me know and I'm happy to do it too, but I figured you'd want to do it.

**Comment by JoeLoser** [comment]
@seelabs took the CppNow conversation to email, but I just force pushed some changes in response to your code feedback earlier.  Please let me know if I didn't interpret your comment correctly.  I agree that it surely didn't follow the element of least surprise in handing back `pn.begin()` instead of `pn.data()`.

**Comment by seelabs** [comment]
Closed and reopened as https://github.com/ripple/rippled/pull/2514

**Pull request closed without merging**
