### PR TITLE
Correct boolean handling for Json::Value (RIPD-941).

### PR DESCRIPTION
**Pull request by rec**
@HowardHinnant @JoelKatz @nbougalis 

Howard brought up an interesting inconsistency in an earlier review, and this is the response.

### CODE REVIEW

**Comment by rec** [comment]
(rebased against develop).

**Comment by HowardHinnant** [comment]
:+1:

**Comment by rec** [comment]
Force pushed with the nit scratched.

**Comment by nbougalis** [comment]
:+1:

**Comment by rec** [comment]
I squashed this down and it's ready to go!

**Comment by nbougalis** [comment]
:+1: needs rebase.

**Pull request closed without merging**
