### PR TITLE
Convert throws and catch alls (RIPD-1046)

### PR DESCRIPTION
**Pull request by miguelportilla**
* Convert all throws to use Throw which guarantees all exceptions will be std::exception derived. This also allows project auditing of any throw.
* Convert catch alls to catch std:exceptions to avoid errors with exceptions thrown within coroutines.

Reviewers: @HowardHinnant @nbougalis

### CODE REVIEW

**Comment by HowardHinnant** [comment]
We have one violation here:  https://github.com/miguelportilla/rippled/blob/develop/src/ripple/rpc/tests/Status.test.cpp#L186
It isn't clear to me if we want to fix this by having `Status` derive from `std::exception` or by having the test throw something else.

**Comment by miguelportilla** [comment]
@HowardHinnant I wasn't sure of the best way to handle that case and since its a unit test I left it but I'll reexamine it today.

**Comment by HowardHinnant** [comment]
:+1:

**Comment by nbougalis** [comment]
:+1:

**Comment by nbougalis** [comment]
Merged as 880f354b9046f15e2fefb3c8c80e679a90b8f463

**Pull request closed without merging**
