### PR TITLE
Remove broken flags --rpc_ip and --rpc_port. (RIPD-810)

### PR DESCRIPTION
**Pull request by rec**
Reviewers: 
  @josh-ripple 
  @nbougalis 

Fixing it up would have been quite a lot of work - I started...

We need a new system anyway - and no one has actually complained about this (the bug was filed when we realized that these flags were advertised but didn't actually work...)

https://ripplelabs.atlassian.net/browse/RIPD-810

### CODE REVIEW

**Comment by vinniefalco** [comment]
Obviously correct...

**Comment by sublimator** [comment]
We could fix this, by patching the `config` passed to `setup_ServerHandler` with command line values, however it's likely we are going to jettison the client in rippled at some point in the name of simplicity? Anyway, instead of merely removing this, we could make it report that the feature has been removed (while still removing it from the help table) ?

People did actually use this. It's my guess that it's because this is something that isn't "omg, my money bled away" we haven't heard much of it. 

(A related issue, is that setup_Client doesn't search for the most suitable (admin allowing) port to connect to)

**Comment by vinniefalco** [comment]
@sublimator Good points although there's no way to keep it out of the table yet still parse it (using boost program options). A more intelligent `setup_Client` is of course welcomed.

**Comment by sublimator** [comment]
I meant more the --help table (which is currently manually maintained)

**Comment by vinniefalco** [comment]
Oh...thats a good idea. We should add a comment in the help table about the switches being removed.

**Comment by nbougalis** [comment]
Obviously correct :+1:

I don't this that this needs two reviews, so I'll mark it as "Passed"

**Comment by vinniefalco** [comment]
@nbougalis What about editing the help table?

**Comment by nbougalis** [comment]
I don't think that requires or prevents a sign off

**Comment by sublimator** [comment]
What about we remove all the rippled rpc client stuff, and replace it with a node script?

**Comment by vinniefalco** [comment]
@sublimator I'd prefer Python since that doesn't require installing extra tools.

**Comment by sublimator** [comment]
Fair

**Comment by rec** [comment]
I'm itching to write Python, so file a JIRA and assign it to me.

**Comment by nbougalis** [comment]
I'd be _all_ for that. Not only would it remove code from rippled, but a python-based RPC client could be more full-featured (e.g. allow connecting to multiple servers, each with its own configuration) but be more flexible too.

**Comment by vinniefalco** [comment]
https://ripplelabs.atlassian.net/browse/RIPD-848

**Comment by nbougalis** [comment]
Merged as 2b04056

**Pull request closed without merging**
