### PR TITLE
0.30.1-b11

### PR DESCRIPTION
**Pull request by nbougalis**

### CODE REVIEW

**Comment by scottschurr** [comment]
Travis reports an interesting unit test failure on clang.debug.nounity:
```
ripple.app.SHAMapStore automatic online_delete
#24 failed: unhandled exception: write: Broken pipe
```

**Comment by vinniefalco** [comment]
@scottschurr Hmm I wonder if that is the result of logging

**Comment by scottschurr** [comment]
@vinniefalco: possibly?  But I'm unsure what the mechanism would be.

**Comment by vinniefalco** [comment]
Sorry, no. The exception would come from `JSONRPCClient` which uses synchronous asio sockets without error checking (the API throws exceptions).

**Comment by scottschurr** [comment]
I'll try running the unit tests a few times on my local machine with only one core enabled to see whether I can reproduce it

**Comment by scottschurr** [comment]
I throttled my local OS X machine down to a single core and ran the unit test suite on a debug build 20 times in a row.  No failures.  I think we'll just have to be watchful on failures of this nature for a while.

**Comment by nbougalis** [comment]
Superseded.

**Pull request closed without merging**
