### PR TITLE
Avoid comparisons that will never succeed

### PR DESCRIPTION
**Pull request by nbougalis**
Reviews: @josh-ripple, @rec

### CODE REVIEW

**Comment by josh-ripple** [comment]
This is approaching the issue too narrowly.  I'd rather see the string class set itself to an empty string in the default constructor, and have non-null storage be an invariant. :-1:

**Comment by nbougalis** [comment]
@josh-ripple it's an error because you cannot pass `nullptr`as an argument to `strcmp`.

To your second point, I agree that this could be solved by having `CZString` initialize the `cstr_` member to some 'safe' value, but that would change the semantics of `CZString` and would require a more extensive change than I'm prepared to make at this point.

**Comment by josh-ripple** [comment]
Clearly, passing `nullptr` to `strcmp()` is wrong.  Can you explain the desired semantics of `operator<()` and `operator==()` with respect to values where one or both might be null?

**Comment by nbougalis** [comment]
Given that the semantics are currently: "crash" I think that returning `false` is sensible.

**Comment by josh-ripple** [comment]
So, given `CZString null; CZString nonnull("foo", noDuplication);`, return `false` for both `null < nonnull` _and_ `nonnull < null`?  That isn't going to work when using `CZString` as a key in `std::map<>`.

**Comment by rec** [comment]
This can be fixed.  Clearly `nullptr` is `!=` to any nonnull string.  As for `operator<`, we already have `""`, which is less than any other string.  If `nullptr` is less than `""` we have a consistent order and the logic is easy to apply.

**Comment by rec** [comment]
Ping!

**Comment by rec** [comment]
I'm going to close this.  It's not entirely obvious what to do and the risks involved in dealing with this critical area are too great.  Feel free to reopen if you have a solution!  :-)

**Pull request closed without merging**
