### PR TITLE
Improvements to signal handling.

### PR DESCRIPTION
**Pull request by rec**
Reviewers: @nbougalis @vinniefalco 

This doesn't at all fix the deadlock but I spun it out from that branch.

### CODE REVIEW

**Comment by josh-ripple** [comment]
Nice work. :+1:

**Comment by rec** [comment]
I got rid of the two one-line changes involving `SIGTERM` and kept the cleanup.

**Comment by rec** [comment]
Is this good to go?

**Comment by vinniefalco** [comment]
Yeah, I guess its good to go :+1: But why did we touch these files? It seems very little gain.

**Comment by rec** [comment]
I agree - this didn't actually solve the issue it set out to solve.

If you recall, in trying to diagnose the deadlocking on SIGTERM, I added a handler for it - which was in this change.  

But discussions during the code review convinced me that that was a bad idea to actually put this in.

It's along the line of "some cleanup, then a business change".  In this case, I reverted the business logic change and kept the cleanup.

**Comment by nbougalis** [comment]
Merged as d575cd5

**Pull request closed without merging**
