### PR TITLE
Trivial: remove deprecated "accepted" parameter and fix compilation warnings.

### PR DESCRIPTION
**Pull request by rec**
Two unrelated small changes in two commits.

@ximinez @miguelportilla

### CODE REVIEW

**Comment by rec** [comment]
See new version that only changes the SConstruct.

**Comment by ximinez** [comment]
:-1: Breaks scons build in Windows.

**Comment by rec** [comment]
Missed this till now!  :-)

On it... but, I thought that circleci was our integration tool that detected Windows build breakage?  and... 

OK - so I don't understand, clearly, how our Windows build works.  Do we have TWO windows builds?  One using vcxproj and one not?

Anyway, I don't need the answer to fix this.  :-D

**Comment by nbougalis** [comment]
@rec VS projects can be built from the command line, using either `msbuild` or `devenv` and that's what `scons` does.

**Comment by vinniefalco** [comment]
@rec Yes there are two builds one that uses `scons` and invokes the compiler from the command line. And then there's a build through the vcxproj (which, our `scons` produces). In theory they produce identical results, since the settings in the vcxproj are generated from the switches that would be passed to the command line.

**Comment by rec** [comment]
All right - this likely fixes the windows issue, and compiles on this mac anyway.  (Wish I'd debugged having an ssh open to my home machine before leaving...)

Overall, once I get back I'm going to rebase the big SConstruct changes and then send them for review even though they aren't finished (they still work... :-D)

**Comment by ximinez** [comment]
@rec AppVeyor checks the Windows build. Unfortunately, it's not hooked in to Github AFAIK. I'm also not sure if it uses scons or the vcxproj to do the build.

**Comment by rec** [comment]
I have AppVeyor already set up:  https://ci.appveyor.com/project/sublimator/rippled-179/build/1.0.1549

But it reports a spurious error, seemingly.  Actually, I misread initially, it does compile but then the npm tests fail...?

**Comment by ximinez** [comment]
That error is very strange looking. I don't think the npm tests even started. It looks more like the unit tests reported success, but had a failing exit code. I'm not seeing the same problem so far on my end, so I vote for this being an AppVeyor issue.

**Comment by rec** [comment]
let me then squash this change down...!

**Comment by ximinez** [comment]
Builds and tests pass in Windows using scons. :+1: 

I'm going to mark this as Passed again, since it had the flag before I found the Windows problem.

**Pull request closed without merging**
