### PR TITLE
Add RPC metrics (RIPD-705)

### PR DESCRIPTION
**Pull request by miguelportilla**
Add metrics to record the number of RPC requests received. Record the number of
node store fetches performed per request. Additionally record the byte size of
each request response and measure the response time of each request in
milliseconds.

A new class, ScopedMetrics, uses the Boost Thead Local Storage mechanism to
efficiently record NodeStore metrics within the same thread.

Reviewers: @vinniefalco , @rec

### CODE REVIEW

**Comment by rec** [comment]
Can we mark this as "Passed"?  Or shelve this?

**Comment by vinniefalco** [comment]
:+1:

**Comment by vinniefalco** [comment]
This has horrible merge conflicts

**Comment by nbougalis** [comment]
Merged as 0e4de42be87ddce5ad9dcdd1f4438acc100d11b5

**Pull request closed without merging**
