### PR TITLE
Add virtual destructor to Logs

### PR DESCRIPTION
**Pull request by seelabs**
This is a trivial PR to add a virtual destructor to Logs.

@scottschurr @HowardHinnant

### CODE REVIEW

**Comment by HowardHinnant** [comment]
:+1:

**Comment by scottschurr** [comment]
:+1:

This error would have been caught earlier if the derived class had declared the destructor as override.  So I'll suggest, for extra credit, you might include the following around line 134 of Env.cpp:
```
~SuiteLogs() override = default;
```
But the change you've made is good.  Thanks for finding, and fixing, the problem.

**Comment by seelabs** [comment]
@scottschurr  Love it. I didn't expect any comments on this and that's actually great feedback. Thanks! Will do.

**Comment by nbougalis** [comment]
Merged as 61e6e5694c59159da81f61f99001c09d93deebab

**Pull request closed without merging**
