### PR TITLE
Test on CircleCI with Boost 1.60:

### PR DESCRIPTION
**Pull request by wilsonianb**
* Run on Ubuntu 14.04
* Do not build Docker images

### CODE REVIEW

**Comment by wilsonianb** [comment]
This requires anyone testing with CircleCI to enable the Ubuntu 14.04 Trusty container experimental setting for their rippled repo on CircleCI.

**Comment by ximinez** [comment]
Is there any way we could configure the OS in `circle.yml` instead of server-side? Otherwise, there's not much to test here. The CircleCI build succeeded and used Boost 1.60, so :+1:

**Comment by wilsonianb** [comment]
As far as I can tell, you can currently only configure builds to use Ubuntu 14.04 in the project settings at https://circleci.com/gh/ripple/rippled/edit#experimental
https://discuss.circleci.com/t/when-are-we-going-to-get-ubuntu-14-04/331/4

**Comment by ximinez** [comment]
Whoever builds the `develop` candidate containing this change will need to ensure they flip this switch for rippled _before_ they do the final push.

**Comment by seelabs** [comment]
:+1: I tried to figure out how to turn on trusty in the yml file. They do support an `experimental` section, but I can't find the right variable to set.

**Comment by nbougalis** [comment]
Merged as 3a45ef0e65c42977ad45bfdfe4e723b070f0a202

**Pull request closed without merging**
