### PR TITLE
Ignore error on socket shutdown

### PR DESCRIPTION
**Pull request by vinniefalco**
Silences an annoying spurious error.

Reviewers: @scottschurr @nbougalis

### CODE REVIEW

**Comment by scottschurr** [comment]
:+1:  I've tested this fix and it works.

It might be useful to add comments that we're ignoring errors on shutdown and why that's the right choice.  Otherwise 3 months from now no one will know why we're ignoring those errors in the unit test.

**Comment by vinniefalco** [comment]
@scottschurr It was just me being over-enthusiastic about checking for errors when I wrote the test. Anyone who programs sockets should already know that `shutdown` can fail, and that such failure is not an error.

**Comment by scottschurr** [comment]
@vinniefalco: Works for me.  :+1:.

**Comment by nbougalis** [comment]
:+1:

**Pull request merged**
