### PR TITLE
Speed up out of order transaction processing (RIPD-239)

### PR DESCRIPTION
**Pull request by ximinez**
Built on top of the (broken) proposed b9, so I wouldn't have to deal with conflicts in devirtualizing `LedgerMaster`. Please ignore those commits. Obviously, I'll rebase once that's merged.

Speaking of devirtualizing, it may be easier to verify that there were no unintended changes by examining the branch locally with `git diff -w`.

I left the test in a separate commit so you could easily revert the "RIPD-239" commit and verify the test fails.

Reviewers: @JoelKatz, @vinniefalco.

### CODE REVIEW

**Comment by ximinez** [comment]
Rebased against b12 and addressed @JoelKatz's concern by only resubmitting held transaction(s) with the next sequence number. I say "transaction(s)", because it is possible for a user to submit multiple different transactions with the same sequence if they all get a `ter`. Unfortunately, each one will still spawn a job, but at most one will apply, and the rest will either be discarded or re-held. There is still room for improvement by either trying `apply` instead of `submitTransaction` (which would be syncronous, and may slow things down), or forcing them all into one asyncronous job (sort of a batch `submitTransaction`).

**Comment by vinniefalco** [comment]
Looks good, I'll leave it up to the author to decide what to do with the `lower_bound` and `upper_bound`
:+1:

**Comment by ximinez** [comment]
Pushed another commit to clean up comments and make the bounds a little bit clearer (though functionally equivalent).

@JoelKatz Can you take another look and sign off, too?

**Comment by ximinez** [comment]
The current CircleCI failure appears spurious to me.

**Comment by ximinez** [comment]
Rebased against 0.30.1-b13.

**Comment by ximinez** [comment]
@ximinez ...I bet I could rewrite these new npm tests as C++ unit tests now that `Env` uses the `Application`.

**Comment by ximinez** [comment]
@ximinez It is not yet possible to fully port the npm tests over, but mao2 is getting there. See https://github.com/ximinez/rippled/commits/ripd239-2.

**Comment by ximinez** [comment]
Rebased against 0.30.1-b14.

**Comment by JoelKatz** [comment]
:+1:

**Comment by ximinez** [comment]
Rebased against 0.30.1-b15.

**Pull request closed without merging**
