### PR TITLE
Convert code to use boost::beast

### PR DESCRIPTION
**Pull request by seelabs**

### CODE REVIEW

**Comment by seelabs** [comment]
Please note the suppressions in cmake:
```
 -DBOOST_BEAST_ALLOW_DEPRECATED
 -DBOOST_ASIO_DISABLE_HANDLER_TYPE_REQUIREMENTS
```
We should plan on resolving these, but in another PR. I'd like this PR to be as vanilla a conversion as possible.

**Comment by HowardHinnant** [comment]
Got a nasty linker warning:
```
ld: warning: direct access in function 'void boost::archive::basic_text_iprimitive<std::__1::basic_istream<char, std::__1::char_traits<char> > >::load<short>(short&)' from file '/Users/howardhinnant/Development/boost_1_67_0/stage/lib/libboost_serialization.a(basic_text_iprimitive.o)' to global weak symbol 'std::__1::__cxx03_bool::__true_value()' from file '/Users/howardhinnant/Development/boost_1_67_0/stage/lib/libboost_regex.a(instances.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```
Looking into  it...

**Comment by seelabs** [comment]
@HowardHinnant Thanks for tracking that down.

**Comment by HowardHinnant** [comment]
@seelabs Should this get a Passed flag on it?

**Comment by HowardHinnant** [comment]
I thought CI was just a random pass/fail generator... ;-)

**Comment by seelabs** [comment]
In 1.1.0-b1

**Pull request closed without merging**
