### PR TITLE
Trivial: Clean structure of RPC::addPaymentDeliveredAmount

### PR DESCRIPTION
**Pull request by rec**
I really wanted to use this to take the opportunity to discuss https://ripplelabs.atlassian.net/browse/RIPD-791... :-)

### CODE REVIEW

**Comment by rec** [comment]
Reviewers: @nbougalis  @ximinez

**Comment by MarkusTeufelberger** [comment]
Line 54 still misses a ledger height or hash...

**Comment by rec** [comment]
You referred to this before if memory serves me?  I'm not quite clear what you want, but this is perhaps the time to ask for it...? :-)

**Comment by MarkusTeufelberger** [comment]
"The first ledger where the DeliveredAmount flag appears is which closed on 2014-Jan-24 at 04:50:10." - this sentence is missing a certain something (between is and which). A ledger height or hash to specify this ledger could fit.

**Comment by nbougalis** [comment]
You aren't kidding @MarkusTeufelberger... I'm embarassed that I wrote that comment! I don't have the ledger number handy; I guess we could specify it as well, although I don't know that it helps very much.

At any rate, I suggest the following wording for the comment:

    // If the ledger closed at 2014-Jan-24 at 04:50:10 or later, then
    // the absence of the DeliveredAmount field indicates that the
    // actual amount delivered is in the Amount field.

@rec, there are no objections to the wording, would you mind stacking a commit on top with the change? Thanks.

**Comment by nbougalis** [comment]
I see that Travis failed. I don't have time to examine this failure, but I don't see anything blatantly wrong with this PR.

**Comment by ximinez** [comment]
Windows debug unity and nounity builds fail:
```
cl /Fobuild\msvc.debug.nounity\src\ripple\unity\rpcx.obj /c src\ripple\unity\rpc
x.cpp /TP /nologo /bigobj /EHa /fp:precise /Gd /Gm- /GR /Gy- /FS /MP /openmp- /Z
c:forScope /Zi /errorReport:none /nologo /W3 /WX- /wd"4018" /wd"4244" /wd"4267"
/wd"4800" /GS /MTd /Od /RTC1 /DOPENSSL_NO_SSL2 /DDEPRECATED_IN_MAC_OS_X_VERSION_
10_7_AND_LATER /DHAVE_USLEEP=1 /DDEBUG /D_DEBUG /D_WIN32_WINNT=0x6000 /D_SCL_SEC
URE_NO_WARNINGS /D_CRT_SECURE_NO_WARNINGS /DWIN32_CONSOLE /D_CRTDBG_MAP_ALLOC /I
C:\boost_1_57_0 /IC:\OpenSSL-Win64\include /Isrc /Isrc\beast /Ibuild\proto /Isrc
\soci\src /Isrc\protobuf\src /Isrc\protobuf\vsprojects
rpcx.cpp
c:\Dev\rippled-merge\src\ripple/rpc/handlers/AccountCurrencies.cpp(27) : error C
2039: 'Context' : is not a member of 'ripple::RPC::ripple::RPC'
c:\Dev\rippled-merge\src\ripple/rpc/handlers/AccountCurrencies.cpp(39) : error C
2039: 'missing_field_error' : is not a member of 'ripple::RPC::ripple::RPC'
c:\Dev\rippled-merge\src\ripple/rpc/handlers/AccountInfo.cpp(34) : error C2039:
'Context' : is not a member of 'ripple::RPC::ripple::RPC'
c:\Dev\rippled-merge\src\ripple/rpc/handlers/AccountInfo.cpp(45) : error C2039:
'missing_field_error' : is not a member of 'ripple::RPC::ripple::RPC'
c:\Dev\rippled-merge\src\ripple/rpc/handlers/AccountInfo.cpp(73) : error C2039:
'inject_error' : is not a member of 'ripple::RPC::ripple::RPC'
c:\Dev\rippled-merge\src\ripple/rpc/handlers/AccountLines.cpp(77) : error C2039:
 'Context' : is not a member of 'ripple::RPC::ripple::RPC'
c:\Dev\rippled-merge\src\ripple/rpc/handlers/AccountLines.cpp(81) : error C2039:
 'missing_field_error' : is not a member of 'ripple::RPC::ripple::RPC'
c:\Dev\rippled-merge\src\ripple/rpc/handlers/AccountLines.cpp(136) : error C2039
: 'expected_field_error' : is not a member of 'ripple::RPC::ripple::RPC'
c:\Dev\rippled-merge\src\ripple/rpc/handlers/AccountLines.cpp(143) : error C3083
: 'Tuning': the symbol to the left of a '::' must be a type
```

**Comment by rec** [comment]
How can that be possibly right?  Look at the change!

**Comment by nbougalis** [comment]
@rec sounds like a header file is missing maybe?

**Comment by ximinez** [comment]
I don't know how, but it's failing in Linux, too.

On Thu, Mar 26, 2015 at 4:06 PM, Tom Swirly <notifications@github.com>
wrote:

> How can that be possibly right? Look at the change!
>
> On Thu, Mar 26, 2015 at 3:55 PM, ximinez <notifications@github.com> wrote:
>
> > Windows debug unity and nounity builds fail:
> >
> > cl /Fobuild\msvc.debug.nounity\src\ripple\unity\rpcx.obj /c
> src\ripple\unity\rpc
> > x.cpp /TP /nologo /bigobj /EHa /fp:precise /Gd /Gm- /GR /Gy- /FS /MP
> /openmp- /Z
> > c:forScope /Zi /errorReport:none /nologo /W3 /WX- /wd"4018" /wd"4244"
> /wd"4267"
> > /wd"4800" /GS /MTd /Od /RTC1 /DOPENSSL_NO_SSL2
> /DDEPRECATED_IN_MAC_OS_X_VERSION_
> > 10_7_AND_LATER /DHAVE_USLEEP=1 /DDEBUG /D_DEBUG /D_WIN32_WINNT=0x6000
> /D_SCL_SEC
> > URE_NO_WARNINGS /D_CRT_SECURE_NO_WARNINGS /DWIN32_CONSOLE
> /D_CRTDBG_MAP_ALLOC /I
> > C:\boost_1_57_0 /IC:\OpenSSL-Win64\include /Isrc /Isrc\beast
> /Ibuild\proto /Isrc
> > \soci\src /Isrc\protobuf\src /Isrc\protobuf\vsprojects
> > rpcx.cpp
> > c:\Dev\rippled-merge\src\ripple/rpc/handlers/AccountCurrencies.cpp(27) :
> error C
> > 2039: 'Context' : is not a member of 'ripple::RPC::ripple::RPC'
> > c:\Dev\rippled-merge\src\ripple/rpc/handlers/AccountCurrencies.cpp(39) :
> error C
> > 2039: 'missing_field_error' : is not a member of
> 'ripple::RPC::ripple::RPC'
> > c:\Dev\rippled-merge\src\ripple/rpc/handlers/AccountInfo.cpp(34) : error
> C2039:
> > 'Context' : is not a member of 'ripple::RPC::ripple::RPC'
> > c:\Dev\rippled-merge\src\ripple/rpc/handlers/AccountInfo.cpp(45) : error
> C2039:
> > 'missing_field_error' : is not a member of 'ripple::RPC::ripple::RPC'
> > c:\Dev\rippled-merge\src\ripple/rpc/handlers/AccountInfo.cpp(73) : error
> C2039:
> > 'inject_error' : is not a member of 'ripple::RPC::ripple::RPC'
> > c:\Dev\rippled-merge\src\ripple/rpc/handlers/AccountLines.cpp(77) :
> error C2039:
> > 'Context' : is not a member of 'ripple::RPC::ripple::RPC'
> > c:\Dev\rippled-merge\src\ripple/rpc/handlers/AccountLines.cpp(81) :
> error C2039:
> > 'missing_field_error' : is not a member of 'ripple::RPC::ripple::RPC'
> > c:\Dev\rippled-merge\src\ripple/rpc/handlers/AccountLines.cpp(136) :
> error C2039
> > : 'expected_field_error' : is not a member of 'ripple::RPC::ripple::RPC'
> > c:\Dev\rippled-merge\src\ripple/rpc/handlers/AccountLines.cpp(143) :
> error C3083
> > : 'Tuning': the symbol to the left of a '::' must be a type
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ripple/rippled/pull/953#issuecomment-86689817>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ripple/rippled/pull/953#issuecomment-86693757>.
>



-- 
*Edward Hennis | *Senior Software Engineer | *Ripple Labs Inc.*
ed@ripple.com | www.ripple.com | *www.ripplelabs.com
<http://www.ripplelabs.com/>*
T. 352.327.8769

**Comment by rec** [comment]
It seems like madness.  Look at the changes!  They are purely cosmetic, one
step beyond a whitespace-only change!

I mainly opened this in order to make sure that a RIPD involving this code
was actually closed.


Well, I'm going to rebase against the new develop, but if that fails I'm
going to abandon it.

**Comment by MarkusTeufelberger** [comment]
You changed whitespace AND deleted 2 closing curly braces that would end namespaces, hence the errors with "ripple::RPC::ripple::RPC" in the file that gets compiled right after this one.

**Comment by rec** [comment]
Thanks, Markus! 

I'm thinking what happened is that I rebased against develop, pushed, but didn't test the right thing.

It's peculiar, however - as there weren't any conflicts in the rebase, and I have a recent executable.

Well, I'm sure I screwed up somehow - fixing it.

**Comment by ximinez** [comment]
Good catch @MarkusTeufelberger!

**Comment by rec** [comment]
Embarrassing.  Here's the correct version.

**Comment by ximinez** [comment]
Changes look good. Code is quite a bit more readable. And as a bonus, builds.

:+1:

**Comment by rec** [comment]
Building is a detail.  ;-)

Still embarrassed about this and not sure what happened.  I do actually build and test everything that goes it, it takes quite a bit of my day!  

Moving right along...

**Comment by nbougalis** [comment]
@rec: please update the comment that Markus Teufelberger highlighted. The following message can be used instead:

    // If the ledger closed at 2014-Jan-24 at 04:50:10 or later, then
    // the absence of the DeliveredAmount field indicates that the
    // actual amount delivered is in the Amount field.

**Comment by rec** [comment]
I felt sure I'd done this before too.  Sigh.  done.

**Comment by rec** [comment]
Should we be actually using UTC for times everywhere? `2014-01-24T04:50:10Z` instead of `2014-Jan-24 at 04:50:10`?

**Pull request closed without merging**
