### PR TITLE
New peer to peer network simulators

### PR DESCRIPTION
**Pull request by vinniefalco**
This adds the `BasicNetwork` peer to peer simulation framework, and a test simulation that demonstrates a mechanism for reducing traffic generated by broadcasting proposals and validations.

### CODE REVIEW

**Comment by vinniefalco** [comment]
The top commit was already approved in #1194

**Comment by HowardHinnant** [comment]
:+1:

**Comment by HowardHinnant** [comment]
````
clang++ -o build/clang.debug.nounity/src/ripple/unl/tests/SlotPeer_test.o -c -Wall -frtti -std=c++11 -Wno-invalid-offsetof -Wno-mismatched-tags -Wno-deprecated-register -Wno-sign-compare -Wno-char-subscripts -Wno-format -g -Wno-redeclared-class-member -Wno-deprecated -Wno-deprecated-declarations -Wno-unused-variable -Wno-unused-function -DOPENSSL_NO_SSL2 -DDEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER -DHAVE_USLEEP=1 -DDEBUG -D_DEBUG -DBOOST_ASIO_HAS_STD_ARRAY -D_FILE_OFFSET_BITS=64 -DBEAST_COMPILE_OBJECTIVE_CPP=1 -I/usr/local/Cellar/openssl/1.0.1f/include -I/Users/howardhinnant/Development/boost_1_57_0 -Isrc -Isrc/beast -Ibuild/proto -Isrc/soci/src src/ripple/unl/tests/SlotPeer_test.cpp
src/ripple/unl/tests/Network_test.cpp:155:21: error: use of undeclared identifier 'connect'
                if (connect(peer, pv[rand(pv.size())],
                    ^
                    this->
src/ripple/unl/tests/Network_test.cpp:130:21: note: in instantiation of member function
      'ripple::test::Net_test::Network<ripple::test::Net_test::InstantPeer>::connect_one' requested here
                    connect_one(peer);
                    ^
src/ripple/unl/tests/Network_test.cpp:168:13: note: in instantiation of member function
      'ripple::test::Net_test::Network<ripple::test::Net_test::InstantPeer>::Network' requested here
        Net net;
            ^
src/ripple/unl/tests/Network_test.cpp:208:9: note: in instantiation of function template specialization
      'ripple::test::Net_test::testDiameter<ripple::test::Net_test::InstantPeer>' requested here
        testDiameter<InstantPeer>("InstantPeer");
        ^
src/ripple/unl/tests/BasicNetwork.h:209:5: note: must qualify identifier to find this declaration in dependent base class
    connect (Peer& from, Peer& to,
    ^
1 error generated.
````

**Comment by vinniefalco** [comment]
Rebased to b2

**Comment by JoelKatz** [comment]
:+1:

**Comment by HowardHinnant** [comment]
:+1:  for cf139b422700e855f1af46dcb0c2c8699b09977f

**Pull request closed without merging**
