### PR TITLE
Fix Subscribe RPC to correctly distinguish bids and asks.

### PR DESCRIPTION
**Pull request by rec**
Found by Mickey!

See here:

https://github.com/ripple/rippled/commit/6014b132348bc51af658285cf2d385bc504deb6d#diff-e33c82fefe08b47268c75bbbd4bd054cL311

Note that there are apparently no tests for Subscribe - I filed a JIRA for this: https://ripplelabs.atlassian.net/browse/RIPD-740

### CODE REVIEW

**Comment by rec** [comment]
Reviewers: @miguelportilla @ximinez

**Comment by miguelportilla** [comment]
Nice fix to this problem, Tom. LGTM +1

**Comment by ximinez** [comment]
Clever fix. :+1: 

Builds, and unit and JS tests pass in Windows. Not that that helps much in this case.

**Comment by rec** [comment]
Pushed a new version with Vinnie's `reversed` suggestion.

**Comment by miguelportilla** [comment]
I cherry picked your fix,Tom.

**Comment by rec** [comment]
Closing this in favor of Mickey's branch.

**Pull request closed without merging**
