### PR TITLE
Include 2 missing headers

### LINKED ISSUE #2402: src/ripple/beast/core/WaitableEvent.cpp might miss 2 includes
...namely `<errno.h>` (for ETIMEDOUT) and `<sys/time.h>` (for gettimeofday())

### PR DESCRIPTION
**Pull request by MarkusTeufelberger**
<errno.h> for ETIMEDOUT
<sys/time.h> for gettimeofday()

fixes #2402

### CODE REVIEW

**Comment by smlu** [comment]
This PR probably won't compile under VS because header file`sys/time.h` is missing on windows.
Should be placed in Unix scope.

**Comment by MarkusTeufelberger** [comment]
Hm, ok. Thanks for the warning, I don't use VS.

It now works on Linux though, so my use case is covered. I'm sure someone from Ripple will take a closer look and advise on how to do the necessary ifdefs that they prefer.

**Comment by HowardHinnant** [comment]
How about we try changing `<errno.h>` to `<cerrno>` and moving `<sys/time.h>` down to just inside the `#else` (// !BEAST_WINDOWS).

**Comment by scottschurr** [comment]
@HowardHinnant, what I've done with a couple of @MarkusTeufelberger's pull requests in the past is cherry-pick the commit(s) onto a branch of my own, do any massaging that's required, and push to my GitHub.  Since it's a cherry-pick it preserves Markus's ID on the commit.  Then, once the branch passes local CI, submit a pull request for the new branch and close Markus's original.  That's a technique to get the pull request to be processed by our CI.

Would you like to do that for this pull request?  Or I could do it if you'd like.

**Comment by HowardHinnant** [comment]
I can do it.

**Comment by MarkusTeufelberger** [comment]
in 1.0.0-b1

**Pull request closed without merging**
