### PR TITLE
Remove rippled.spec rpm file

### PR DESCRIPTION
**Pull request by wilsonianb**
rippled.spec has not been maintained aside from bumping the version.
To my knowledge it has not been used for rpm package building.
https://github.com/ripple/rippled-package-builder/blob/master/rpm-builder/rippled.spec is now available as a reference that is in use.

### CODE REVIEW

**Comment by wilsonianb** [comment]
Alternatively, we could add https://github.com/ripple/rippled-package-builder as a submodule in the `Builds/` directory.

**Comment by vinniefalco** [comment]
Are you telling me that we've been updating the version in this file for all this time, for nothing?!

**Comment by wilsonianb** [comment]
I think it has been unchanged (aside from the version) since it was added March 2014
https://github.com/ripple/rippled/commits/develop/Builds/rpm/rippled.spec

It's possible others have used it to build rpms since that time, but I have no evidence of that being the case.

**Comment by MarkusTeufelberger** [comment]
I personally would prefer storing the rippled related repositories as submodules (e.g. the debian build and the RPM build), there has been a recent explosion of repositories with only few commits or very limited scope...

**Comment by stevenzeiler** [comment]
I'm in favor of including `rippled-package-builder` as a git submodule of rippled.

**Comment by vinniefalco** [comment]
Do you mean `git-submodule` or `git-subtree`? I'm not a fan of submodules. Please explain why a submodule is benefical in this circumstance and why `rippled-package-builder` needs to be in the tree

**Comment by MarkusTeufelberger** [comment]
I constantly confuse these 2, so I just repeated the suggestion from @wilsonianb to use a submodule... no strong feelings either way, just that it might be nice to have stuff that is very closely related to rippled available in the rippled repo.

**Comment by vinniefalco** [comment]
Its not necessary for the rippled repository to accumulate submodules for every rippled related project. Instead, just create a new repository that adds (either as submodules or subtrees) the rippled repo and the rippled-package-builder repo, along with any other repositories that you want. It doesn't even need to be in the Ripple organization. Then you can have all the related repositories together in one, but without the need for making them children of the rippled repository.

**Pull request closed without merging**
