### PR TITLE
Trivial: Replace calls to new(). (#243)

### PR DESCRIPTION
**Pull request by rec**
Reviewers: @vinniefalco @nbougalis

### CODE REVIEW

**Comment by nbougalis** [comment]
This is likely broken: `PeerFinder::Logic` uses `beast::SharedPtr` but also relies on `beast::SharedObject` functionality for `Source`. Until we can remove that dependency, `beast::SharedPtr` can't be simply replaced with `std::shared_ptr`.

**Comment by rec** [comment]
Oh, really!  So that reveals something - we have no tests for this facility!

I'll probably revert that part but let me see what I can do.

**Comment by rec** [comment]
(I reverted all those pending better understanding of `beast::SharedPtr`.)

**Comment by nbougalis** [comment]
:+1:

**Comment by scottschurr** [comment]
Incorporated as d5193a776e9972db334892f7036888d2cbd6c9fd

**Pull request closed without merging**
