### PR TITLE
ConnectedAddresses stores Addresses to avoid port issues.

### PR DESCRIPTION
**Pull request by ximinez**
* Also change log level on a couple of Overlay messages.

Prevents fallacious assertion.

Reviewers: @vinniefalco, @miguelportilla

### CODE REVIEW

**Comment by vinniefalco** [comment]
Completely rational changes, thanks for taking the initiative
:+1:

**Comment by ximinez** [comment]
@vinniefalco You're welcome. I was motivated by the pain it was causing on my dogfood machine.

**Comment by ximinez** [comment]
BTW, I've been running this branch on my dogfood machine, and the uptime is now just shy of 3 days. Hasn't lost sync at all either.

**Comment by rec** [comment]
Friggen great idea, :100:

**Comment by miguelportilla** [comment]
LGTM :+1:

**Pull request closed without merging**
