### PR TITLE
Catch unhandled exceptions in I/O service threads

### PR DESCRIPTION
**Pull request by nbougalis**

### CODE REVIEW

**Comment by vinniefalco** [comment]
Reviewer: @willwray

**Comment by HowardHinnant** [comment]
For linux where we have the special libstdc++, we need to follow the Apple path here:
https://github.com/nbougalis/rippled/blob/9cf7d359d56537afe1c77091dda120e4776cf0e9/src/ripple/core/ReportUncaughtException.h#L102
This would best be addressed in ReportUncaughtException.h (application wide).

**Comment by scottschurr** [comment]
@HowardHinnant: In the latest version of ReportUncaughtException.h your concern would be handled by defining `NO_LOG_UNHANDLED_EXCEPTIONS ` on the compiler command line (using Scons).  See https://github.com/ripple/rippled/blob/develop/src/ripple/core/ReportUncaughtException.h#L102.  Would that be sufficient?

**Comment by HowardHinnant** [comment]
Yup, that would be great.

**Comment by HowardHinnant** [comment]
👍

**Comment by willwray** [comment]
:thumbsup:

**Pull request closed without merging**
