### PR TITLE
View medley

### PR DESCRIPTION
**Pull request by vinniefalco**
Odds and ends

### CODE REVIEW

**Comment by HowardHinnant** [comment]
````
Jade:~/Development/rippled> npm test
 
> rippled@0.0.1 test /Users/howardhinnant/Development/rippled
> mocha test/websocket-test.js test/server-test.js test/*-test.{js,coffee}

-

  WebSocket connection
rippled stderr:
Loading: "rippled.cfg"
2015-Jul-16 20:09:44 LedgerMaster:NFO Validation quorum: 1
2015-Jul-16 20:09:44 LedgerMaster:DBG Ledger 2 accepted :110DFD4A51B84B3E9EDAB6517CABD880DBE51C10DB210D9C2E848790DF12DF00
2015-Jul-16 20:09:44 Ledger:TRC saveValidatedLedger fromAcquire 2
2015-Jul-16 20:09:44 OrderBookDB:DBG Advancing from 0 to 2
2015-Jul-16 20:09:44 OrderBookDB:DBG OrderBookDB::update>
    1) WebSocket connect and disconnect
    2) "after each" hook

  Standalone server startup
    ✓ server start and stop 

  account_objects
rippled stderr:
Loading: "rippled.cfg"
2015-Jul-16 20:09:47 LedgerMaster:NFO Validation quorum: 1
2015-Jul-16 20:09:47 LedgerMaster:DBG Ledger 2 accepted :03FDA4C94D9775C56A30173E20CDB30B2C37AB202969248DD5DBECAFCAEAB183
2015-Jul-16 20:09:47 Ledger:TRC saveValidatedLedger fromAcquire 2
2015-Jul-16 20:09:47 OrderBookDB:DBG Advancing from 0 to 2
2015-Jul-16 20:09:47 OrderBookDB:DBG OrderBookDB::update>
    3) "before all" hook

  1 passing (4s)
  3 failing

  1) WebSocket connection WebSocket connect and disconnect:
     Uncaught AssertionError: Server died with signal SIGSEGV
    at ChildProcess.<anonymous> (/Users/howardhinnant/Development/rippled/test/server.js:143:5)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:809:12)
  

  2) WebSocket connection "after each" hook:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
    at [object Object].<anonymous> (/Users/howardhinnant/Development/rippled/node_modules/mocha/lib/runnable.js:170:19)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)
  

  3) account_objects "before all" hook:
     Uncaught AssertionError: Server died with signal SIGSEGV
    at ChildProcess.<anonymous> (/Users/howardhinnant/Development/rippled/test/server.js:143:5)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:809:12)
  



npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
````

**Comment by vinniefalco** [comment]
Yep, two functions were missing their implementation - pushed the fix marked `[FOLD]`

**Comment by HowardHinnant** [comment]
Latest version passes all tests for me. :+1:

**Comment by rec** [comment]
Possible simplifications here:

https://github.com/rec/rippled/commits/cache

**Comment by vinniefalco** [comment]
@HowardHinnant I squashed in the fix for the unit test and made `sles` a `const&` in the range-fors.

**Comment by vinniefalco** [comment]
I chopped off the last "rules" commit since Ed needs more work done on it

**Comment by vinniefalco** [comment]
Fixed vcxproj out of date

**Comment by ximinez** [comment]
Everything looks fine. I left a suggestion/question about `mapped_type`, but it's not necessary. @rec's simplifications also look good, but not required.

:+1:

**Comment by vinniefalco** [comment]
@JoelKatz Should we remove **Always cache in ApplyView::read:** ?

**Pull request closed without merging**
