### PR TITLE
Simplify lookupLedger().

### PR DESCRIPTION
**Pull request by rec**
Reviewers: @nbougalis @JoelKatz

Probably replaces #820

### CODE REVIEW

**Comment by JoelKatz** [comment]
It'd be nice to have a log at warning level if ``walkHashBySeq`` throws. Also, I'm not sure why the hash of the ledger is called ``next``, but it should probably be called something else -- even ``hash`` is better.

:+1:

**Comment by nbougalis** [comment]
It'd be nice to get David's comments addressed. With that said, this gets a :+1: from me. I won't mark it as passed. Tom, feel free to do so, unless you wish to address the comments.

**Comment by rec** [comment]
I did all the comments.  The ternary was weird, I think it evolved from something else, murdered it too and rebased.

**Comment by rec** [comment]
Are we good to go?

**Comment by nbougalis** [comment]
Merged as e742da73bd10bb0ada28775ce2c58a02392f9aec

**Pull request closed without merging**
