### PR TITLE
Redirect on peer with duplicate IP

### PR DESCRIPTION
**Pull request by vinniefalco**
Solves a problem where a second outgoing peer connection from the same IP will cause the server to return a 403 with no helpful explanation

Reviewers: @JoelKatz

### CODE REVIEW

**Comment by nbougalis** [comment]
Well, VS2015 isn't cooperating:```C:\projects\rippled-179\src\ripple/app/ledger/impl/LedgerCleaner.cpp(98): error C2512: 'beast::SharedData<ripple::LedgerCleanerImp::State,beast::SharedMutexAdapter<beast::RecursiveMutex>>::SharedData': no appropriate default constructor available 
scons: *** [build\msvc.debug\src\ripple\unity\app_ledger.obj] Error 2
scons: building terminated because of errors.
```

**Comment by JoelKatz** [comment]
This doesn't really help very much. There are a very small number of bootstrap servers and with this change, if someone else from behind the same NAT at you is connected to all of them, you still won't get any peers.

**Comment by nbougalis** [comment]
How about we allow multiple connections from the same IP but place a limit - say 2 or 3?

**Comment by JoelKatz** [comment]
I'd love to see more than one connection allowed from the same IP. I was thinking either a configurable number or one per 32 (or 64) inbound peer slots.

**Comment by vinniefalco** [comment]
We will rethink the treatment of duplicate IPs

**Pull request closed without merging**
