### PR TITLE
Simple multisigning (RIPD-182):

### PR DESCRIPTION
**Pull request by scottschurr**
With this changeset two-level multisigning is removed from the
codebase and replaced with single-level multisigning.  There are
three known missing elements:

 1. Multisigned transactions should require higher fees than
    regular (single-signed) transaction.  That's not yet
    implemented.

 2. It should be possible to disable the master key on an account
    if that account is multisign enabled (has a signer list).
    That's not yet implemented.

 3. Documentation about multisigning needs to be improved.

Multisigning is still compiled out of the code base.  To enable
multisigning for a stand-alone rippled, change the
RIPPLE_ENABLE_MULTI_SIGN macro (in BeastConfig.h) to "1" and
rebuild.

This commit also addresses:
 o RIPD-912: Remove multisign APIs from STObject, and
 o RIPD-944: Replace common_transactor with jtx at call sites.

Reviewers: @nbougalis, @JoelKatz, @vinniefalco

### CODE REVIEW

**Comment by nbougalis** [comment]
:+1:

**Comment by nbougalis** [comment]
I'm ok with this :+1:

**Comment by scottschurr** [comment]
Rebased and incorporated a couple of comments from @nbougalis.

**Comment by JoelKatz** [comment]
:+1:

**Pull request closed without merging**
