### PR TITLE
Verify slqlite ledgers exist in node store

### PR DESCRIPTION
**Pull request by miguelportilla**

### CODE REVIEW

**Comment by MarkusTeufelberger** [comment]
This only checks if the header is present in the node store compared to `ledger_cleaner` which would fetch the whole SHAMap tries, right?

**Comment by miguelportilla** [comment]
@MarkusTeufelberger Correct. This additional check detects when the node store in out of sync with sqlite, making `complete_ledgers` more accurate. The desync usually occurs when a user deletes their node store and forgets to clear the sqlite DB.

**Comment by miguelportilla** [comment]
@ximinez I don't believe so as this is called after a network sync and backfilling begins.

**Comment by ximinez** [comment]
@miguelportilla That's what I was thinking, too. Oh well.

**Comment by bachase** [comment]
In 1.0.0-b3 as 4869a0d00e4c5854b1760ca89ee93b1a7c79b8f1

**Pull request closed without merging**
