### PR TITLE
Fix RPC subscribe with multiple books (RIPD-77):

### PR DESCRIPTION
**Pull request by miguelportilla**
* Fix subscribe to multiple books to report all bids and asks or offers
* Append Bids, Asks and Offers of each book to the result

Reviewers: @rec @ximinez

### CODE REVIEW

**Comment by rec** [comment]
You should replace my change with the updated one...

Or even just wait, we can make sure that one is checked in before the other.  Your code is basically independent of my change.

**Comment by miguelportilla** [comment]
Tom, I cherry picked your fix. Its using the version that your named 'reverse' as Vinnie suggested.

The jvOffers param will get stomped with each call to getBookPage, which is the intent.

**Comment by rec** [comment]
You're behind the times, Vinnie's new suggestion is `reversed` (note the extra "d" on the end) and you don't have that!

**Comment by rec** [comment]
OK, hmm, I clearly need to read the final code again.  Moment please...

**Comment by miguelportilla** [comment]
Ah right you are sir. Cherry picked once more. That 'd' was brilliant :)

**Comment by miguelportilla** [comment]
That lambda would omit calling reversed.

**Comment by ximinez** [comment]
Looks good. This change underscores the need to have book subscription unit / integration tests.

**Comment by rec** [comment]
There's a weirdness in the commits - the initial fix appears to be there twice??

If you fix up the commits, this looks good to me!

**Comment by miguelportilla** [comment]
Done

**Comment by ximinez** [comment]
Good news, bad news.

Good news: I wrote a test. https://github.com/ximinez/rippled/commit/2d89366bf5605792c7e4f0a4a6a059ac97122379

Bad news: It found a bug. The multiple book request seems to be returning duplicates of one book or the other. More details soon.

**Comment by miguelportilla** [comment]
Duplicates in the bids or asks arrays?

**Comment by ximinez** [comment]
All. Bids, asks, offers (depending on the value of `both`) are all duplicated.

Here's some extra output:

```
Received:  2
  TakerGets: 200/CNY/rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh, TakerPays 100/JPY/rHb9C
JAWyB4rj91VRWn96DkukG4bwdtyTh
  TakerGets: 200/CNY/rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh, TakerPays 100/JPY/rHb9C
JAWyB4rj91VRWn96DkukG4bwdtyTh
Found:  1
  TakerGets: 200/cny/root, TakerPays 100/jpy/root
Not found:  1
  TakerGets: 200, TakerPays 100/usd/root
    1) Multiple books: One side: Offers in book
    √ Multiple books: Both sides: Empty book (403ms)
Received:  2
  TakerGets: 100/JPY/rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh, TakerPays 500/CNY/rHb9C
JAWyB4rj91VRWn96DkukG4bwdtyTh
  TakerGets: 100/JPY/rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh, TakerPays 500/CNY/rHb9C
JAWyB4rj91VRWn96DkukG4bwdtyTh
Found:  1
  TakerGets: 100/jpy/root, TakerPays 500/cny/root
Not found:  1
  TakerGets: 100/usd/root, TakerPays 500
    2) Multiple books: Both sides: Offers in book
```

**Comment by ximinez** [comment]
Never mind. There was a bug in the test. Updated test commit: https://github.com/ximinez/rippled/commit/514a7a0a5c8cf907289aab9eed925fb738a39132

**Comment by miguelportilla** [comment]
Cherry picked Ed's new integration test.

**Comment by ximinez** [comment]
I approve of adding the test. :+1:

**Comment by rec** [comment]
:+1:

**Pull request closed without merging**
