### PR TITLE
Update dependency scripts for Ubuntu 16.04

### PR DESCRIPTION
**Pull request by seelabs**
A minor update to the scripts that install deps for ubuntu 16.04.

@ximinez @nbougalis

### CODE REVIEW

**Comment by ximinez** [comment]
I'm going to upgrade to 16.04 on one box during lunch so I can actually run these. :)

**Comment by ximinez** [comment]
Everything seems to work on an upgraded Ubuntu 16.04 system. :+1:

**Comment by vinniefalco** [comment]
TRIVIAL

**Comment by nbougalis** [comment]
Merged as 13ec10415449ae58c5e9b857605b732a4dab928b

**Pull request closed without merging**
