### PR TITLE
Support python3 in SCons

### PR DESCRIPTION
**Pull request by JoelKatz**
These changes allow our scons build to work with both python2 and python3.

### CODE REVIEW

**Comment by seelabs** [comment]
:+1: Tested on ubuntu 16.04 and 12.04. @bachase Tested on windows.

**Comment by scottschurr** [comment]
:+1: tested on macOS, and it worked fine.

**Comment by mDuo13** [comment]
👍 Built sucessfully on Arch Linux with Python v3.6.3 and scons v3.0.0

**Comment by bachase** [comment]
Merged as 5a9c3c797c1ee2be7e38f226bf7f831f43c024c1

**Pull request closed without merging**
