### PR TITLE
Fix SusPay condition check in Finish:

### PR DESCRIPTION
**Pull request by vinniefalco**
On a SusPayFinish, an additional check is added to make sure that the presented digest matches the digest in the SusPay ledger entry. This includes a regression unit test.

Reviewers: @rec @ximinez

### CODE REVIEW

**Comment by ximinez** [comment]
Looks good. :+1:

**Comment by rec** [comment]
Well, `digest` isn't a useful name - what would be interesting is whose digest it is.

Another option is

    if (auto const& ledgerDigest = (*slep)[~sfDigest]))
        if (! (ctx_.tx[~sfMethod] && ledgerDigest == ctx_.tx[~sfDigest]))
            return tecNO_PERMISSION;

making it clearer that you're comparing the ledger digest with the transaction digest...

but it's not important.  :+1:

**Comment by vinniefalco** [comment]
`slep` is completely clear: "S"erialized "L"edger "Entry" of the "P"ayment (versus just `sle`, which by convention is the account root for any function that loads 2 or more ledger entries where one of them is the account root). I admit that `sle` at first was not agreeable, but considering both the frequency which it comes up in business logic, and that it is a fundamental building block of rippled, it makes sense to presume that the reader is aware.

**Comment by rec** [comment]
> slep is completely clear: 

It's completely clear _to you_ because you invented all these acronyms.  For me at least, each time I see one I have to fill it in.  When it's an existing English word, like `sled`, I block a little longer.

> `sle`, which by convention is the account root for any function that loads 2 or more ledger entries where one of them is the account root

I didn't know that!  "two or more ledger entries where one of them is the account root"...

How do you expect non-ripple engineers to ever read - and audit - this code when there is such a huge cognitive burden required to understand even the simplest parts?

The reason I keep pushing back on this is because 

1. I find the code extremely hard to read and understand and it seems to be getting worse.

2. We keep finding errors caused by rippled engineers misreading the code.  The example that stood out for me was the test that didn't test anything - five engineers participated in that review, yet none of them saw it.

3. Thirty years of experience has shown me time and time again that the simplest and most readable code (and I mean readable to anyone) is usually also the most correct, reliable, and (most of the time) the most performant.

(If I were naming this stuff, it'd be just `LedgerEntry` - I never understood why you needed to advertise the serialization, if you couldn't serialize it, you couldn't put it in a ledger, could you? - and the variable would be `paymentLedgerEntry` - conceivably `paymentEntry`.)


Anyway, none of this is "actionable" - I already :+1: 'ed this - but you should understand where I'm coming from here.  

I will do anything to avoid risk, and to my mind, it is a risk to rely on engineers to understand "`sle`, which by convention is the account root for any function that loads 2 or more ledger entries where one of them is the account root" - and to correctly reason with that understanding each time they see the variable name.

**Comment by vinniefalco** [comment]
@rec I didn't pick `SLE`, it was there already and I considered changing it but ultimately just accepted it since David understands it, its reasonably short (`SLE is currently an alias for `STLedgerEntry`), and the rename would be largely gratuitous. I don't think that the `STObject` class hierarchy (which we now call "st") is particularly bad although there is certainly room for tidying.

**Pull request merged**
