### PR TITLE
Remove deprecated account_tx interface [RIPD-1569]

### PR DESCRIPTION
**Pull request by scottschurr**
As noted in RIPD-1569, the account_tx RPC command has maintained a deprecated interface since 2014 or so.  That interface has been documented as deprecated for a long time.  The deprecated interface has no tests.  It's time to remove the deprecated support.

### CODE REVIEW

**Comment by scottschurr** [comment]
Yipes!  Good catch! It looks like the entire command line interface to `account_tx` is predicated on the deprecated interface that I was about to remove.  See the command line tab at https://developers.ripple.com/account_tx.html.

So I'm guessing this will have to wait while we get a new command line interface specified and implemented.  I have no idea what the transition process should like like either.  Still, I guess it's better to know than to be ignorant.

I won't close this immediately.  I'll wait until @mDuo13 has an opportunity to weigh in on what he'd like to see regarding the command line interface.

**Comment by scottschurr** [comment]
No word yet from @mDuo13 on a preferred command line interface.  So I'm closing this pull request.

**Comment by mDuo13** [comment]
Sorry, I missed this. I think I'd like to have a new command line interface that works without using the `json` command.

**Comment by scottschurr** [comment]
No problem @mDuo13, you're a busy guy.

So, given that preference, there are two additional questions:
1. What should the interface for the new command look like?
2. What should the transition process between the old command line interface and the new one look like?

If the command line interface shouldn't change (even through it matches the deprecated RPC interface) then there is no transition process and I can easily close the JIRA item.  Anything other than that and we'll need to think a bit harder.

Thanks for your thoughts.

**Comment by mDuo13** [comment]
I think the commandline interface should be something like this (basically, this is my take on how to substitute the old format's arguments for the new format):

```
rippled -- account_tx {address} {ledger_index_min} {ledger_index_max} [limit] [marker] [binary] [forward]
```

(The `--` is of course just there to prevent arguments like `-1` from being interpreted as flags, and isn't part of the `account_tx` syntax itself. The curly-braced fields would be mandatory and the square bracket ones would be optional.)

From what I can tell, if you provide `"marker": null`, `"marker": 0`, or `"marker": -1` in WebSocket, that seems to be equivalent to not providing a marker, so that would be necessary if you wanted to set the later parameters. That's similar to how it works now.

If you want to provide a marker you would probably have to quote it, but that's OK. For example:

```
rippled -- account_tx rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn -1 -1 5 '{"ledger": 35842313,"seq": 2}' 1 0
```

... would be the equivalent of:

```
{
  "command": "account_tx",
  "account": "rf1BiGeXwwQoi8Z2ueFYTEXSwuJYfV2Jpn",
  "ledger_index_min": -1,
  "ledger_index_max": -1,
  "limit": 5,
  "marker": {
      "ledger": 35842313,
      "seq": 2
  },
  "binary": true,
  "forward": false
}
```

The commandline API is officially not a supported API so I think it's OK to make this change in a new rippled version without providing a migration path, especially since the new functionality does pagination better than the existing commandline interface. I expect most uses of the commandline interface are ad-hoc and the later arguments are probably used only rarely, so there shouldn't be that much disruption from a change like this.

**Pull request closed without merging**
