### PR TITLE
Fix RPC handlers to use the results of lookupLedger.

### PR DESCRIPTION
**Pull request by rec**
Reviewers:
  @JoelKatz @donovanhide

This is in response to "blocker" RIPD-698.

### CODE REVIEW

**Comment by vinniefalco** [comment]
This doesn't compile and has subtle conflicts with other pull requests, it needs to be re-evaluated.

**Comment by rec** [comment]
Hmm, let me look at this then.  This is two months old... :-(

**Comment by rec** [comment]
What makes you say it doesn't build?  I just tried it and it builds and tests fine...?

**Comment by rec** [comment]
This was committed a month or so ago, and I just checked the code to make sure!

Closing...

**Pull request closed without merging**
