### PR TITLE
[TRIVIAL] Reduce severity of some logging messages

### PR DESCRIPTION
**Pull request by JoelKatz**

### CODE REVIEW

**Comment by ximinez** [comment]
:+1:

**Comment by nbougalis** [comment]
:+1: But let's see if there's any other trivial logging fixes we want to make and merge into this.

**Comment by rec** [comment]
:+1:

I think we should just push this (once we have other complete changes) whether or not there are other logging fixes.

**Comment by JoelKatz** [comment]
If anyone wants to collect log messages that they think could use a severity reduction, we can get them in while this is still open. Or we can just do another one. One of these is really chatty and has made some people (including me) think there were issues in the history fetch changes, so that's kind of important to get in.

**Pull request closed without merging**
