### PR TITLE
Use C++14 lambda declaration.

### PR DESCRIPTION
**Pull request by ximinez**
Reviewers: @miguelportilla @HowardHinnant. This branch is currently forked from proposed 0.30.1-b2, which is pending merge. I'll rebase as soon as b2 is pushed to develop. Relevant changes start *after* `Set version to 0.30.1-b2`.

### CODE REVIEW

**Comment by ximinez** [comment]
This change was originally part of #1230, but because of uncertainty with forcing the move to C++14 / GCC 5.0, this was left out of that one when merged, and pulled into this separate PR for separate evaluation.

**Comment by HowardHinnant** [comment]
I get the expected warning concerning the use of the C++14 feature.  Tests pass.  As soon as we get the green light to have SConstruct use C++14 by default, I'm good with this.

**Comment by vinniefalco** [comment]
Needs a rebase

**Comment by ximinez** [comment]
Weird. Rebasing didn't change anything, so I was unable to get commit list to update. `git commit --amend` forced a new hash, and pushing that finally took care of the problem.

**Comment by miguelportilla** [comment]
I get c++14 warnings in Ubuntu and OS X as expected. In Ubuntu I see non related  "src/ripple/protocol/tests/digest_test.cpp:64:22: warning: unused variable 'r' [-Wunused-variable]" warnings which I believe are fixed in B4. Once merged, this should fine.

**Comment by ximinez** [comment]
Rebased on top of 0.30.1-b4. This should clear up the warnings. I'll check the CI results once they finish. @miguelportilla, can you check again, too?

**Comment by ximinez** [comment]
...At least in CI, all the build warnings are gone. There are some new warnings installing npm modules in clang builds, but those don't seem to affect anything.

**Comment by miguelportilla** [comment]
Checked again, warnings are gone.

**Comment by ximinez** [comment]
Thanks!

**Pull request closed without merging**
