### PR TITLE
Small fixes to locks and other little deficiencies.

### PR DESCRIPTION
**Pull request by rec**
@scottschurr @ximinez 

The shadow of the rejected wshadow branch...

### CODE REVIEW

**Comment by rec** [comment]
GAK.  

Sorry, this keyboard is dying - and this pull request was tiny pieces extracted from an already dying pull request.

I should get rid of it but it's the world's most comfortable keyboard... 

(fixed)

**Comment by scottschurr** [comment]
These all look like good changes to me (again).  :+1:

**Comment by ximinez** [comment]
Looks pretty uncontroversial. :+1:

**Comment by vinniefalco** [comment]
Please don't put *Passed* labels on commit messages that are clearly inappropriate

**Comment by vinniefalco** [comment]
The commit needs to be split into the beast and non-beast parts

**Comment by vinniefalco** [comment]
Suggested messages:
`Fix shadowing`
`Tidy up locks and locals`

**Comment by rec** [comment]
Done!

**Pull request closed without merging**
