### PR TITLE
shamap::Family dependency injection bundle

### PR DESCRIPTION
**Pull request by vinniefalco**
Simple refactoring to bundle together interfaces that are always injected as a group.

### CODE REVIEW

**Comment by HowardHinnant** [comment]
Compile-time error on OS X.  I believe this is while compiling debug/nonunity.  http://codepad.org/qNypOw0G

**Comment by vinniefalco** [comment]
Next time please just say
Missing include `#include <ripple\basics\StringUtilities.h>` in src/ripple/shamap/tests/common.h

**Comment by HowardHinnant** [comment]
With the latest fix (add missing include), I've got a repeatable hang in the --unittest.  The last thing output to the terminal is:
`ripple.shamap.sync`
During the hang, no significant CPU is being burned.  No significant amount of memory is being used.  Therefore it smells like a deadlock.  But I have not investigated further at this point.

**Comment by HowardHinnant** [comment]
Overall: I like this cleanup.  Clearly we need to figure out what's going on with the hang (which Travis is now replicating).  A cursory glance of the code did not give me any clues.

**Comment by vinniefalco** [comment]
Should be all fixed now thanks

**Comment by HowardHinnant** [comment]
:+1:  This builds without warnings on OS X.  This was built using `scons
debug` which builds both unity and non-unity builds.  The unity debug build
passes unittest, npm, syncs and stops.  The sync and stop tests were run
configured with nudb.

**Pull request closed without merging**
