### PR TITLE
Unit test pre-expired offer that also cancels an offer

### PR DESCRIPTION
**Pull request by scottschurr**
@mDuo13 had a question about the behavior of an offer that both:

1. Cancels an earlier offer on the same account, and
2. Failed because the new offer was not validated until after the expiration time.

This unit test explores the behavior.  Things behave much as I had hoped.  The expired offer does not succeed in canceling the other offer.  The expired offer also does not get into the ledger.

### CODE REVIEW

**Comment by scottschurr** [comment]
Thanks for the comment, @seelabs.  Adding the `close()` calls was quite intentional.  I have two motivations for that:

1. While we do care about the execution of transactions in the current ledger, the thing that matters most is what ends up in a validated ledger.  Without any `close()` calls you're not looking at the contents of the validated ledger.
2. Once you add one `close` call it's important to add lots or to think very hard about interactions between transactions.  Several times I've added a `close` late in a unit test (to a unit test without prior `close` calls) and had the test mysteriously wad up and die until I added `close` calls throughout.  Rather than go through that pain I conservatively add `close` calls.

I'm pretty sure the `fund`, `trust`, `pay` sequence from which you removed the `close` calls is not guaranteed to execute in that order in a validated ledger (depending on the accounts used).  The `fund` uses `masterpassphrase`'s sequence.  The `trust` uses `alice`'s sequence.  And the `pay` uses `gw`s sequence.  My understanding is that the execution order is only guaranteed if all three transactions are on the same account, in which case the transactions would have ascending sequence numbers.  Or if you add `close` calls between 😄.

What's worse is that the unit test will show that it is passing prior to the first `close` call, because the jtx framework bases its outcome on the non-final result of the transaction.  But if you examine the contents of the accounts after the `close` it is not at all what you intended or would expect from reading the unit test code.

I welcome a conversation if you disagree with either my motivations or my conclusions.  Thanks.

**Comment by sublimator** [comment]
TxnSignature is random

Close is explicit huh

**Comment by seelabs** [comment]
@scottschurr I don't think in practice a unit test will fail a fund/trust/pay sequence if a close is put after the `pay` - at least I've never seen it. However, I do understand your motivation of "this unit test cares about close, I'm putting one after every tx just to be safe". I'm fine keeping them here, but if we're going to continue to do this in other unit tests let's come up with a shorthand to submit a tx and close in one step so all the calls to `close` don't end up cluttering all the unit tests.

**Comment by scottschurr** [comment]
I think a shorthand for `close()` would be swell :+1:.

**Comment by bachase** [comment]
Merged in c6a307fcd776f2336bce77eef061ea56ee19a9f6

**Pull request closed without merging**
