### PR TITLE
[Trivial] Fix calling incorrect require function in tests

### PR DESCRIPTION
**Pull request by seelabs**
Reviewers: @scottschurr @rec

### CODE REVIEW

**Comment by scottschurr** [comment]
Assuming that my understanding of the change is correct, :+1:.  Nice catch.

I'll add that the mistake you corrected looks like it would be extraordinarily easy to make.  I'm surprised I didn't make it in any of my own unit tests.  I'd feel a lot more comfortable if the code misuse were caught automatically.  I can't think of a good way to catch the problem at compile time.  But, since the problem will only show up in unit tests, perhaps a runtime trap would be good enough.  We could potentially do something like this (in a separate pull request):
```
class require
{
private:
    require_t cond_;
    mutable bool emplaced = false; // new flag

public:
    template<class... Args>
    require(Args const&... args)
        : cond_(required(args...))
    {
    }

    // Add a destructor that tests the new flag.
    ~require()
    {
        // Assert if conditions passed to the constructor were not tested.
        assert (emplaced);
    }

    void
    operator()(Env const&, JTx& jt) const
    {
        jt.requires.emplace_back(cond_);
        emplaced = true;  // set flag to indicate conditions will be tested.
    }
};
```
This way any future misuses will be trapped the first time the unit test runs in debug mode.  Thoughts?

**Comment by seelabs** [comment]
@scottschurr: Yes, I was calling `jtx::require` and of course that test isn't a test at all.

The `emplace_` flag clever, but let's wait to see if anyone else makes this dumb mistake before we burden `require` with extra complexity. If they do then let's think about adding something like that.

**Comment by scottschurr** [comment]
I'm good with the wait-and-see approach.  But I was also thinking in a self-interested fashion.  I don't think I'm any more clever than you are.  So I believe I'm just as likely as you are to make the same mistake.  Still, even given that, I certainly won't push on adding the flag to `require` (or some other improvement).

**Comment by vinniefalco** [comment]
@scottschurr `jtx` funclets are copyable so this isn't guaranteed to work. `jtx` makes no attempt to be user friendly or discourage incorrect usage - instead, it is designed to allow skilled writers to create tests that are as compact and comprehensive as possible. Its a tradeoff, I hope the right one.

**Comment by scottschurr** [comment]
@vinniefalco: Good point about `jtx::require` being copyable.  I was just looking for a low-cost way to do a sanity check.  I guess that one wouldn't work.

**Comment by rec** [comment]
It sort of disturbs me that this test was testing nothing, we all missed it, and the possibility of this happening again still exists.   

The idea behind naming standards for variables and classes is to prevent this sort of thing - it's not obvious that the issue is that `Env::require` is a method but `test::jtx::require` is a class even once I knew the code was wrong.

**Comment by vinniefalco** [comment]
@scottschurr Another problem with the `emplace_` flag is that postconditions later in the chain don't get evaluated if early conditions fail.

@rec You have to know how `jtx` works, and that `test::jtx::require` is a lazily evaluated funclet. `jtx` names are not chosen to "prevent this sort of thing", and not chosen to make diagnosing usage errors easy. They are chosen to create a very compact vocabulary. You could argue that the `jtx` documentation could be better, and you'd win that argument. Or you could write something explaining how the framework operates.

**Comment by rec** [comment]
> jtx names are not chosen to "prevent this sort of thing", and not chosen to make diagnosing usage errors easy. 

Basically, I only have one priority - detecting and avoiding errors - and pretty well everything I say in a review aside from style quibbles is to that end.  So won't ever agree on this.

**Comment by seelabs** [comment]
@rec I'd like to get thumbs up on the trivial fixes in this. I think `jtx` fixes are out of scope for this PR (tho of course it was a good place for the discussion).

**Comment by rec** [comment]
:+1:

**Pull request closed without merging**
