### PR TITLE
Simplify Beast

### PR DESCRIPTION
**Pull request by nbougalis**
Simplify Beast:
* Remove asio HTTP classes
* Remove beast::File, beast::String, beast::Stream, beast::Array,
  beast::MemoryBlock, beast::CriticalSection and other unused
  classes.
* Remove unused platform-specific code.
* Reduce Beast custom assert and debugging helper macros.

### CODE REVIEW

**Comment by vinniefalco** [comment]
Nice bump up in coverage

**Comment by vinniefalco** [comment]
Can we please split this up so that all the removals are in one commit, and all the added lines are in the next commit?

**Comment by ximinez** [comment]
Reviewers: @ximinez @miguelportilla @vinniefalco

**Comment by vinniefalco** [comment]
I'm okay with all the removed lines :-)

**Comment by miguelportilla** [comment]
Fails to build.

Status.test.cpp missing #include <algorithm> for std::min

**Comment by nbougalis** [comment]
Vinnie, the "Simplify Beast" commit essentially only removes lines. Any additions are either #inlcudes or things like changing `bassert` to `assert`.

**Comment by vinniefalco** [comment]
There are code changes. For example, the file system changes. I can't audit them because the diff is too large. I'm okay with all the removed code and addition of includes.

**Comment by nbougalis** [comment]
Ah, you're right - I will split it.

**Comment by ximinez** [comment]
Love all the removals. :+1:

**Comment by miguelportilla** [comment]
OS X build fails:

In file included from src/ripple/core/tests/LoadFeeTrack.test.cpp:21:
In file included from src/ripple/core/LoadFeeTrack.h:23:
src/ripple/json/json_value.h:106:20: error: implicit instantiation of undefined template 'std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >'
    return strcmp(x.c_str(), y.c_str());
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:193:33: note: template is declared here
    class _LIBCPP_TYPE_VIS_ONLY basic_string;

**Comment by nbougalis** [comment]
@miguelportilla again? I thought I fixed that... gah.

**Comment by miguelportilla** [comment]
:+1:

**Comment by nbougalis** [comment]
Merged as 555cd59a592ee44222423d9fdeadb8d7df3af633, 77955c74bc99f24ef39582b74373190468e24f41, de4d872b7a4049a80c5071d46f96a1aebe62bccf and 78e59191ed7713ecc6bf36afe4f7a97e91653354.

**Pull request closed without merging**
