### PR TITLE
Rename legacy websocket and bring in new websocket.

### PR DESCRIPTION
**Pull request by rec**
I have a huge branch that depends on the new websocket - but unfortunately, having any sort of subtree completely freezes my ability to rebase in that branch, even changes long after the subtree.

If we can get in this pull request, which doesn't change any behavior, then I can actually rebase my main branch and clean up for submission.

Reviewer: @josh-ripple @vinniefalco

### CODE REVIEW

**Comment by josh-ripple** [comment]
Please separate whitespace changes into an initial commit.

**Comment by vinniefalco** [comment]
@josh-ripple Why?

**Comment by rec** [comment]
Travis doesn't like the submodule.  I got turned around, over all the open source projects I'm involve in it's about 50/50 submodule/subtree.

I can easily prepare a separate whitespace only change for the old websocket - I'm usually very big on that - BUT that whole delta doesn't change any actual behavior and touches a ton of files, some subset of which had some unused whitespace, so I can see the argument for keeping them altogether.

I'd like to get this in quick-as-a-bunny as it's blocking me - so let me know!

**Comment by josh-ripple** [comment]
Sounds like I've been politely overruled.  I concede.

**Comment by rec** [comment]
Don't worry, I'll back you up on "separating whitespace and business logic
changes" every time.

In my mind I think of two different sorts of changes - "obvious" changes
like whitespace or a rename, and "tricky" changes, which change actual
logic.  I just want to keep the big, obvious changes and the "tricky"
changes separate... the rest is gravy.

**Pull request closed without merging**
