### PR TITLE
Revert "Apply transaction batches in periodic intervals (#4504)"

### PR DESCRIPTION
**Pull request by scottschurr**
## High Level Overview of Change

This reverts commit 002893f280cbd578f0693d79e7b2304e3d9cd1d8.

There were two files with conflicts in the automated revert:

- src/ripple/rpc/impl/RPCHelpers.h and
- src/test/rpc/JSONRPC_test.cpp

Those files were manually resolved.

### Context of Change

There is currently no evidence that any problems were introduced by #4504.  However something is misbehaving on the current state of develop, and pull request #4504 was identified as a possible suspect.

### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by ckeshava** [comment]
the revert looks good to me 👍

**Review by ckeshava — APPROVED** [review]

**Comment by ckeshava** [comment]
I was slightly perplexed by the Github UI. It displays a different hash of f9e5cc351dee7beb55e9dcbc665302a75eb1bbb9 for the specified commit in the PR page. But, this hash object does not exist in `git log`


image

**Comment by intelliot** [comment]
f9e5cc3 was the commit hash before it was brought up-to-date with `develop` and then squash-merged.

**Comment by ckeshava** [comment]
i see, thanks for the explanation 👍

**Review by ximinez — APPROVED** [review]
Looks like a clean revert of the original PR.

**Pull request merged**
