### PR TITLE
Set quorum to tolerate 2 failures for validator list of 6 members.

### PR DESCRIPTION
**Pull request by mtrippled**

### CODE REVIEW

**Comment by mtrippled** [comment]
Without this PR, when moving from 5 to 6 validators, we will tolerate only 1 failure instead of 2. Quorum will go from 3/5 to 5/6. This fixes it so that the latter will be 4/6 (tolerating 2 failures. In each case, quorum for 7 and above allow at least 2 failures, so no modifications need to be made.

**Comment by wilsonianb** [comment]
Here's the unit test that should be updated. Unfortunately it wasn't checking things properly, which is why tests were still passing despite the change.
https://github.com/wilsonianb/rippled/commit/1cd6ff460dd24bd6bba7dcc55a7604a0cc616ccf

**Comment by mtrippled** [comment]
@wilsonianb fixed

**Comment by bachase** [comment]
Merged as dffb999efb8285334fe88d95011c0c17e3a352cd

**Pull request closed without merging**
