### PR TITLE
Simply function call profiling API

### PR DESCRIPTION
**Pull request by nbougalis**
Use variadic templates to consolidate multiple functions into one, and prefer to measure time using `std::chrono::high_resolution_clock` instead of Beast's high resolution clock.

Review: @vinniefalco, @HowardHinnant

### CODE REVIEW

**Comment by HowardHinnant** [comment]
:+1: Looks good to me.  My minor comments are optional.

**Comment by nbougalis** [comment]
ping @vinniefalco

**Comment by vinniefalco** [comment]
I'd prefer we removed all that crap entirely, I added it before I found out about `_NO_DEBUG_HEAP=1`. But that said, if you want to rearrange the deck chairs go for it
:+1:

**Comment by nbougalis** [comment]
I'm fine with removing the timing/profiling stuff completely.

**Comment by vinniefalco** [comment]
I'm down with whatever

**Comment by HowardHinnant** [comment]
:+1: on the latest.

**Comment by scottschurr** [comment]
Does the pull request name want to be "Simplify function call profiling API"?

**Comment by nbougalis** [comment]
Yeah, the name of the PR had a typo.

**Pull request closed without merging**
