### PR TITLE
Exit if OpenSSL doesn't have secp256k1 support (RIPD-900)

### PR DESCRIPTION
**Pull request by nbougalis**
@rec, @seelabs, @JoelKatz

### CODE REVIEW

**Comment by sublimator** [comment]
I thought we were using the bitcoin/secp256k1 lib now ?

**Comment by vinniefalco** [comment]
@sublimator The Bitcoin secp256k1 implementation is in the source tree, and the classes `PublicKey` and `SecretKey` use it, but we have not yet converted all the existing code which uses `RippleAddress` over to using `PublicKey` and `SecretKey` (although, we *have* done this for `AccountID`). We're proceeding cautiously, as secp256k1 is not officially at its first version.

**Comment by sublimator** [comment]
bitcoind uses by default?

**Comment by vinniefalco** [comment]
main screen turn on?

**Comment by sublimator** [comment]
mmmm so hot right now

**Comment by rec** [comment]
You need to update your vcxproj!

**Comment by nbougalis** [comment]
Project updated - thanks!

**Comment by seelabs** [comment]
:+1: I was worried about using mutex pre-startup (I remember having issues with that in the past). However, I tested on all platforms and it works as advertised.

**Comment by JoelKatz** [comment]
:+1:

**Comment by sublimator** [comment]
In a slightly more perfect world, where you had perfect confidence in the secp256k1 module (or at least as much as in OpenSSL), would that mean you could drop openssl? The base58 implementation no longer uses bignum right? What else do we use it for?

**Comment by nbougalis** [comment]
We cannot drop OpenSSL: It's used by `boost.asio` for SSL/TLS encryption (i.e. HTTPS)

**Comment by sublimator** [comment]
Ah! Yeah, I recall now :)

Thanks

**Comment by rec** [comment]
:+1:

**Pull request closed without merging**
