### PR TITLE
Two small things

### PR DESCRIPTION
**Pull request by JoelKatz**
Performance improvement in STArray (showed up in profiling).

Fix duplication of two caches and associated memory leak.

### CODE REVIEW

**Comment by vinniefalco** [comment]
There are some structural improvements that can be made but the logic is sound
:+1:

**Comment by nbougalis** [comment]
@JoelKatz: The `STArray` optimization is also part of #959. Would you prefer I remove it, or to combine the two PRs into one?

**Comment by JoelKatz** [comment]
@nbougalis Whatever you prefer.

**Comment by JoelKatz** [comment]
@vinniefalco Do you think any of your suggested changes are worth making?

**Comment by vinniefalco** [comment]
@JoelKatz The value of the suggested changes comes from removing two public member functions of `Application`. What's the value of that?

**Comment by nbougalis** [comment]
Integrated into #959 as 9b270d6 and f3f4b8f.

**Pull request closed without merging**
