### PR TITLE
Improve peer iteration in overlay

### PR DESCRIPTION
**Pull request by nbougalis**
Reviewers: it's important to verify that all the callback functions are safe to call without the overlay `mutex_` being held.

### CODE REVIEW

**Comment by vinniefalco** [comment]
Weakly against this. It covers up a symptom which is that other threads might share this control flow and mutate the container.

**Comment by seelabs** [comment]
I reviewed the code and I couldn't find any callback that required the mutex. Having said that, I'm going to advocate for keeping the lock during the iterations. Rational:

1) If we see a problem here, we won't know if it's because we didn't fix the old bug or if we introduced a new bug. If we keep the lock and still see a problem we know we didn't fix the old bug.

2) If we keep the lock it's trivial to verify this change is correct. 

3) We know we have another planned change in the pipeline - changing the recursive mutex to a regular mutex. That's going to require a careful audit. I'd propose we unlock during iteration when we make that change (and we should make a note `for_each` now that we can't keep the lock in the iteration if it's not recursive).

**Comment by seelabs** [comment]
We should fix the rvalue ref const issue, :+1: after that. Here's a commit to cherry pick if you want: https://github.com/seelabs/rippled/commit/dc263070c80918a3a257b5843299c81936a10892 (that commit also adds a comment explaining why the change to `for_each` was made).

**Comment by HowardHinnant** [comment]
No objections here, but I thought both Vinnie and David had some concerns.

**Comment by vinniefalco** [comment]
What is the motivation for changing this code and what is the rationale for why this new version is better?

**Comment by HowardHinnant** [comment]
👍

**Comment by vinniefalco** [comment]
Is this code also broken then?
https://github.com/ripple/rippled/blob/develop/src/ripple/server/impl/io_list.h#L236

**Comment by seelabs** [comment]
@vinniefalco In the `io_list::close` function the `map_` member variable is moved into a local `map` variable before the iteration, so iterating through the local `map` should be safe

**Comment by vinniefalco** [comment]
Documentation preview?

**Comment by seelabs** [comment]
:+1:

**Comment by nbougalis** [comment]
Merged as d572de769b7b5fbe0652c597ea225a1e206a07d1

**Pull request closed without merging**
