### PR TITLE
Fix resource leaks in ed25519-donna/fuzz

### PR DESCRIPTION
**Pull request by draane**
Add missing `fclose` calls for variable `f`

### CODE REVIEW

**Comment by nbougalis** [comment]
Hi! Thanks for your submission but **ed25519-donna** is a third-party library that we pull in as a dependency. I would urge you to submit this fix upstream, so that everyone using this library can benefit:

**Comment by MarkusTeufelberger** [comment]
More specifically upstream is https://github.com/floodyberry/ed25519-donna.

**Comment by carlhua** [comment]
Closing this PR - please submit this PR to upstream

**Comment by draane** [comment]
Hi, sorry for the delay in replying but I have been very busy.
Thank you for the pointer, I'll make the pull request to the library :+1:

**Pull request closed without merging**
