### PR TITLE
Document feature RPC command in --help.

### PR DESCRIPTION
**Pull request by scottschurr**
Reviewers: @nbougalis, @miguelportilla

### CODE REVIEW

**Comment by nbougalis** [comment]
I'm ok with this, but we need to make it very clear that `accept` and `reject` via RPC aren't permanent. Once the server restarts, the feature that was accepted or rejected will return to its default state.

**Comment by scottschurr** [comment]
We could either leave that documentation to @mDuo13, or I could omit the `[accept|reject]` part.  @mDuo13, what do you prefer?

**Comment by mDuo13** [comment]
include it and I'll cover it in the docs

**Comment by nbougalis** [comment]
:+1:

**Comment by miguelportilla** [comment]
:+1:

**Comment by nbougalis** [comment]
Merged as f15cc6c4f64421cd5e4581e7c122c51075440a89

**Pull request closed without merging**
