### PR TITLE
Fix include guards in rippled.

### PR DESCRIPTION
**Pull request by rec**
Using script https://github.com/rec/cppguards/blob/master/cppguards.py

Reviewer: @vinniefalco @seelabs

### CODE REVIEW

**Comment by vinniefalco** [comment]
No love for beast?

**Comment by vinniefalco** [comment]
:+1:

**Comment by rec** [comment]
I'll do a separate beast run.

**Comment by rec** [comment]
Interesting - the beast code isn't UTF-8!  Developing...

**Comment by vinniefalco** [comment]
What do you mean beast code isn't UTF-8? All source files should be plain ascii (except for the vcxproj which needs a byte order mark).

**Comment by rec** [comment]
I'll instrument which file it is, but some .h file has a character >=128 in
it...

**Comment by vinniefalco** [comment]
@rec Probably urls_large.hpp or something

**Comment by rec** [comment]
It turns out to be the string Daniel Lidström which appears in all the
files in sqdb!

**Comment by vinniefalco** [comment]
LOL!!!!!

**Pull request closed without merging**
