### PR TITLE
Doc consolidation

### PR DESCRIPTION
**Pull request by undertome**
This PR consolidates Benchmarks.md, DeterministicShard.md, ShardStoragePaths.md, and ShardValidation.md into a single README file in the nodestore directory. It's based on  #3463 which has yet to be reviewed.

### CODE REVIEW

**Comment by cjcobb23** [comment]
@undertome what files or commits do you want reviewed as part of this PR? It seems that some of the commits are part of a different PR.

**Comment by undertome** [comment]
> @undertome what files or commits do you want reviewed as part of this PR? It seems that some of the commits are part of a different PR.
Just 89f12d4 and de4bfab (the last two). The others are from #3463 which is unmerged.

**Comment by miguelportilla** [comment]
👍

**Comment by undertome** [comment]
**FYI:** The latest force-push removes `DeterministicShard` documentation (since it was removed from develop) and updates shard storage path documentation which was modified in  #3463. It's also been rebased onto that PR to simplify merging.

**Comment by undertome** [comment]
Another force push to reflect documentation changes in #3463.

**Pull request closed without merging**
