### PR TITLE
Update libarchive version

### LINKED ISSUE #3215: error: 'CC_MD5_Final' is deprecated
I got an MD5 error when trying to install rippled on Mac Catalina 10.15.2

```
make[3]: warning: -jN forced in submake: disabling jobserver mode.
/Users/denisangell/projects/xrp/rippled/.nih_c/unix_makefiles/AppleClang_11.0.0.11000033/Debug/src/libarchive/libarchive/archive_digest.c:162:3: error: 'CC_MD5_Init' is deprecated: first deprecated in macOS 10.15 - This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger). [-Werror,-Wdeprecated-declarations]
  CC_MD5_Init(ctx);
  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/CommonCrypto/CommonDigest.h:133:12: note: 'CC_MD5_Init' has been explicitly marked deprecated here
extern int CC_MD5_Init(CC_MD5_CTX *c)
           ^
/Users/denisangell/projects/xrp/rippled/.nih_c/unix_makefiles/AppleClang_11.0.0.11000033/Debug/src/libarchive/libarchive/archive_digest.c:170:3: error: 'CC_MD5_Update' is deprecated: first deprecated in macOS 10.15 - This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger). [-Werror,-Wdeprecated-declarations]
  CC_MD5_Update(ctx, indata, insize);
  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/CommonCrypto/CommonDigest.h:136:12: note: 'CC_MD5_Update' has been explicitly marked deprecated here
extern int CC_MD5_Update(CC_MD5_CTX *c, const void *data, CC_LONG len)
           ^
/Users/denisangell/projects/xrp/rippled/.nih_c/unix_makefiles/AppleClang_11.0.0.11000033/Debug/src/libarchive/libarchive/archive_digest.c:177:3: error: 'CC_MD5_Final' is deprecated: first deprecated in macOS 10.15 - This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger). [-Werror,-Wdeprecated-declarations]
  CC_MD5_Final(md, ctx);
  ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/CommonCrypto/CommonDigest.h:139:12: note: 'CC_MD5_Final' has been explicitly marked deprecated here
extern int CC_MD5_Final(unsigned char *md, CC_MD5_CTX *c)
           ^
3 errors generated.
make[6]: *** [libarchive/CMakeFiles/archive_static.dir/archive_digest.c.o] Error 1
make[6]: *** Waiting for unfinished jobs....
make[5]: *** [libarchive/CMakeFiles/archive_static.dir/all] Error 2
make[4]: *** [libarchive/CMakeFiles/archive_static.dir/rule] Error 2
make[3]: *** [archive_static] Error 2
CMake Error at /Users/denisangell/projects/xrp/rippled/.nih_c/unix_makefiles/AppleClang_11.0.0.11000033/Debug/src/libarchive-stamp/libarchive-build-Debug-impl.cmake:9 (message):
  Command failed (2):

   '/usr/local/Cellar/cmake/3.15.5/bin/cmake' '--build' '.' '--config' 'Debug' '--target' 'archive_static' '--parallel' '2' ''



CMake Error at /Users/denisangell/projects/xrp/rippled/.nih_c/unix_makefiles/AppleClang_11.0.0.11000033/Debug/src/libarchive-stamp/libarchive-build-Debug.cmake:23 (message):
  Command failed: 1

   '/usr/local/Cellar/cmake/3.15.5/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/Users/denisangell/projects/xrp/rippled/.nih_c/unix_makefiles/AppleClang_11.0.0.11000033/Debug/src/libarchive-stamp/libarchive-build-Debug-impl.cmake'

  See above



make[2]: *** [../.nih_c/unix_makefiles/AppleClang_11.0.0.11000033/Debug/src/libarchive-stamp/libarchive-build] Error 1
make[1]: *** [CMakeFiles/libarchive.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 58%] Completed 'soci'
-- rocksdb build command succeeded.  See also /Users/denisangell/projects/xrp/rippled/.nih_c/unix_makefiles/AppleClang_11.0.0.11000033/Debug/src/rocksdb-stamp/rocksdb-build-*.log
[ 60%] Built target soci
[ 61%] No install step for 'rocksdb'
[ 61%] No test step for 'rocksdb'
[ 62%] Completed 'rocksdb'
[ 63%] Built target rocksdb
make: *** [all] Error 2

```

### PR DESCRIPTION
**Pull request by yusufsahinhamza**
Fixes #3215
Tested with **macOS Catalina (version 10.15)**

### CODE REVIEW

**Comment by nbougalis** [comment]
Thank you for your contribution.

**Comment by thejohnfreeman** [comment]
Version 3.4.2 fails to build with Visual Studio 2017 because of unreachable code. @EricAustinYu [diagnosed](https://github.com/libarchive/libarchive/issues/861#issuecomment-613552463) this problem in the libarchive project, and submitted a [patch](https://github.com/libarchive/libarchive/pull/1360), but libarchive has not publicly acknowledged either yet. I would personally rather use a vanilla version between 3.3.3 and 3.4.2 that still fixes #3215 than apply patches during the build process.

**Comment by yusufsahinhamza** [comment]
@thejohnfreeman 

17 hours ago from now **libarchive** merged an PL (https://github.com/libarchive/libarchive/pull/1364) for disabling MD5 errors, but i'm not sure when they are going to release it. So i think there still could be those MD5 errors in the versions of **libarchive** between 3.3.3 and 3.4.2.

Did you tried any version of **libarchive** between 3.3.3 and 3.4.2 for build **rippled** with Visual Studio 2017?

**Comment by thejohnfreeman** [comment]
I haven't tried any other versions, no, but as of now this PR is trading one build error on one platform for a different build error on a different platform. I think we should wait to upgrade our default version until libarchive releases one that has no build errors on any platforms. In the meantime, you should be able to override individual dependencies by installing them yourself and passing `<PackageName>_ROOT` to CMake.

**Comment by yusufsahinhamza** [comment]
Hi @thejohnfreeman and @manojsdoshi, 

Finally they just released a new version of libarchive, [v3.4.3](https://github.com/libarchive/libarchive/releases/tag/v3.4.3).

They are already merged some pull requests (https://github.com/libarchive/libarchive/pull/1364 & https://github.com/libarchive/libarchive/pull/1360) about this issue so i will update the libarchive to it's latest version now.

**Pull request closed without merging**
