### PR TITLE
Levelize RipplePathFind.h

### PR DESCRIPTION
**Pull request by ximinez**
Nearly trivial.

Reviewers: @vinniefalco, @seelabs

### CODE REVIEW

**Comment by vinniefalco** [comment]
This needs to be applied to *b2* after b2 is pushed, since there are changes to signatures.

**Comment by ximinez** [comment]
Reopening this PR to rebase against 0.29.0-b2. Will push the results in a few minutes.

**Comment by ximinez** [comment]
@vinniefalco Ok, ready to go.

**Comment by rec** [comment]
Obviously correct:  :+1:

**Comment by seelabs** [comment]
:+1: Just built non-unity and quick look at code.

**Pull request closed without merging**
