### PR TITLE
Chrono fixes for VS Update 2

### PR DESCRIPTION
**Pull request by seelabs**
MSVS 2015 Update 2 includes an updated chrono implementation that overlaps with our own chono code. This PR disables our chono code when compiling with MSVC 2015 Update 2.

@miguelportilla @HowardHinnant

### CODE REVIEW

**Comment by miguelportilla** [comment]
:+1:  Unity and non Unity Debug/Release build fine on Visual Studio 2015 v.14.0.24720.00 Update 1.

**Comment by HowardHinnant** [comment]
:+1:

**Comment by HowardHinnant** [comment]
Still :+1:

**Comment by seelabs** [comment]
@miguelportilla @HowardHinnant I pushed another set of commits to address comments and take care of a some warnings I noticed (I see Howard already reviewed as I was testing :-) Mickey, I'd love it if you could compile on Update 1 again to make sure I didn't muck it up.

**Comment by seelabs** [comment]
Rebased onto b10

**Comment by miguelportilla** [comment]
:+1:  Changes LTGM. Unity and non Unity Debug/Release build fine on Visual Studio 2015 with Update 1. All tests pass.

**Comment by seelabs** [comment]
Squashed

**Pull request closed without merging**
