### PR TITLE
Drop nexmo SMS support. Reverts 58b3cc1d.

### PR DESCRIPTION
**Pull request by tdfischer**
I have no idea if this is actually a thing that is still used. I can't imagine that Rippled *really* needs to be able to send SMSs.

If I'm wrong, please just close this. Otherwise, here, have a patch that makes rippled one tiny iota simpler :heart: 

Reviewers: @vinniefalco @rec @ahbritto

### CODE REVIEW

**Comment by tdfischer** [comment]
circle test fails 'cuz I still had that hook enabled on my fork, its safe to ignore.

**Comment by nbougalis** [comment]
I'm in favor of this, however we should probably deprecate the feature, wait for a release cycle and then drop it entirely. 

Other than that, I give it a :+1:

**Comment by rec** [comment]
How exactly DO we deprecate a feature, anyway?

**Comment by nbougalis** [comment]
@rec: by adding "Version a.b.c deprecates the SMS feature. The feature will be removed with version b.c.d" in the release notes.

**Comment by rec** [comment]
Apparently this means contacting @yana-novikova

**Comment by rec** [comment]
"We should make sure integration has no objection. This isn't a major or really supported feature so the barrier to removing might not be high as other things.

I posted to architects, I'm not entirely sure if contacting you is "integration"?  :-)

**Comment by yana-novikova** [comment]
I will follow-up with integration

**Comment by nbougalis** [comment]
I am marking this as *HOLD*. @rec, if this passes technical muster, then tag it as passed. I'm signing off on this instead of Vinnie.

**Comment by nbougalis** [comment]
@tdfischer: please run `scons vcxproj` on this, then squash and push.

**Comment by tdfischer** [comment]
@nbougalis done. is the scons vcxproj supposed to be squashed as well? I thought it was meant to always be a separate commit.

**Comment by rec** [comment]
Nope, put 'em altogether.  Otherwise, there'd be a point between the two commits where the state of the project was inconsistent!

**Comment by nbougalis** [comment]
Merged as a90bb53cd295ad5558cbf63441351e8038a78862

**Pull request closed without merging**
