### PR TITLE
CMake: build consistently with default (unspecified) target

### PR DESCRIPTION
**Pull request by ximinez**
After the last round of changes, calling `cmake` on an empty folder would build the default target correctly, but subsequent calls would not - the primary symptom was switching the build from unity to nonunity. This change stores the `target` in the cache, and sets some of the flags appropriately even if `target` is not set.

### CODE REVIEW

**Comment by seelabs** [comment]
Would change the if statement on line 15 to `  if (NOT target)` do the same thing? If so that feels nicer than using the cache.

**Comment by seelabs** [comment]
replying to myself. Nevermind, I see the difference. It's not the same.

**Comment by seelabs** [comment]
:+1:

**Comment by seelabs** [comment]
Side note: I always test with `-Dtarget=Something`. I'm not sure how well this works with `-DCMAKE_BUILD_TYPE` without specifying a target. We may want to support that case by setting the correct compiler and `unity` build. If we do that I'd want to remove `target` from the cache and rm the `NOT CMAKE_BUILD_TYPE` from the if statement. But not for this PR.

**Comment by ximinez** [comment]
> I'm not sure how well this works with -DCMAKE_BUILD_TYPE without specifying a target.

Let's find out.
Windows:
```
$ rm -rf build/cmake/*
$ cd build/cmake/
$ cmake -G"Visual Studio 14 2015 Win64" -Dassert=true -DCMAKE_BUILD_TYPE=Debug  ../..
[...]
$ grep target CMakeCache.txt
//Build target
target:STRING=
$ grep CMAKE_BUILD_TYPE CMakeCache.txt
CMAKE_BUILD_TYPE:INTERNAL=Debug
$ grep vcxproj rippled.sln
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "rippled", "rippled.vcxproj", "{84B78374-85B6-3015-B1C4-53DB2D429833}"
[...]
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "rippled_classic", "rippled_classic.vcxproj", "{8A270834-066B-3F37-894C-E082ED6F74B3}"
$ cmake .
[...]
$ grep vcxproj rippled.sln
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "rippled", "rippled.vcxproj", "{84B78374-85B6-3015-B1C4-53DB2D429833}"
[...]
Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "rippled_classic", "rippled_classic.vcxproj", "{8A270834-066B-3F37-894C-E082ED6F74B3}"
```
So that looks fine.

However, on Ubuntu:
```
$ cmake ../../.. -DCMAKE_BUILD_TYPE=Debug
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:69 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:69 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/eah/dev/rippled/build/cmake/default/CMakeFiles/CMakeOutput.log".
See also "/home/eah/dev/rippled/build/cmake/default/CMakeFiles/CMakeError.log".
```
So that's a problem, and I'm going to try to fix it, because it doesn't error out without these changes, though it uses `cc`/`c++` and defaults to a nonunity build, but at least it does _something_

**Comment by ximinez** [comment]
@bachase @seelabs I pushed a commit which turned out to be a pretty small change, and addresses @seelabs's concern about the mix of command line params, and I think makes it more robust overall.

**Comment by seelabs** [comment]
@ximinez Love it! Thanks for doing that. Now with that change I don't think `target` needs to be in the cache anymore. What do you think about removing `target` from the cache?

**Comment by ximinez** [comment]
@seelabs Let's think it through. On the first run, if `target` is on the command line, it'll go straight into the cache anyway. If not on the command line, it'll be initialized to the preferred default regardless of what else is on the command line.  ...On subsequent runs, if `target` is on the command line, it'll act like the first run. If not, then it'll be pulled from the cache. If it's not in the cache, it'll be initialized to the preferred default yet again.

So yeah, I don't think there's any need to store it explicitly in the cache either. I'll confirm and push a change ASAP.

**Comment by seelabs** [comment]
:+1:

**Comment by bachase** [comment]
Still 👍 from me. Just testing that builds work as you describe.

**Pull request closed without merging**
