### PR TITLE
Make repo available for deb 11 bullseye

### PR DESCRIPTION
**Pull request by legleux**
## High Level Overview of Change
Debian 11 Bullseye doesn't have its own directory in the repo right now.
During the next release this will create it.

### Type of Change

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by manojsdoshi — APPROVED** [review]
LGTM

**Comment by legleux** [comment]
Let me add a debian 11 test to pull from this repo before merging this.

**Comment by MarkusTeufelberger** [comment]
Please also remove at least Xenial, it is out of support for a while now.

**Comment by legleux** [comment]
Addressed in https://github.com/ripple/rippled/pull/4064/

**Pull request closed without merging**
