### PR TITLE
Include field name when diagnosing field not found

### LINKED ISSUE #3263: Include field name when diagnosing "Field not found"
There are 10 instances (in `STObject.{h,cpp}`) of throwing an exception with the description "Field not found" in the presence of an `SField`, which has a name, but without including that name. We should include that name.

### PR DESCRIPTION
**Pull request by thejohnfreeman**
Closes #3263

### CODE REVIEW

**Comment by thejohnfreeman** [comment]
It would be nice to amend the "Wrong field type" messages to include the type, but I haven't dug into how to stringify the type. Pointers appreciated.

**Comment by scottschurr** [comment]
If you have an `SField` at hand it has a `fieldName` data member that you can use for the name.  Is that what you are looking for?

**Comment by thejohnfreeman** [comment]
Right, that's what I used (through the method `getName`). The problem is that the previous throws failed to include the name in the exception message.

**Comment by seelabs** [comment]
@thejohnfreeman  Looks like we need to fix the STTx unit tests in two places:
1. https://github.com/thejohnfreeman/rippled/blob/field-not-found/src/test/protocol/STTx_test.cpp#L1286-L1288
2. https://github.com/thejohnfreeman/rippled/blob/field-not-found/src/test/protocol/STTx_test.cpp#L1351-L1353

Other than that, nice change! I'll give a thumbs up after the tests are fixed.

**Pull request closed without merging**
