### PR TITLE
Remove temp_db (RIPD-887)

### PR DESCRIPTION
**Pull request by seelabs**
@miguelportilla @rec

### CODE REVIEW

**Comment by vinniefalco** [comment]
It uses the active voice or else it gets the stick

**Comment by rec** [comment]
All that red... what's not to like?

:+1:

**Comment by vinniefalco** [comment]
@MarkusTeufelberger Yes, SQLite is no longer an available node_db type

**Comment by MarkusTeufelberger** [comment]
Then these tests in src/ripple/nodestore/tests/Database.test.cpp that concern sqlite should be removed too I guess...

**Comment by vinniefalco** [comment]
@MarkusTeufelberger Yes

**Comment by rec** [comment]
Still :+1:!

**Comment by miguelportilla** [comment]
:+1:

**Comment by vinniefalco** [comment]
Squash please

**Comment by seelabs** [comment]
@vinniefalco Squashed

**Comment by vinniefalco** [comment]
"API Change" because this needs partner messaging

**Pull request closed without merging**
