### PR TITLE
Json Cleanup

### PR DESCRIPTION
**Pull request by nbougalis**
This cleanup forks our existing JSON library and begins removing some code and JSON support which we do not need. I plan on maintaining and improving this code significantly going forward, and bringing it up to date with C++11/C++14.

Reviews: @rec, @vinniefalco

### CODE REVIEW

**Comment by rec** [comment]
Don't forget to add labels!  :-)

**Comment by rec** [comment]
OK, I added labels, you slack dog.  :-P  Reviewing....

**Comment by rec** [comment]
Tiny comment, otherwise good.  :+1:

**Comment by rec** [comment]
Add this tiny comment and I'll mark it as approved!  :-)

**Comment by vinniefalco** [comment]
How comprehensive is the unit test coverage?

**Comment by rec** [comment]
It's no worse than it was before - which is to say that all the stuff we use in Json seems to be tested pretty thoroughly...

**Comment by nbougalis** [comment]
@vinniefalco just adding a bit to what @rec said: this mostly *removes* functionality (such as supports for comments inside JSON) which we were not using and integration with "CPP-TL" which is a template library of sorts.

As I get more into this, I plan on adding specific unit tests to it, to exercise new code. I didn't really think it made much sense to write unit tests for code that was being removed and was already unused in practice.

**Comment by nbougalis** [comment]
@rec: wilco, thanks for the review.

**Comment by vinniefalco** [comment]
@nbougalis So this is "removing code?"
https://github.com/nbougalis/rippled/commit/ed29ccc80dccd541e21972196ec7b79635df2dc2#diff-a67364b76ebee3988993db290840b0f7R570

**Comment by nbougalis** [comment]
I said _mostly_. If you'd prefer that this be removed (or a unit test be added for it) I can do that.

**Comment by vinniefalco** [comment]
We should add tests, but we don't need to do it now. Maybe someone new can write them.
:+1:

**Comment by rec** [comment]
:+1:

**Comment by rec** [comment]
This needs a rebase!

**Comment by rec** [comment]
(I tried to do it myself, but I ended up with unit test failures I don't fully understand...)

**Comment by nbougalis** [comment]
This has been rebased against the latest develop.

**Comment by rec** [comment]
I'll try to do another push later today...!

**Pull request closed without merging**
