### PR TITLE
Add Eclipse build instructions

### PR DESCRIPTION
**Pull request by crazyquark**
Switched to develop branch for a more clean pull request.

### CODE REVIEW

**Comment by nbougalis** [comment]
I am not sure why, but the *.png* files associated with this commit actually contain *html* content. Any idea why that is @crazyquark?

**Comment by vinniefalco** [comment]
Its not clear that after merging, the resulting Eclipse README.md will refer to images hosted within the repository.

**Comment by rec** [comment]
Ping?

We'd like to use this change, but the .png files with .html content in them make us nervous...

**Comment by vinniefalco** [comment]
I don't mind the html content but we shouldn't be linking to a forked repo

**Comment by crazyquark** [comment]
Ah, sorry about that. The Markdown needs to be edited to point to your repo instead of my fork.
Not sure about the PNGs. I just made them with "Shutter" on Linux, a tool similar to Snipping Tool on Windows.

**Comment by crazyquark** [comment]
I corrected the png paths. I don't know about the html content...

**Comment by vinniefalco** [comment]
@crazyquark Can you please email me the .png files? vinnie@ripple.com and I will fix this branch. Thanks

**Comment by vinniefalco** [comment]
Replaced by:
https://github.com/ripple/rippled/pull/1065

**Comment by crazyquark** [comment]
OK, I will email you the .png files.

**Pull request closed without merging**
