### PR TITLE
Let SIGINT terminate rippled during unit testing

### PR DESCRIPTION
**Pull request by josh-ripple**

### CODE REVIEW

**Comment by josh-ripple** [comment]
Reviewers: @vinniefalco

**Comment by josh-ripple** [comment]
More reviewers: @ximinez

**Comment by ximinez** [comment]
Windows nonunity build fails
```
cl /Fobuild\msvc.debug.nounity\src\ripple\app\main\Main.obj /c src\ripple\app\main\Main.cpp /TP /nologo /bigobj /EHa /fp:precise /Gd /Gm- /GR /Gy- /FS /MP /openmp- /Zc:forScope /Zi /errorReport:none /nologo /W3 /WX- /wd"4018" /wd"4244" /wd"4267" /wd"4800" /GS /MTd /Od /RTC1 /DOPENSSL_NO_SSL2 /DDEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER /DHAVE_USLEEP=1 /DDEBUG /D_DEBUG /D_WIN32_WINNT=0x6000 /D_SCL_SECURE_NO_WARNINGS /D_CRT_SECURE_NO_WARNINGS /DWIN32_CONSOLE /D_CRTDBG_MAP_ALLOC /Isrc\soci\src\core /Isrc\sqlite /IC:\boost_1_57_0 /IC:\OpenSSL-Win64\include /Isrc /Isrc\beast /Ibuild\proto /Isrc\soci\src /Isrc\protobuf\src /Isrc\protobuf\vsprojects
Main.cpp
src\ripple\app\main\Main.cpp(206) : error C2065: 'SIGINT' : undeclared identifier
src\ripple\app\main\Main.cpp(206) : error C2065: 'SIG_DFL' : undeclared identifier
src\ripple\app\main\Main.cpp(206) : error C3861: 'signal': identifier not found
scons: *** [build\msvc.debug.nounity\src\ripple\app\main\Main.obj] Error 2
scons: building terminated because of errors.
```

**Comment by nbougalis** [comment]
Sorry, but this gets a :-1: from me:

`ApplicationImp` constructs a `boost::asio::signal_set` which intercepts `SIGINT`. According to the [Boost documentation](http://www.boost.org/doc/libs/1_57_0/doc/html/boost_asio/reference/signal_set.html#boost_asio.reference.signal_set.multiple_registration_of_signals), setting a handler using `signal` for a signal managed by a `boost::asio::signal_set` is not allowed.

The _actual_ problem here is that when running unit tests, we do not end up calling `ApplicationImp::setup` which is what starts an `async_wait` on the signal set and causes the stop. I have two proposed solutions:

* Easy: construct the `m_signal_set` in `ApplicationImp::setup`, allowing the default semantics of `SIGINT` to apply, terminating the process.
* Harder: directly or indirectly call `ApplicationImp::setup` when running unit tests, which is a bigger, more involved change.

**Comment by josh-ripple** [comment]
Superseded by <https://github.com/ripple/rippled/pull/1024>.

**Pull request closed without merging**
