### PR TITLE
Improved 0.27 -> 0.28 switchover semantics:

### PR DESCRIPTION
**Pull request by nbougalis**
* Support PreviousTxnID until the switchover
* Implement "No Ripple" for issue_iou and redeem_iou.
* Do not utilize issue_iou and redeem_iou from legacy code
* Rename 0.27 legacy files to account for VS build process
* Misc. cleanups

Reviews: @JoelKatz, @vinniefalco

### CODE REVIEW

**Comment by rec** [comment]
Travis failure seem legit - a compilation failure!

**Comment by nbougalis** [comment]
Silly typo - shall be fixed. Thanks.

**Comment by vinniefalco** [comment]
Commit message should read `0.27.0` not `0.27`. Alternatively one could write:
`Improved version switchover semantics:`

**Comment by nbougalis** [comment]
Quickly addressing Vinnie's comments.

**Comment by nbougalis** [comment]
Merged as a7efdb4e522a7d65a0035a462afacc5e3b47f6dd

**Pull request closed without merging**
