### PR TITLE
Remove legacy logging

### PR DESCRIPTION
**Pull request by nbougalis**
This PR, which is based off the work in #1511, removes the legacy logging APIs `WriteLog`, `CondLog` and `ShouldLog`. A new API, `debugJournal` can be used when logging from places where a journal is not available.

Commits cecb10d and 3a155b2 are unrelated cleanups that I stumbled upon. Please review them carefully.

@scottschurr, @vinniefalco

### CODE REVIEW

**Comment by scottschurr** [comment]
:+1: I brought up a couple of items, but I think it's good as it stands.

**Comment by nbougalis** [comment]
@scottschurr: I have addressed all the things you pointed out; I'm going to rebase and squash.

**Comment by scottschurr** [comment]
:+1:

**Comment by nbougalis** [comment]
Merged as 5ac744ff6694847cf8e209a8d34a2f9119b57648, 57d6ab091ca333d28d5dc876bf0e7839c8ce157a and 2be11874e3969f67de67e7b29419d699c64a84ff.

**Pull request closed without merging**
